spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/KinesisTDigestReader.java
This makes the reader more forgiving of bad records
in the stream. Bad records will now get logged and
increment a counter so we can detect the condition
easily.
=> skip bad records

spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/StepDigest.java, spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/StepDigestTest.java, spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestWriterTest.java
Add test case for the step digest and fix
the add method to actually release the lock.
=> add test case for digest

gradle.properties, spectator-nflx-plugin/build.gradle, spectator-nflx/build.gradle, spectator-reg-tdigest/build.gradle
Internal platform is moving to guice4. Updating dependency
to stay consistent.
=> update to guice4

build.gradle
Import of the project into idea isn't working correctly
with the older version. It seems to work fine with the
0.2.0 version.
=> update gradle jmh plugin

spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SpectatorReporter.java, spectator-ext-spark/src/test/java/com/netflix/spectator/spark/SpectatorReporterTest.java
Added basic test case covering this issue. Need to increase
coverage of other types, but that can be done in future PRs.
=> fix counter increments for reporter

spectator-ext-spark/build.gradle, spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SidecarRegistry.java
There was a hack to manually create the json due to
some issues with trying to avoid conflicts. This change
switches to a minimal json library and relocates it
in the shadow jar to avoid any conflicts with other
users.
=> switch to proper json lib

spectator-api/src/test/java/com/netflix/spectator/api/DefaultTimerTest.java
Someone wanted an example of using lambda with timers,
this change updates one of the timer test cases until
I get time to update the wiki.
=> add example for using lambda with timer

spectator-api/src/main/java/com/netflix/spectator/api/CompositeCounter.java, spectator-api/src/main/java/com/netflix/spectator/api/CompositeDistributionSummary.java, spectator-api/src/main/java/com/netflix/spectator/api/CompositeMeter.java, spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java, spectator-api/src/main/java/com/netflix/spectator/api/CompositeTimer.java, spectator-api/src/main/java/com/netflix/spectator/api/RegistryMeter.java, spectator-api/src/main/java/com/netflix/spectator/api/Spectator.java, spectator-api/src/test/java/com/netflix/spectator/api/CompositeCounterTest.java, spectator-api/src/test/java/com/netflix/spectator/api/CompositeDistributionSummaryTest.java, spectator-api/src/test/java/com/netflix/spectator/api/CompositeRegistryTest.java, spectator-api/src/test/java/com/netflix/spectator/api/CompositeTimerTest.java
This change will allow the sub-registries for the composite
to change during runtime.
=> allow adding and removing from the composite

spectator-ext-aws/src/main/java/com/netflix/spectator/aws/SpectatorRequestMetricCollector.java
Endpoint values currently include https:// prefix
adding noise the the metrics. Also it is easier to
do a quick prefix on the type without the scheme
being present.
=> extract host name from service endpoint

spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoId.java, spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoIdTest.java
=> override equals and toString for ServoId

spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileDistributionSummary.java, spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileTimer.java
Zero pad the tag value for the percentile key.
=> zero pad the tag value

spectator-api/src/main/java/com/netflix/spectator/api/Functions.java, spectator-api/src/main/java/com/netflix/spectator/api/Registry.java, spectator-api/src/test/java/com/netflix/spectator/api/ExtendedRegistryTest.java, spectator-api/src/test/java/com/netflix/spectator/api/FunctionsTest.java
Eliminate raw types and unchecked casts
=> Improve type safety

spectator-reg-metrics3/src/main/java/com/netflix/spectator/metrics3/MetricsGauge.java, spectator-reg-metrics3/src/main/java/com/netflix/spectator/metrics3/MetricsGaugeAggr.java, spectator-reg-metrics3/src/main/java/com/netflix/spectator/metrics3/MetricsRegistry.java, spectator-reg-metrics3/src/main/java/com/netflix/spectator/metrics3/NameUtils.java, spectator-reg-metrics3/src/test/java/com/netflix/spectator/metrics3/MetricsRegistryTest.java
Hi!
I added support for Metrics3 Gauge, so when using reporting functions from Metrics3 it gets the values for Gauges too.
=> Added support for Metrics3 Gauge

README.md, docs/ext/jvm-gc.md, docs/ext/log4j2.md, docs/index.md, docs/intro/netflix.md, docs/registry/metrics3.md, docs/registry/servo.md, docs/registry/tdigest.md, docs/reports.md, mkdocs.yml, scripts/Makefile, scripts/update-gh-pages.sh
Use a makefile to simplify the logic. Change it to
update a particular version for a given run. This should
make it easier to integrate into the build at some point.
=> update gh-pages helper script

README.md, docs/ext/jvm-gc.md, docs/ext/log4j2.md, docs/index.md, docs/intro/netflix.md, docs/registry/metrics3.md, docs/registry/servo.md, docs/registry/tdigest.md, spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java, spectator-api/src/test/java/com/netflix/spectator/api/ArrayTagSetTest.java, spectator-api/src/test/java/com/netflix/spectator/api/DefaultIdTest.java
It was using the full array length before which
can lead to ArrayIndexOutOfBoundsExceptions if
a dedup occurs before an append.
/cc @daveray
=> restrict search to used portion of array

docs/intro/clock.md, docs/intro/gauge.md, docs/intro/registry.md, docs/intro/timer.md, mkdocs.yml
Addresses some of the issues in #296
=> docs: add pages for registry and clock

spectator-agent/src/main/java/com/netflix/spectator/agent/JmxData.java, spectator-agent/src/main/resources/tomcat.conf
Provides compatible metrics with:
https://github.com/Netflix/servo/tree/master/servo-tomcat
=> add mapping config for tomcat jmx

spectator-agent/src/main/resources/cassandra.conf
Updates the mapping for the BloomFilterFalsePositives
to consider it a monotonically increasing counter.
=> bloom filter false positives is a counter

build.gradle
This will hopefully fix #329. It isn't clear what the
relevant change is, but running locally it seems like
this will clear up the issue.
=> use nebula 3.5.1

spectator-web-spring/src/main/java/com/netflix/spectator/controllers/model/ApplicationRegistry.java
=> Added startTime to metric response.

spectator-agent/src/main/resources/bitbucket.conf
"count" and "counter" are NOT valid atlas.dstypes
=> Update bitbucket.conf with correct atlas.dstype

spectator-api/src/main/java/com/netflix/spectator/api/Statistic.java, spectator-api/src/main/java/com/netflix/spectator/api/Utils.java, spectator-api/src/main/java/com/netflix/spectator/api/patterns/IntervalCounter.java, spectator-api/src/main/java/com/netflix/spectator/api/patterns/LongTaskTimer.java, spectator-api/src/test/java/com/netflix/spectator/api/patterns/IntervalCounterTest.java
This adds IntervalCounter: a counter that keeps track of the last time
it was incremented. This fixes #369
=> A counter that keeps track of its last update

spectator-agent/src/main/java/com/netflix/spectator/agent/Agent.java
Since the agent is normally used as a fat jar, it can
be hard to debug and figure out exactly what version is
being used. With this change a property in the typesafe
config, `netflix.spectator.agent.dependencies`, can be
used to specify a list of dependency jars that will be
exported to system properties by the agent. This allows
them to be easily queried using JMX.
=> add config option to list dependency jars

build.gradle
For details see:
https://github.com/nebula-plugins/gradle-netflixoss-project-plugin/releases/tag/v3.6.0
=> nebula 3.6.0

spectator-agent/src/main/java/com/netflix/spectator/agent/Agent.java
Agent configs can now be loaded from the file system
by using a `file:` prefix. For example to load the
tomcat config from the classpath and a `nflx.conf`
file with internal settings from the file system:
```
java -javaagent:spectator-agent.jar=file:nflx.conf,tomcat Main
```
=> fix #396, support loading configs from file system

spectator-api/src/main/java/com/netflix/spectator/api/Statistic.java, spectator-api/src/main/java/com/netflix/spectator/api/patterns/IntervalCounter.java, spectator-api/src/test/java/com/netflix/spectator/api/patterns/IntervalCounterTest.java
See discussion in Netflix/atlas#597.
=> use duration statistic for IntervalCounter

spectator-api/src/main/java/com/netflix/spectator/api/Id.java, spectator-api/src/test/java/com/netflix/spectator/api/DefaultIdTest.java
Fixes #439. See issue for details.
=> add helper for adding boolean tag values

docs/ext/jvm-gc-causes.md
=> docs: fix link to jvmti force GC

docs/ext/thread-pools.md, mkdocs.yml
Added some basic doc of the new API and reported metrics.
=> Add documentation of `ThreadPoolMonitor` for the wiki.

.travis.yml
Problems with jdk9 have been fixed, see #467 and #468.
=> reenable jdk9 PR builds

docs/intro/gauge.md
Avoid referring to deprecated methods in the docs and
describe using the new PolledMeter pattern.
=> update docs for recent gauge changes

spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SparkSink.java
This is useful for cases where jobs running on Spark need
to report custom metrics that are tagged with the common
Spark tags.
/cc @smadappa @kedargsm
=> allow spark registry to collect global metrics

spectator-api/src/main/java/com/netflix/spectator/impl/Scheduler.java, spectator-api/src/test/java/com/netflix/spectator/impl/SchedulerTest.java
If a Throwable was propagated from an executed task,
then the thread would get stopped and never replaced.
For many uses of the scheduler, we cannot control
the task to ensure they are well-behaved and do not
want a bad task to impact other tasks that may be on
the same scheduler. With this change we catch Throwable.
An additional counter is added to track the number
of uncaught exceptions that occur for the scheduler.
This will make it easy to alert if we are seeing
regular failures.
To simplify updating the stats without having to pass
around too many handles, they have been consolidated
in a stats class.
There is also a small fix to avoid having threads
restart after shutdown. Before the shutdown was
interrupting the threads and a new one would be
created to replace them. So there …
=> make Scheduler robust to uncaught Throwables

spectator-agent/build.gradle
=> add Automatic-Module-Name to agent

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/DataExpr.java, spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/DataExprTest.java
Previously, when aggegating values for a DataExpr the
query would get checked for every update. For some
use-cases the query will already have been validated
and this causes them to get checked twice adding a
significant overhead.
In addition, the group by and rollup operators now
use that for the grouped results to avoid rechecking
the query internally.
=> add flag to ignore the query when aggregating

spectator-api/src/main/java/com/netflix/spectator/api/patterns/PolledMeter.java
This adds a new method to the `PolledMeter.Builder` class that allows
the user to specify the duration at which values should be refreshed.
=> Allow the user to specify the delay for polling

build.gradle
Needed to make bintray publishing work with gradle 4.8.
=> nebula 5.1.0

buildViaTravis.sh
Hopefully this will help us understand why it is taking
some much time to publish to bintray.
/cc @chali
=> add --info to release build

build.gradle, gradle/wrapper/gradle-wrapper.properties
Hopefully this will fix the regular timeouts on the
release build.
=> update to gradle 4.8.1 and nebula 5.1.1

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
The space is covered by the default section.
=> remove unnecessary branch

build.gradle
Updates to ASM 6.2 for JDK 11 support.
=> update to spotbugs 3.1.6

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
Until support for many frequencies is implemented, restrict
the sub to those where the step matches the registry.
=> limit the lwc subs to those with matching step

spectator-web-spring/src/main/java/com/netflix/spectator/controllers/MetricsController.java, spectator-web-spring/src/test/java/com/netflix/spectator/controllers/MetricsControllerTest.java
=> fix(web-spring): Strip NaN values

spectator-api/src/main/java/com/netflix/spectator/api/patterns/PolledMeter.java, spectator-api/src/test/java/com/netflix/spectator/api/RegistryTest.java
Makes it easier to confirm the behavior we are seeing
from the user functions.
/cc @allenxwang
=> more detailed logging of polled gauges

spectator-web-spring/src/main/java/com/netflix/spectator/controllers/MetricsController.java
=> feat(web-spring): Add PercentileTimer

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpClient.java, spectator-nflx-plugin/build.gradle, spectator-reg-atlas/build.gradle, spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java, spectator-reg-stateless/build.gradle, spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessRegistry.java
Start making the usages within Spectator itself use the
common IPC helper.
=> switch clients to use common ipc helper

build.gradle
Improves compatibility with jdk11.
=> update to spotbugs 3.1.7

spectator-ext-jvm/src/main/resources/cassandra.conf
These were added into an internal config a while back. Adding
here to keep all the configs for cassandra in the same place.
=> additional jmx mappings for cassandra 3.x

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
Updates AtlasRegistry to regularly check the config
interface to see whether or not it should be enabled.
If it is mapped to a dynamic config source, then it
can be toggled at runtime.
=> allow AtlasRegistry to be dynamically enabled

docs/intro/registry.md, docs/registry/servo.md, mkdocs.yml, spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoRegistry.java
Remove references to the ServoRegistry from the docs.
=> ServoRegistry is deprecated

build.gradle, codequality/pmd.xml, spectator-api/src/main/java/com/netflix/spectator/api/Clock.java, spectator-api/src/main/java/com/netflix/spectator/api/Functions.java, spectator-api/src/main/java/com/netflix/spectator/api/Registry.java, spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileBuckets.java, spectator-api/src/main/java/com/netflix/spectator/impl/AtomicDouble.java, spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcEvent.java, spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java, spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogger.java, spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketFunction.java, spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/SpectatorModule.java, spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/DoubleCounter.java, spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoId.java, spectator-web-spring/src/main/java/com/netflix/spectator/controllers/MetricsController.java, spectator-web-spring/src/main/java/com/netflix/spectator/controllers/filter/PrototypeMeasurementFilter.java, spectator-web-spring/src/main/java/com/netflix/spectator/controllers/filter/PrototypeMeasurementFilterSpecification.java, spectator-web-spring/src/main/java/com/netflix/spectator/controllers/filter/TagMeasurementFilter.java, spectator-web-spring/src/main/java/com/netflix/spectator/controllers/model/ApplicationRegistry.java, spectator-web-spring/src/main/java/com/netflix/spectator/controllers/model/DataPoint.java, spectator-web-spring/src/main/java/com/netflix/spectator/controllers/model/MetricValues.java, spectator-web-spring/src/main/java/com/netflix/spectator/controllers/model/TaggedDataPoints.java, spectator-web-spring/src/test/java/com/netflix/spectator/controllers/filter/TagFilterTest.java, spectator-web-spring/src/test/java/com/netflix/spectator/controllers/model/TestId.java, spectator-web-spring/src/test/java/com/netflix/spectator/controllers/model/TestMeter.java
Conventient time since we just updated checkstyle.
=> update to pmd 6.9.0

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java, spectator-ext-ipcservlet/src/test/java/com/netflix/spectator/ipcservlet/IpcServletFilterTest.java, spectator-ext-ipcservlet/src/test/java/com/netflix/spectator/ipcservlet/TestUtils.java
General agreement among teams is to keep this separate. Detail
will be for the app specific usage if any.
=> do not put http status into detail

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDistributionSummary.java, spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasGauge.java
Update the javadocs for `AtlasDistributionSummary` and `AtlasGauge`
=> Some minor javadoc fixes

build.gradle, spectator-agent/build.gradle, spectator-ext-spark/build.gradle
This is in preparation for updating to nebula 7 and gradle 5.1.
=> fix gradle deprecation warnings

build.gradle
Updated plugin is needed for compatibility with gradle 5.
=> update to spotbugs 3.1.10

build.gradle, gradle/wrapper/gradle-wrapper.properties
=> update to nebula 7 and gradle 5.1

.travis.yml
=> remove sudo from Travis config

build.gradle, codequality/pmd.xml, spectator-api/src/main/java/com/netflix/spectator/api/FilteredIterator.java, spectator-api/src/main/java/com/netflix/spectator/api/Id.java, spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileBuckets.java, spectator-api/src/main/java/com/netflix/spectator/api/patterns/PolledMeter.java, spectator-api/src/main/java/com/netflix/spectator/impl/matcher/PatternUtils.java, spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoPollers.java
Transitively pulls in an old version of jcommander that
causes some warnings.
=> update to pmd 6.15.0

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java
This is a useful for being able to index a set of queries
and find the checks for a given key.
=> add base interface for simple key-value checks

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java, spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryTest.java
This will allow us to pre-match against common tags and avoid
merging them into the ids for the initial check.
=> support simplifying query based on common tags

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
This method can be used to call a consumer function for
each matching value. The primary benefit over `findMatches`
is that in many cases there is no need to allocate a list
to store the set of matches.
=> add forEachMatch method to QueryIndex

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/SubscriptionManager.java, spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/SubscriptionManagerTest.java
It wasn't corrected after being renamed. Also adds test
for missing and explicit true.
=> fix ignore check

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpRequestBuilder.java, spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
Before we limited it to a single thread to bound the
overhead. This change will allow a number of concurrent
sends to help for some apps such as the aggregation
service that publish a lot of metrics.
The implementation should allow for substituting the
Java 11 HttpClient in the future either when we drop
Java 8 support or if we decide to build as an MR jar.
=> support concurrent posts of metric batches

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
Before it was just the HTTP send. Now converting the payload
to JSON and compressing will also be done concurrently. In
many cases that takes longer than the actual send.
=> improve concurrent publish

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
Looping across the full set of measurements is a hot code
path if there are many measurements. Testing with real data
shows much better performance when doing it explicitly using
loops rather than the stream.
=> avoid using streams for hot path

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
When polling meters, split out the steps of getting all of
the measurements and updating the consolidators and evaluator.
In cases with a lot of meters the second step may take a while
and can potentially cause some meters to be sampled after
crossing a step boundary. This change should make that unlikely
and help confirm the theory is correct.
=> split measurement collection from update

build.gradle, gradle/wrapper/gradle-wrapper.properties, settings.gradle
Update gradle and nebula plugins to latest versions.
=> update to gradle 6

build.gradle
Sample build: https://travis-ci.org/Netflix/netflixoss-build-infrastructure/jobs/637103838?utm_medium=notification&utm_source=github_status
=> upgrade netlfixoss to 8.4.4: fixes multi-module publishing

README.md, docs/ext/jvm-gc.md, docs/ext/log4j1.md, docs/ext/log4j2.md, docs/ext/placeholders.md, docs/index.md, docs/intro/netflix.md, docs/registry/metrics3.md, docs/registry/servo.md
Bump version in docs to latest.
=> update version in docs

spectator-web-spring/build.gradle
=> update spring dependencies to latest versions

.travis.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
Also drop jdk13 as we only commit to supporting 2 LTS and
latest.
=> add jdk14 to build matrix

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcTagKey.java
Remove whitespace at the end of lines.
=> fix checkstyle warnings

spectator-api/src/main/java/com/netflix/spectator/api/patterns/PolledMeter.java, spectator-api/src/test/java/com/netflix/spectator/api/patterns/PolledMeterTest.java
Adds additional helpers for use with static methods to make
that use-case more clear. There is nothing prevent other
usage, but hopefully the naming makes it clear and users will
think about it first.
For existing methods, the comments have been updated to discuss
the behavior of null explicitly and use of null will now get
emitted as a warning.
Fixes #819.
=> clarify behavior for polling static methods

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java, spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasGauge.java, spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMaxGauge.java, spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/DsType.java
It was mistakenly setup to be public. Also fixes a few
lines that exceed preferred max width.
=> update dstype to have package level access

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java, spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/GzipLevelOutputStream.java, spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/StreamHelper.java, spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/StreamHelperTest.java
Ports an internal optimization that provides a significant
reduction in the amount of allocations for sending data.
=> reuse buffers for sending data to Atlas

spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/NetflixConfig.java
Makes it consistent with the latest internal mapping.
=> add shards to common tags

build.gradle
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
=> remove jcenter references

spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java
Adds a test case for Atlas registry to ensure counters
are flushed as expected.
=> add test case for flushing counters

spectator-api/src/main/java/com/netflix/spectator/api/TagList.java, spectator-api/src/test/java/com/netflix/spectator/api/ArrayTagSetTest.java, spectator-api/src/test/java/com/netflix/spectator/api/DefaultIdTest.java
Updates the TagList and thus Id to implement Comparable
with the order being the same as a comparison of the
string representations.
=> make TagList comparable

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
Refactor the condition for the stop method to avoid
all shutdown actions if the registry hasn't been
started. Before it could result in an NPE because
the thread pool for the publisher would be null.
=> fix NPE if stop without start

spectator-api/src/main/java/com/netflix/spectator/api/patterns/PolledMeter.java, spectator-api/src/test/java/com/netflix/spectator/api/patterns/PolledMeterTest.java
Adds a helper method to PolledMeter for polling a
monotonically increasing double value. One example
where this can be useful is monotonic counters for
time that are in units like milliseconds. This allows
the value to be converted to seconds to the counter
will have a base unit.
=> support polling monotonic double

spectator-reg-sidecar/src/test/java/com/netflix/spectator/sidecar/SidecarConfigTest.java
Add basic tests for defaults and extracting tags from
the environment.
=> add tests for sidecar config

spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/HotspotRuntime.java
The implementation class is package private which requires
using `setAccessible(true)` and thus needs `--add-opens`.
Refactor to use the interface class to get the method so
it is only using the public APIs and will also work with
`--add-exports`.
=> Avoid setAccessible for hotspot mbean

spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/MemoryPoolMeter.java
Change MemoryPoolMeter's measure method to return Collections.emptyList() if the MemoryPoolMXBean is not present. Additionally, size the ArrayList for the fixed number of measurements.
=> Minor optimization in MemoryPoolMeter::measure

spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
The CompositeRegistry is the implementation used for the global registry. This change reduces the locking on the methods to get a meter. This should reduce
contention if there is a lot of concurrent access
using the global registry.
Changing the set of registries should be fairly rare. It now works similar to a copy on write array list, but is done with a simple array to avoid allocations for the common case of accessing a meter with a single registry in the composite.
=> reduce locking for CompositeRegistry

spectator-api/src/main/java/com/netflix/spectator/api/NoopId.java, spectator-api/src/main/java/com/netflix/spectator/api/NoopRegistry.java
Override some default methods that allocate in NoopId and NoopRegistry.
=> Override default methods in NoopId and NoopRegistry

spectator-api/src/jmh/java/com/netflix/spectator/perf/StringReplace.java
Add a BitSet based implementation for the StringReplace benchmark. It seems to be significantly slower for cases with no replacements and a bit slower for cases with replacements.
=> update string replace benchmark for BitSet

spectator-api/src/main/java/com/netflix/spectator/api/patterns/CardinalityLimiters.java, spectator-api/src/test/java/com/netflix/spectator/api/patterns/CardinalityLimitersTest.java
We have tag values which may be IP addresses, which are very high cardinality and low value, or registered names (Eureka VIPs or DNS hostnames), which are lower cardinality and high value. This limiter allows us to apply different cardinality policies to each case.
=> Add RegisteredNameOrIp cardinality limiter

gradle/wrapper/gradle-wrapper.properties, spectator-agent/build.gradle, spectator-ext-spark/build.gradle, spectator-reg-atlas/build.gradle, spectator-web-spring/build.gradle
Shadow plugin updated to latest version to fix compatiblity issues with gradle 8.
=> update to gradle 8

.github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml, build.gradle, spectator-perf/src/test/java/com/netflix/spectator/perf/MemoryUseTest.java
Remove jdk19 and add jdk20. Disable some memory use tests based on JOL that do not complete on jdk20. Will debug that later.
=> ci: add jdk20

.github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml, build.gradle
Switches back to zulu distribution because temurin is slow to get the updated release out.
=> update CI to test on JDK 21

build.gradle, codequality/findbugs-exclude.xml, spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SparkSink.java
Update to latest version of spotbugs and gradle plugin to avoid build errors when using jdk21.
=> spotbugs 4.8.1

spectator-agent/build.gradle, spectator-ext-spark/build.gradle, spectator-reg-atlas/build.gradle, spectator-web-spring/build.gradle
Move to fork of shadow plugin that has been updated to support newer JDKs.
=> update shadow plugin to 8.1.3

dependencies.properties, spectator-ext-aws2/build.gradle
Pull in latest version with netty patch.
=> update to aws-sdk 2.30.17

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpRequestBuilder.java
If the HTTP response has a Content-Length header, use it to precisely size the read buffer in HttpRequestBuilder#readAll, which avoids unnecessary copying.
=> Avoid copying when reading HTTP response body

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/DefaultPublisher.java
Make logger field static in DefaultPublisher.
=> Make logger field static in DefaultPublisher
