spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java

The INFO level is a bit noisy for some users when
enabled by default with the SpectatorModule. Users
that want it can explicity whitelist by enabling
debug level for:
```
com.netflix.spectator.gc.GcLogger
```

change log level for gc events to debug

---

spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpLogEntry.java
spectator-nflx-plugin/src/main/java/com/netflix/spectator/http/RxHttp.java

It is convenient to have a single logger name
for setting up a logging config. The specific
source class can be added as part of the entry
later if there is a sufficient need.

use default logger

---

spectator-reg-servo/build.gradle

servo 0.8.2 is in jcenter, but didn't get published
to maven central correctly.

servo-0.8.3

---

spectator-nflx-plugin/build.gradle
spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/ChronosGcEventListener.java

Mainly to get rxnetty 0.4.5. Also found that we
were using jackson, but didn't have an explicit
dependency so archaius moving from jackson 1 to 2
caused a failure. Spectator moved to 2 and the
dependency is now explicit.

bump versions of deps

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/http/RxHttp.java

When reporting stats rxnetty is using the name as
the value for the `id` tag. If no name is specified
it is creating a unique id per client.

set the rx client name based on the config name

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/http/ClientConfig.java
spectator-nflx-plugin/src/test/java/com/netflix/spectator/http/ClientConfigTest.java

If the named property isn't set then check for the
default property. Matches behavior of internal rest
client.

default prop for client

---

spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoGauge.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoRegistry.java

Gauges were getting passed to servo by creating an
instance of NumberGauge when getMonitors is called.
NumberGauge keeps a weak reference to the number so
it will not prevent collection. Since spectator doesn't
hold onto a reference to the number passed to the
gauge it can get collected before the value is actually
read.
This change adds a simple ServoGauge monitor type that
keeps a strong reference to the value to report.

fix sporadic gaps on gauges reported to servo

---

spectator-nflx-plugin/build.gradle

Fixes bug that can lead to many spurious metrics if
unnamed clients are used.

rxnetty-0.4.6

---

spectator-ext-log4j2/src/main/java/com/netflix/spectator/log4j/SpectatorAppender.java
spectator-ext-log4j2/src/test/java/com/netflix/spectator/log4j/SpectatorAppenderTest.java

The spectator appender needs to get a registry and
the registry loading tries to log. This creates a
problem where the slf4j loggers created before log4j2
successfully configures don't work properly and we
lose the logging.
We can delay the registry hook, but this can lead to
recursive calls to the appender or a misleading logger
name if we configure the logging to not send the
spectator messages to the spectator appender.
To work around this there is now a helper that can be
called as part of the application init to add the
SpectatorAppender to the root logger. It will also
listen for configuration change events and re-add the
appender as needed.
```java
SpectatorAppender.addToRootLogger(
Spectator.registry(),
"spectator",  // Appender name
false)        // Ignore exceptions?
```
If more …

add helper for adding appender to root logger

---

spectator-reg-metrics2/src/jmh
spectator-reg-metrics3/src/jmh
spectator-reg-servo/src/jmh

The jgit version used with the cloudbees released job
is marking the workspace as dirty due to the symlinks.
For now just removing them and we'll revisit later.

remove symlinks

---

.netflixoss

This will cause our job DSL to not create and also remove the cloudbees pull request job.

Disable cloudbees pullrequest job creation/existence

---

codequality/pmd.xml
spectator-nflx/src/main/java/com/netflix/spectator/nflx/AutoPlugin.java
spectator-nflx/src/test/java/com/netflix/spectator/nflx/AutoPluginTest.java
spectator-nflx/src/test/resources/eureka-client.properties

Recent changes were causing the auto bind plugin
to fail with exceptions like:
```
2015-02-23 22:29:06,322 INFO  com.netflix.governator.guice.InternalAutoBindModule:187 [localhost-startStop-1] [bindAutoBindSingleton] Installing @AutoBindSingleton com.netflix.cag.client.AlertClientManager
java.lang.RuntimeException: com.google.inject.CreationException: Guice creation errors:
1) No implementation for com.netflix.spectator.http.ServerRegistry was bound.
while locating com.netflix.spectator.http.ServerRegistry
for parameter 0 at com.netflix.spectator.http.RxHttp.<init>(RxHttp.java:90)
while locating com.netflix.spectator.http.RxHttp
for parameter 0 at com.netflix.spectator.nflx.Plugin.<init>(Plugin.java:50)
while locating com.netflix.spectator.nflx.Plugin
for parameter 0 at …
```

fix auto bind plugin

---

spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/ByteBufferOutputStream.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/FileTDigestWriter.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/Json.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/StreamTDigestReader.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/StreamTDigestWriter.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestPlugin.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestWriter.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestPluginTest.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestWriterTest.java

Adds some test cases for TDigestWriter. Primary fix
is to reset the overflow flag when reseting the
position of the ByteBuffer. The end array was getting
dropped because the checkCapacity call would fail and
thus the json object wasn't complete.

add test cases for writer

---

spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/StepDigest.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestDistributionSummary.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestTimer.java

The digest is not thread safe and concurrent updates
and can end up with deadlock. The stack traces typically
look like:
```
java.lang.Thread.State: RUNNABLE
at com.tdunning.math.stats.AVLGroupTree.floor(AVLGroupTree.java:186)
at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:72)
at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:67)
at com.tdunning.math.stats.AbstractTDigest.add(AbstractTDigest.java:142)
at com.netflix.spectator.tdigest.TDigestTimer.record(TDigestTimer.java:46)
```
This change will drop samples if another thread has the
lock. We'll see how much we actually encounter dropped
samples in practice and whether it perturbs the value
enough to warrant a more complex solution.

prevent concurrent updates of the digest

---

spectator-ext-spark/build.gradle

Dependencies were specified incorrectly and the jar
was empty.

fix shadow jar config

---

gradle.properties
spectator-nflx-plugin/build.gradle
spectator-reg-tdigest/build.gradle

Upgrade to latest rc and update spectator-nflx-plugin
dependency so it is on the more stable 0.6.6 version.
The 2.x version will only get used for the experimental
tdigest registry right now.

archaius-2.0.0-rc.8

---

spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketFunctions.java
spectator-ext-sandbox/src/test/java/com/netflix/spectator/sandbox/BucketFunctionsTest.java

For some values, e.g., `latency(3, TimeUnit.SECONDS)`, the
unit was wrong so we would get labels 0s, 1s, and 3s. The
values should have been 0375ms, 0750ms, 1500ms, and 3000ms.
This change fixes those ranges and adds a test case to
ensure we are getting the proper number of buckets across
the default formatters.

fix bucket labels

---

gradle.properties

rc.9 changed quite a few of the APIs. In particular
the `AppConfig` class was removed. Spectator is only
using archaius2 for the T-Digest registry and no
code changes were needed.

archaius-2.0.0-rc.9

---

spectator-api/src/main/java/com/netflix/spectator/api/Spectator.java
spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SparkSink.java
spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SpectatorReporter.java

In some cases we are seeing:
```
Thread.currentThread().getContextClassLoader() == null
```
For now this workaround will use the classloader of
the local class. In some quick tests this works and
unblocks the teams seeing this problem. We probably
need to find a better solution longer term after we
understand why the context class loader is null.

work-around for null context class loader

---

spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SparkValueFunction.java
spectator-ext-spark/src/main/resources/reference.conf
spectator-ext-spark/src/test/java/com/netflix/spectator/spark/SparkNameFunctionTest.java
spectator-ext-spark/src/test/java/com/netflix/spectator/spark/SparkValueFunctionTest.java

Breaks out the driver name into a separate tag and
adds a mapping for the streaming source.

allow drill-down by driver name

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/SpectatorModule.java

Move ExtendedRegistry and Registry bindings into @Provides methods to avoid triggering static initialization of these classes from within configure().

Avoid static initialization in configure()

---

spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/StepDigest.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestConfig.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestDistributionSummary.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestMeter.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestModule.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestPlugin.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestRegistry.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestTimer.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestPluginTest.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestTimerTest.java

Before the TDigestRegistry would get included via
the service loader as part of the composite. While
convenient for testing that causes everything to
use the digest timers which is potentially expensive
on the client and server.
With this change the expectation is that for use
cases that need it the TDigestRegistry will be
injected directly. The old behavior can be simulated
by mapping the main Registry binding to TDigestRegistry.

switch to wrap the main registry

---

spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestConfig.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestModule.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestPlugin.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestRegistry.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestPluginTest.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestTimerTest.java

At some point the archaius2 logic changed to require
this and with the latest RC's we get a NPE:
```
Caused by: java.lang.NullPointerException
at com.netflix.archaius.ProxyFactory$1.invoke(ProxyFactory.java:87) ~[archaius2-core-2.0.0-rc.18.jar:2.0.0-rc.18]
at com.netflix.spectator.tdigest.$Proxy61.endpoint(Unknown Source) ~[?:0.27.0-SNAPSHOT]
at com.netflix.spectator.tdigest.TDigestModule.providesWriter(TDigestModule.java:46) ~[spectator-reg-tdigest-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
```

rename accessors to getXXX

---

gradle.properties
spectator-ext-spark/build.gradle
spectator-reg-tdigest/build.gradle
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestConfig.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestModule.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestPlugin.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestRegistry.java
spectator-reg-tdigest/src/main/resources/reference.conf
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestPluginTest.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestTimerTest.java
spectator-reg-tdigest/src/test/resources/reference.conf

Will revisit when final version with stable api is released. For now I want to avoid others getting one of the RC versions as a transitive from spectator.

remove archaius2 dependency

---

spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SidecarRegistry.java

To make debugging easier this will add the json payload
being sent to the sidecar if there is a failure to POST
with a non-200 status code.

add json payload to log for failures

---

spectator-ext-spark/src/main/resources/reference.conf
spectator-ext-spark/src/test/java/com/netflix/spectator/spark/SparkNameFunctionTest.java

In some cases there is not an explicit appid.executorid. prefix.

update pattern for executor stats

---

spectator-api/src/main/java/com/netflix/spectator/api/TagList.java
spectator-ext-spark/build.gradle
spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SidecarRegistry.java
spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SparkSink.java
spectator-ext-spark/src/main/resources/reference.conf
spectator-ext-spark/src/test/java/com/netflix/spectator/spark/SparkNameFunctionTest.java

Switch to using the SparkEnv to access the config for obtaining the common tags. Will cleanup some of the name mappings after more thorough testing. Enable the jvm and gc stats.

pull common tags from the spark env

---

spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/FileTDigestReader.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/FileTDigestWriter.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/Json.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/KinesisTDigestReader.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/KinesisTDigestWriter.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/StreamTDigestReader.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/StreamTDigestWriter.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestModule.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestWriter.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/StepDigestTest.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestPluginTest.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestWriterTest.java

Updates the Json utility class to use an injected registry
to create the ids rather than using `DefaultId` directly.
This change does break backwards compatibility of some of
the classes to pass in the registry. However, it is still
experimental and our use of those classes is only via tests
or via a guice module so it will not break common usage.
cc @pstout

use registry for creating the ids in t-digest lib

---

spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/StreamTDigestReader.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestWriterTest.java

The package private readAll helper method was only used
for a single test case. This change moves the method to a
private method in the test.

move readAll helper into test case

---

spectator-nflx-plugin/src/test/java/com/netflix/spectator/nflx/ChronosGcEventListenerTest.java

Most of these were left over from when rxhttp was
part of spectator. It has since been pulled out and
the failure tests in this case are all based on the
client configuration.

remove flakey tests

---

gradle.properties

There is some problem with versions above that and loading
the AutoBindSingleton modules.
Conflicts:
gradle.properties

revert governator to 1.7.6-rc1

---

spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/Spectator.java
spectator-api/src/test/java/com/netflix/spectator/api/SpectatorTest.java
spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java
spectator-ext-log4j2/src/main/java/com/netflix/spectator/log4j/SpectatorAppender.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketCounter.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketDistributionSummary.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketTimer.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/DoubleDistributionSummary.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpLogEntry.java
spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SparkSink.java
spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SpectatorReporter.java
spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/ChronosGcEventListener.java
spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/Plugin.java
spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/SpectatorModule.java
spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/TestModule.java
spectator-nflx-plugin/src/test/java/com/netflix/spectator/nflx/ChronosGcEventListenerTest.java
spectator-nflx-plugin/src/test/java/com/netflix/spectator/nflx/TestModuleTest.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/KinesisTDigestReader.java

The static global registry returned by `Spectator.globalRegistry()`
is now a composite. During application initialization a user can
add another registry to the composite to subscribe to activity
hitting the global registry. If nothing is added the global will
behave similar to the NoopRegistry.
The primary benefit of this change is to make it easier to work
with DI systems. The DI library can be used to setup the main
registry and if there is interest in the global data add it to
the global registry.
If the legacy behavior is needed the user can call:
```java
Spectator.initializeUsingServiceLoader();
```
That method will add the registries found using the service loader
to the global composite.
The `Spectator.registry()` call is deprecated because it still
returns the `ExtendedRegistry` …

global registry is now a composite

---

spectator-api/src/main/java/com/netflix/spectator/api/DoubleFunction.java
spectator-api/src/main/java/com/netflix/spectator/api/Functions.java
spectator-api/src/main/java/com/netflix/spectator/api/ObjectGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/Registry.java
spectator-api/src/main/java/com/netflix/spectator/api/ValueFunction.java
spectator-api/src/test/java/com/netflix/spectator/api/ExtendedRegistryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/FunctionsTest.java

Fixes the typing on `ValueFunction` so that a cast isn't
needed when using lambdas. Also deprecates `ValueFunction`
in favor of `ToDoubleFunction` that comes with the jdk.

fix types to make lambdas work better

---

spectator-api/src/main/java/com/netflix/spectator/api/DefaultId.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultIdTest.java
spectator-reg-metrics3/src/main/java/com/netflix/spectator/metrics3/MetricsRegistry.java
spectator-reg-metrics3/src/test/java/com/netflix/spectator/metrics3/MetricsRegistryTest.java

The `.` was not getting added between tags when
creating the names leading to:
```
server.requestCountagent-safaristatus-400method-GET
```
rather than the expected:
```
server.requestCount.agent-safari.status-400.method-GET
```
Also fixes a NPE if normalize is called on an Id with
an empty tag list. A test case was added for gauges
that are not currently getting mapped properly, but it
is ignored until that problem is fixed in a later commit.

fix name mapping for metrics3 registry

---

spectator-reg-tdigest/src/jmh/java/com/netflix/spectator/tdigest/Record.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/StepDigest.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestRegistry.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/StepDigestTest.java

The digest timer will drop samples if another thread already
has the lock. For artificial benchmarks of the timer
we see a high loss rate as threads that do not perform an update
will take a shorter amount of time. In practice, the timer update
is usually small compared to the code being measured.

add counters to track number of samples dropped

---

spectator-api/src/main/java/com/netflix/spectator/api/Functions.java

Avoids issues like:
```
error: type mismatch;
found   : com.netflix.spectator.api.DoubleFunction[?0] where type ?0 <: Number
required: java.util.function.ToDoubleFunction[Number]
Note: ?0 <: Number, but Java-defined trait ToDoubleFunction is invariant in type T.
You may wish to investigate a wildcard type such as `_ <: Number`. (SLS 3.2.10)
"age", new AtomicLong(System.currentTimeMillis), Functions.AGE)
```

add type info to age functions

---

settings.gradle
spectator-ext-aws/README.md
spectator-ext-aws/build.gradle
spectator-ext-aws/src/main/java/com/netflix/spectator/aws/SpectatorMetricsCollector.java
spectator-ext-aws/src/main/java/com/netflix/spectator/aws/SpectatorRequestMetricCollector.java
spectator-ext-aws/src/test/java/com/netflix/spectator/aws/SpectatorRequestMetricCollectorTest.java

Extension that allows spectator to capture data about
AWS requests being made using the SDK.
Currently this is only capturing request metrics since
it gives us the most context. For now the throughput data
from the ServiceMetricCollector is ignored.

MetricCollector for the AWS SDK

---

spectator-api/src/main/java/com/netflix/spectator/api/DefaultId.java
spectator-api/src/main/java/com/netflix/spectator/api/TagList.java
spectator-api/src/main/java/com/netflix/spectator/api/Utils.java
spectator-api/src/test/java/com/netflix/spectator/api/CompatibilityTest.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultIdTest.java
spectator-api/src/test/java/com/netflix/spectator/api/ExtendedRegistryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/TagListTest.java
spectator-reg-metrics3/src/test/java/com/netflix/spectator/metrics3/MetricsRegistryTest.java

Previous behavior was based on some tests to reduce the
cost of generating the dynamic ids in high volume paths
compared to servo. However, it led to a number of surprising
and confusing issues for users. With this change we want
to clear up the behavior for users and we can optimize
as needed in the future.
It will now sort by the tag key and remove duplicates on
update. The goal is to have more intuitive behavior for
the user so they can rely on:
1. Any ids with the same set of tags will be equal.
2. Later additions will always override if the key already
exists. So for `withTags(Iterable)` if there were
entries with duplicate keys the iteration order would
determine which one ended up getting used.

refactor TagList to be more intuitive

---

spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestTestModule.java
spectator-reg-tdigest/src/main/resources/test.conf
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestPluginTest.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestTimerTest.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TDigestWriterTest.java
spectator-reg-tdigest/src/test/java/com/netflix/spectator/tdigest/TestModuleTest.java
spectator-reg-tdigest/src/test/resources/reference.conf

Helper module to make it easier to unit test. Usage:
```java
@Test
public void testSomething() {
Injector injector = Guice.createInjector(TDigestTestModule.create());
injector.getInstance(Foo.class).doSomething();
final TDigestRegistry r = injector.getInstance(TDigestRegistry.class);
Assert.assertEquals(1, r.timer("foo").count());
}
private static class Foo {
private final Timer t;
@Inject
Foo(TDigestRegistry registry) {
t = registry.timer("foo");
}
void doSomething() {
t.record(42, TimeUnit.NANOSECONDS);
}
}
```

add module for unit tests with digest registry

---

build.gradle

Updgrade to 3.1.2 to fix maven sync.
NEBULA-283:
I recently updated an oss project to nebula 3.1.1:
https://github.com/Netflix/spectator/pull/219
The release build fails with:
https://travis-ci.org/Netflix/spectator/builds/80925469
> Could not sync 'netflixoss/maven/spectator/0.31.0' to
> Maven Central: HTTP/1.1 400 Bad Request [messages:[Invalid
> POM: /com/netflix/spectator/0.31.0/spectator-0.31.0.pom:
> Project URL missing, SCM URL missing, Developer information
> missing, Dropping existing partial staging repository.],
> status:Validation Failed]
It is getting published to jcenter, but failing to sync with
maven central. I looked at the poms for an individual jar
and don't see any major diffs:
```bash
$ curl -O 'http://jcenter.bintray.com/com/netflix/spectator/spectator-api/0.31.0/spec …
```

nebula.netflixoss 3.1.1 breaks maven sync

---

spectator-api/src/main/java/com/netflix/spectator/api/CompositeMeter.java
spectator-api/src/test/java/com/netflix/spectator/api/CompositeRegistryTest.java

If an id is missing from one of the registries it was
throwing:
```
java.lang.NullPointerException
at com.netflix.spectator.api.CompositeMeter.hasExpired(CompositeMeter.java:52)
at com.netflix.spectator.api.CompositeRegistryTest.testHasExpired(CompositeRegistryTest.java:249)
```
@pstout this should fix the NPE bug you found.

fix NPE with CompositeMeter.hasExpired

---

spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestPlugin.java

Generally we want to avoid this, but in this case it should
give us better logging in the case an Error is thrown instead
of an Exception.

catch throwable for reporting thread

---

spectator-ext-aws/src/main/java/com/netflix/spectator/aws/SpectatorMetricCollector.java

There is occasional confusion caused because the name
doesn't match the name for the base class in the AWS
SDK. Since there isn't much use yet, it is probably a
good time to rename to match and avoid more confusion
in the future.

rename to SpectatorMetricCollector

---

spectator-api/src/main/java/com/netflix/spectator/api/Config.java
spectator-api/src/main/java/com/netflix/spectator/api/RegistryMeter.java
spectator-api/src/main/java/com/netflix/spectator/api/Spectator.java
spectator-api/src/test/java/com/netflix/spectator/api/ThrowablesTest.java

This method was deprecated a while back and depotsearch
shows no internal usage remaining.

remove initializeUsingServiceLoader

---

codequality/pmd.xml
spectator-api/src/main/java/com/netflix/spectator/api/Functions.java
spectator-api/src/main/java/com/netflix/spectator/api/Registry.java
spectator-api/src/test/java/com/netflix/spectator/api/ExtendedRegistryTest.java

For test cases it is sometimes useful to check aggregated
values rather than individual counters. The most common
example is looking at the overall number of increments for
a counter with a given name. The recommendation was to use
streams, but that can get a bit cumbersome:
```java
long sum = StreamSupport.stream(registry.spliterator(), false)
.filter(m -> m instanceof Counter)        // Convert to counters
.map(m -> (Counter) m)
.filter(c -> "foo".equals(c.id().name())) // Restrict by name
.mapToLong(Counter::count)                // Get value
.reduce(0L, Long::sum)                    // Compute sum
```
This change adds some helpers to make this sort of use-case
a bit easier:
```java
long sum = registry.counters()
.filter(Functions.nameEquals("foo"))      // Restrict by name …
```

add helpers for working with Streams

---

spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileBuckets.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileTimer.java
spectator-api/src/main/java/com/netflix/spectator/impl/Preconditions.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/PercentileBucketsTest.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/PercentileDistributionSummaryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/PercentileTimerTest.java
spectator-reg-tdigest/src/main/java/com/netflix/spectator/tdigest/TDigestRegistry.java

This is an alternative to using digests to get an approximate
percentile value that works well with slicing and dicing. For
this approach we are using a fixed set of buckets that partition
the range of long values so it can be used with most sets of
non-negative long values.
The error for an estimate is usually within a few percent of
the actual percentile for the real data sets tried, but there
are some exceptions. Compared with using t-Digests it is far
more performant and usually more compact. That comes at a
cost of being less accurate and more restrictive on inputs.
Docs will be updated after the cheaper bucket options are
moved from sandbox to stable. We do need to be careful with
the overhead and encourage users to be diligent about the
usage of percentiles and the overhead …

add percentile timer and distribution summary

---

spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoCounter.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoDistributionSummary.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoTimer.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoCounterTest.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoTimerTest.java

For the servo registry delay marking the counter, timer, or
distribution summary as active until there is some activity
such as a call to increment on the counter. This is mainly
for use-cases that cache the meter instance to avoid the
lookup cost, but may not get used for quite a while.

delay reporting until there is activity

---

spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketCounter.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketFunctions.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketTimer.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/BucketCounterTest.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/BucketDistributionSummaryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/BucketFunctionsTest.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/BucketTimerTest.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketDistributionSummary.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketFunction.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketFunctions.java

These have been used for quite a while and are considered
stable now. The old classes in sandbox have been kept and
marked as deprecated to avoid breaking existing users. To
avoid drift in the implementations they now just wrap the
new versions in the api lib.
A few small changes as part of the move:
* Remove BucketFunction in favor of jdk LongFunction
* Accessor to get type for a given bucket changed to package
private

move bucket helpers from sandbox to api

---

spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileTimer.java

Timers are mapped to nanoseconds before computing the
bucket. This allows better precision without needing
to support floating point. For display it is often
preferred to use base units, like seconds. In any
case, it is useful to distinguish whether the value
was reported for a timer or a distribution summary. The
index value stored for the `percentile` key is now
prefixed with a `T` for timers and `D` for distribution
summaries.

indicate type as prefix on idx value

---

spectator-api/src/main/java/com/netflix/spectator/api/ConfigMap.java
spectator-api/src/main/java/com/netflix/spectator/api/Spectator.java
spectator-api/src/main/java/com/netflix/spectator/api/SystemConfigMap.java

Add back minimal amount of ConfigMap interface and the
implementations to avoid incompatibility with mixed versions
of api and sandbox libs in the classpath.

temporarily add back ConfigMap

---

spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketFunctions.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/BucketFunctionsTest.java
spectator-ext-sandbox/src/test/java/com/netflix/spectator/sandbox/BucketFunctionsTest.java

Update BucketFunctions so it provides helpers for working with
quantities other than time. The most commonly requested has been
bytes which will automatically generate labels using powers of
1024. There is also a helper for other arbitrary quantities that
uses the decimal metric prefixes.

add bucket helpers for quantities other than time

---

scripts/update-gh-pages.sh

1. checkCompatibility target is no longer in the build
2. use ssh instead of https for git clone

fix script to update javadocs to gh-pages

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/RegistryMeter.java
spectator-api/src/main/java/com/netflix/spectator/api/Utils.java
spectator-api/src/main/java/com/netflix/spectator/impl/AtomicDouble.java
spectator-api/src/main/java/com/netflix/spectator/impl/Config.java
spectator-api/src/main/java/com/netflix/spectator/impl/Preconditions.java
spectator-api/src/main/java/com/netflix/spectator/impl/StepDouble.java
spectator-api/src/main/java/com/netflix/spectator/impl/StepLong.java
spectator-api/src/main/java/com/netflix/spectator/impl/Throwables.java
spectator-api/src/main/java/com/netflix/spectator/impl/package-info.java
spectator-api/src/test/java/com/netflix/spectator/impl/ThrowablesTest.java

In some cases it would be useful in other spectator sub-projects
to keep the behavior consistent (for example #269). Also adds
comments to make sure it is clear these should not be used
outside of spectator itself.

move Throwables to impl package

---

spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/DoubleDistributionSummary.java
spectator-ext-sandbox/src/test/java/com/netflix/spectator/sandbox/DoubleDistributionSummaryTest.java

Update DoubleDistributionSummary in sandbox to expire
if there is no activity for 15m. This is a minimal
change to fix the current problem, expiration behavior
should probably get specified as part of the configuration
interface longer term.
/cc @dmuino

DoubleDistributionSummary should expire

---

spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketFunctions.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/BucketFunctionsTest.java

If a zero value is recorded it will now go to the smallest
bucket rather than be counted as negative.

fix #276, zero values counted as negative

---

spectator-ext-aws/build.gradle
spectator-ext-aws/src/main/java/com/netflix/spectator/aws/SpectatorRequestMetricCollector.java
spectator-ext-aws/src/test/java/com/netflix/spectator/aws/SpectatorRequestMetricCollectorTest.java

The getHost function was incorrectly getting applied
to the serviceName causing it to always be UNKNOWN.
Also updates the tests for tag value extraction to be
a bit smaller and more focused.

fix service{Name,Endpoint} for aws collector

---

spectator-ext-log4j2/src/test/java/com/netflix/spectator/log4j/SpectatorAppenderTest.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/DoubleCounter.java

Fixes two deprecation warnings:
1. Use of to string helper in guava for DoubleCounter
2. Switch to using builder for log4j event test case

fix deprecation warnings

---

spectator-api/src/jmh/java/com/netflix/spectator/perf/Ids.java
spectator-api/src/main/java/com/netflix/spectator/api/Id.java

https://github.com/Netflix/spectator/commit/f2f25c0b89b7ad75405cddb7de92bf5020b092ae made the id creation much slower than before when adding tags. Current behavior:
```
Benchmark             Mode  Cnt          Score         Error  Units
Ids.justName         thrpt   50  155882324.425 ± 4993818.679  ops/s
Ids.withTags         thrpt   50     291907.876 ±    2474.398  ops/s
```
Most time being spent sorting using the tree map:
```
43.6%  43.6% java.util.TreeMap.put
17.5%  17.5% com.netflix.spectator.api.TagList.createFromSortedTags
17.5%  17.5% java.util.TreeMap.fixAfterInsertion
8.2%   8.2% com.netflix.spectator.api.TagList$TagSorterAndDeduplicator.addTags
4.2%   4.2% java.util.TreeMap.compare
3.2%   3.2% java.util.TreeMap.getFirstEntry
2.3%   2.3% java.util.TreeMap.successor
2.1%   2.1% …
```

benchmark for performance of id creation

---

.travis.yml

For more context see:
https://docs.travis-ci.com/user/trusty-ci-environment/
Per https://github.com/Netflix/AWSObjectMapper/pull/17
it results in longer startup time, but
more stable builds overall.

try using trusty build environment

---

spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/test/java/com/netflix/spectator/api/ArrayTagSetTest.java

The offset for the input string array was getting
incremented by 1 instead of 2.

fix corrupt tag set when using varargs

---

spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcEvent.java
spectator-ext-gc/src/test/java/com/netflix/spectator/gc/GcEventTest.java

The arguments to java for setting the heap sizes using
a power of 1024. This change updates the logger to report
using a power of 1024 instead of power of 1000 to match
the jvm behavior. To try and minimize confusion labels
use KiB, MiB, and GiB to make it explicit in the output.

update gc logger to report using power of 1024

---

build.gradle

If an older version of ant is in the root classpath, then
it can cause problems for using the shadow plugin in a
sub project. Specifically the build fails with:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':spectator-ext-spark:shadowJar'.
> Could not create ZIP '/home/travis/build/Netflix/spectator/spectator-ext-spark/build/libs/spectator-ext-spark-0.41.0-SNAPSHOT-shadow.jar'
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
```
The specific failure is:
```
Caused by: groovy.lang.MissingMethodException: No signature of method: org.apache.tools.zip.ZipOutputStream.setUseZip64() is applicable for argument types: (org.apache.tools.zip.Zip64Mode) values: [Never]
at …
```

fix "Could not create ZIP" for shadowJar

---

build.gradle
spectator-ext-aws/build.gradle
spectator-ext-gc/build.gradle
spectator-ext-jvm/build.gradle
spectator-ext-log4j2/build.gradle
spectator-ext-sandbox/build.gradle
spectator-reg-metrics3/build.gradle
spectator-reg-servo/build.gradle

Gradle by default will publish these to the POM
using runtime scope. This changes dependencies
that are exposed via public APIs to get placed
in the compile scope of the POM.
Verified using:
```
$ ./gradlew spectator-reg-metrics3:generatePomFileForNebulaPublication
$ diff before spectator-reg-metrics3/build/publications/nebula/pom-default.xml
```
Diff:
```diff
18c18
<       <scope>runtime</scope>
---
>       <scope>compile</scope>
24c24
<       <scope>runtime</scope>
---
>       <scope>compile</scope>
50c50
<     <nebula_Build_Date>2016-09-01_05:33:46</nebula_Build_Date>
---
>     <nebula_Build_Date>2016-09-01_05:39:17</nebula_Build_Date>
```

use compile scope for deps in public api

---

build.gradle
codequality/findbugs-exclude.xml
codequality/pmd.xml
spectator-api/src/main/java/com/netflix/spectator/impl/Scheduler.java
spectator-api/src/test/java/com/netflix/spectator/impl/SchedulerTest.java

Adds helper class adapted from internal util for scheduling
at a fixed rate, but skipping if the execution of a task
takes longers than the frequency. The scheduled executors
in the JDK will queue the results by default. For a number
of the reporting use-cases we want fixed rate behavior, but
do not want queueing. If it falls behind, then there is a
counter we can use to detect it.

add helper for fixed rate scheduling

---

build.gradle
settings.gradle
spectator-api/src/main/java/com/netflix/spectator/impl/StepDouble.java
spectator-api/src/main/java/com/netflix/spectator/impl/StepLong.java
spectator-api/src/main/java/com/netflix/spectator/impl/StepValue.java
spectator-reg-atlas/build.gradle
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDistributionSummary.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimer.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/DsType.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/HttpRequest.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/MeasurementSerializer.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/PublishPayload.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/StepClock.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/ValidCharacters.java
spectator-reg-atlas/src/main/resources/META-INF/services/com.netflix.spectator.api.Registry
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasCounterTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasDistributionSummaryTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasTimerTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/MeasurementSerializerTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/StepClockTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/ValidCharactersTest.java

An initial version of a registry that talks to Atlas
directly rather doing it via Servo. This allows apps
that do not need all of the legacy compatibility working
to shed many dependencies and simplify the usage.
This is still considered experimental for now and may
have changes to configuration and other settings.

initial version of Atlas registry

---

settings.gradle
spectator-agent/build.gradle
spectator-agent/src/main/java/com/netflix/spectator/agent/Agent.java
spectator-agent/src/main/resources/agent.conf
spectator-agent/src/main/resources/simplelogger.properties

Adds a simple agent that can be used to start collecting
basic metrics about the JVM and GC behavior without changing
the code.
Usage:
```
java -javaagent:spectator-agent-shadow.jar=custom-config Main
```
The `custom-config` is optional and can be used to change
settings. See the `agent.conf` for available settings.

add agent that can be hooked to jvm

---

spectator-agent/build.gradle
spectator-agent/src/main/java/com/netflix/spectator/agent/Agent.java
spectator-agent/src/main/java/com/netflix/spectator/agent/JmxConfig.java
spectator-agent/src/main/java/com/netflix/spectator/agent/JmxData.java
spectator-agent/src/main/java/com/netflix/spectator/agent/JmxMeasurementConfig.java
spectator-agent/src/main/java/com/netflix/spectator/agent/JmxMeter.java
spectator-agent/src/main/java/com/netflix/spectator/agent/MappingExpr.java
spectator-agent/src/main/resources/agent.conf
spectator-agent/src/main/resources/cassandra.conf
spectator-agent/src/test/java/com/netflix/spectator/agent/Json.java
spectator-agent/src/test/java/com/netflix/spectator/agent/MappingExprTest.java

Allows the agent to be configured to query arbitrary
JMX data. Sample config is provided for Cassandra.
Test cases are a bit light right now, some of the
were generated using dumps of actual JMX data. These
need to cleaned up and sanitized first. That can
be done later without blocking other experimentation
though.

support config to query JMX data

---

spectator-agent/src/main/java/com/netflix/spectator/agent/Agent.java
spectator-agent/src/main/resources/agent.conf

Overrides the common tags method so the tags can
be specified as part of the agent configuration.

read in common tags from agent config

---

spectator-agent/src/main/java/com/netflix/spectator/agent/Agent.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

Atlas does not allow empty values. For the common tags
where the value often comes from an environment variable
empty values are sometimes used instead of not having
the environment variable. Unfortunately that breaks the
fallback logic in typesafe config. So the agent will now
filter out the empty values.

remove tags with empty values

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/HttpRequest.java

Updates the Atlas registry to explicitly set the client
name to make debugging easier.

add explicit client name to request logging

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/HttpRequest.java

This isn't super accurate, but it is a simple way to
detect if there is a large difference between the time
sources for the client and the server. In particular,
in some environments we saw NTP fail and over several
days some instances would be off by 45s or more.

add metric for rough estimate of clock skew

---

build.gradle

Updates to nebula 3.5.2 to fix jmh. For more
details see:
nebula-plugins/gradle-netflixoss-project-plugin#32
Note, 0.3.1 of the jmh plugin breaks for a
different reason on both nebular versions. So
pinning back to 0.3.0 for now.

update to nebula 3.5.2

---

build.gradle
spectator-api/src/jmh/java/com/netflix/spectator/perf/Counters.java
spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java

The `AbstractRegistry` base class uses a `ConcurrentHashMap`
for storing the meters. In some use-cases on larger instance
types like m4.16xlarge we are seeing a lot of thread
contention.
Sample profile from the JMH benchmark running on a
m4.16xlarge:
```
Result "lookup_T032":
5606833.986 ±(99.9%) 630187.261 ops/s [Average]
(min, avg, max) = (5031460.935, 5606833.986, 6415287.533), stdev = 416829.854
CI (99.9%): [4976646.724, 6237021.247] (assumes normal distribution)
Secondary result "·stack":
Stack profiler:
....[Thread state distributions]....................................................................
92.0%         BLOCKED
6.7%         RUNNABLE
1.3%         WAITING
....[Thread state: BLOCKED].........................................................................
92.0% 100.0% …
```

reduce thread contention for registry

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/DefaultGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/DefaultRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/ExtendedRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/NoopGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/NoopRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/Registry.java
spectator-api/src/main/java/com/netflix/spectator/api/RegistryConfig.java
spectator-api/src/test/java/com/netflix/spectator/api/CompatibilityTest.java
spectator-api/src/test/java/com/netflix/spectator/api/CompositeRegistryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/ExtendedRegistryTest.java
spectator-ext-sandbox/src/test/java/com/netflix/spectator/sandbox/DoubleDistributionSummaryTest.java
spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SidecarGauge.java
spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SidecarRegistry.java
spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SpectatorReporter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-metrics3/src/main/java/com/netflix/spectator/metrics3/DoubleGauge.java
spectator-reg-metrics3/src/main/java/com/netflix/spectator/metrics3/MetricsRegistry.java
spectator-reg-metrics3/src/test/java/com/netflix/spectator/metrics3/MetricsRegistryTest.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoGauge.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoRegistry.java
spectator-web-spring/src/main/java/com/netflix/spectator/controllers/model/TaggedDataPoints.java
spectator-web-spring/src/test/java/com/netflix/spectator/controllers/MetricsControllerTest.java

Changes the registry to support a `gauge(Id)` that returns
a settable gauge value. This allows the underlying type to
be activity based like the other core types. With this change
gauges are no longer a special case in terms of how they are
supported internally.
The old methods still works and will get polled via a
background thread. This has the advantage that gauges based
on user registered functions are now isolated and do not
impact regular collection.
This change should enable some additional cleanup that will
be done in subsequent PRs.

make gauges more consistent with other basic types

---

spectator-api/src/main/java/com/netflix/spectator/impl/StepDouble.java
spectator-api/src/main/java/com/netflix/spectator/impl/StepLong.java
spectator-api/src/test/java/com/netflix/spectator/impl/StepDoubleTest.java

Updates StepValue implementations to use a volatile
variable rather than AtomicLong for the previous. We
only use get and set so this is an easy way to reduce
a bit of memory overhead. Not a big difference, but it
is a trivial change and there are often many instances
of these classes.

use volatile for previous value on StepValue impl

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/DataExpr.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/Parser.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/Query.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/TagsValuePair.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/DataExprTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/QueryTest.java

Adds support for basic Atlas expressions to be used with
local filtering and aggregation. For some later work with
streaming data off this will form a minimal basis that can
be done locally on each node to reduce the volume going
out to only what is needed.
For example, assume we have a metric `requestsPerSecond`
that has dimensions for `status` with cardinality around 4,
`endpoint` with cardinality 20, and `country` with a
cardinality of about 250. So the overall number of values
is around `4 * 20 * 250 = 20,000`. If we want to stream
a query like:
```
name,requestsPerSecond,:eq,:sum
```
This will allow a local aggregation on the node to reduce
it to a single value rather than sending all 20k and doing
all reduction server side. This is similar to map and combiner
steps of a Hadoop style …

add support for Atlas query and data expressions

---

spectator-api/src/test/java/com/netflix/spectator/api/DefaultTimerTest.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/EvalPayload.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/Subscription.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/Subscriptions.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java

Still needs a lot of work, but is a minimal base version
that will send data at the same frequency as publishing
to Atlas.
For more details on the server side see:
https://github.com/Netflix/atlas/pull/459.
Future iteration needed for refactoring to honor frequency
in the subscription, performance tuning, etc.

initial version of integration with lwc api

---

docs/intro/registry.md

The doc contained an example where the Id was initialized statically. However, in the docs above, it suggests passing the Registry via constructor.
Make the example consistent with the docs about how to inject the registry.

Modify example in doc

---

spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoGauge.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoGaugeTest.java

The `ServoGauge` class was not overriding `Gauge.set`
which by default does nothing. So updates to the
gauge were getting lost. In a later PR may remove the
default impl in the base interface to avoid similar
problems with other registry implementations in the
future. The default is only there to avoid breaking
backwards compatibility due to adding a new method
to the interface.

fix gauges for servo registry

---

spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoGauge.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoRegistry.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoGaugeTest.java

The internal `ServoGauge` did not implement the
`ServoMeter` interface. This has been fixed and
test case added.
```
java.lang.ClassCastException: com.netflix.spectator.servo.ServoGauge cannot be cast to com.netflix.spectator.servo.ServoMeter
at com.netflix.spectator.servo.ServoRegistry.getMonitors(ServoRegistry.java:124) ~[spectator-reg-servo-0.46.0.jar:0.46.0]
```

fix CCE for reading gauges via ServoRegistry

---

spectator-agent/src/main/resources/cassandra.conf

For cassandra 2.x the metrics 2.2 library is used. When
extracting latencies for sending to Atlas, the `totalTime`
was being estimated by using the `Mean` value reported via
jmx. However, the `Mean` in metrics 2.2 does not come from
the snapshot used for the percentiles, but is since the timer
was created. This means that it isn't very reflective of
recent behavior. Metrics 3 changes that so that the `Mean`
is useful and is used with cassandra 3.x.
For now since we need to work with cassandra 2.x, the config
for `totalTime` uses the `50thPercentile` reported in jmx to
get the estimate.

improve totalTime estimate for cass latencies

---

spectator-agent/src/main/java/com/netflix/spectator/agent/JmxData.java
spectator-agent/src/main/java/com/netflix/spectator/agent/JmxMeasurementConfig.java
spectator-agent/src/main/java/com/netflix/spectator/agent/JmxMeter.java
spectator-agent/src/main/java/com/netflix/spectator/agent/MappingExpr.java
spectator-agent/src/main/resources/cassandra.conf
spectator-agent/src/test/java/com/netflix/spectator/agent/CassandraTest.java
spectator-agent/src/test/java/com/netflix/spectator/agent/MappingExprTest.java

When mapping in metrics from cassandra and possibly
other sources using metrics2/metrics3, the histograms
are based on a reservoir that is only rescaled during
updates. This can give a false impression of incorrect
sustained activity because the old value will keep
getting reported if no updates are received on the
underlying timer.
This change modifies the expressions to check that
the `Count` has changed since the previous time the
values were sampled. If the count has not changed,
then there was no activity so we zero out those values.
Otherwise the sampled value is returned without
modification.

zero metrics from snapshot if no change in count

---

spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpLogEntry.java

Adds overrides for setting the request URI as a
`String` instead of a `java.net.URI`. There are
two main reasons:
* The URI class is fairly strict on the format
and will fail for many URIs that are common
in practice. Using the string we can avoid
that issue.
* Some servers, e.g. akka, have their own URI
model classes and this avoids needing to
convert to string and reparse as a URI.

allow uri to be specified as string

---

mkdocs.yml

The navigation is better as some of the
sections are collapsed and it generates
the TOC for the page that is being viewed
on the right.

switch to material theme for mkdocs

---

codequality/findbugs-exclude.xml
spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/ExtendedRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/NoopRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/Registry.java
spectator-api/src/main/java/com/netflix/spectator/api/Utils.java
spectator-api/src/main/java/com/netflix/spectator/api/patterns/LongTaskTimer.java
spectator-api/src/test/java/com/netflix/spectator/api/patterns/LongTaskTimerTest.java

For long task timer (#237), interval counter (#369), and some
other uses it is necessary to maintain some state that is used
to provide values for the core types. The lifecycle of the
state should typically be tied to the lifecycle of the registry.
For example, the long task timer needs to keep track of tasks
and it is helpful if that will work across fetches of the timer
from the registry (#237).
This change introduces a concurrent map that can be accessed
from the registry to allow these composite helper types to
manage that state, but have the lifecycle of the objects tied
to the registry. That is, it will go away when the registry
goes away unless the user is maintaining references to it
elsewhere.
`LongTaskTimer` has been refactored to use this state as an
example and moved to the …

add map for storing arbitrary state with registry

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDistributionSummary.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimer.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasDistributionSummaryTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasTimerTest.java

The Atlas registry was only incrementing the timer and
distribution summary objects if the recorded amount was
positive. If the amount was zero or negative it was
ignored.
Negative latency values are sometimes seen due to clock
adjustments on a machine. Also really quick events that
call `System.currentTimeMillis` for getting the time can
get a latency of 0. These should be reflected in the count
statistic for the timer or else it causes confusion
because the number of events will not match what the user
expects.
With this change negative and 0 values will update the
count, but not other statistics.

always increment count for recorded values

---

build.gradle
codequality/pmd.xml
spectator-api/src/main/java/com/netflix/spectator/api/FilteredIterator.java
spectator-api/src/main/java/com/netflix/spectator/api/RegistryConfig.java
spectator-api/src/main/java/com/netflix/spectator/impl/Config.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasConfigTest.java

This is mostly to work around a bug in 5.3.3:
https://sourceforge.net/p/pmd/bugs/1384/
This fixes the following errors in build logs that started
showing up after #378:
```
Exception applying rule ConsecutiveLiteralAppends on file
spectator/spectator-api/src/main/java/com/netflix/spectator/impl/AsciiSet.java,
continuing with next rule
java.lang.NullPointerException
```

update pmd to 5.5.4

---

spectator-api/src/main/java/com/netflix/spectator/api/Registry.java
spectator-api/src/test/java/com/netflix/spectator/api/RegistryTest.java

Continues trend started in #353 to make activity based
gauges more consistent with other core types.

fix #313, add method to get stream of gauges

---

spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
spectator-api/src/test/java/com/netflix/spectator/api/CompositeRegistryTest.java

The composite registry now preserves the core types
when using `get` as well as the stream methods. It
was broken before because `get` was just wrapping it
as a `CompositeMeter`. With this change `get` will now
inspect the type from the sub-registries and use the
type of the first one it finds.

fix #312, preserve core types with Composite

---

docs/ext/jvm-gc-causes.md
docs/ext/jvm-gc.md
spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java

Move the concurrent phases of CMS out of `jvm.gc.pause`
and to a new timer `jvm.gc.concurrentPhaseTime`. This
makes it easier to use the pause time to only see the
stop the world pauses, and also makes the behavior match
the description in the docs.
Fixes #339.

separate out concurrent phases of CMS

---

spectator-agent/src/main/java/com/netflix/spectator/agent/JmxMeasurementConfig.java
spectator-agent/src/main/resources/agent.conf
spectator-agent/src/main/resources/cassandra.conf

Updates the agent mappings for Cassandra, specifically
testing with 2.1.x to:
1. Fix some naming issues: `s/threadpool/cql/` for `type=CQL`
and `s/filecache/readrerepair/` for `type=ReadRepair`.
2. Added mappings for `type=Client`.
3. Added a few metrics for `type=ClientRequest`.
4. Added mappings for column family histograms.
5. Added some comments about omissions.
6. Fix delta handling for monotonic counters that would not
get reported if they did not deviate from 0.

minor updates for cassandra mappings for 2.1.x

---

codequality/checkstyle.xml
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/DataExpr.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/EvalPayload.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Evaluator.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Parser.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/PublishPayload.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Subscription.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Subscriptions.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/TagsValuePair.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/DataExprTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/EvalPayloadTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/EvaluatorTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/MeasurementSerializerTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/PublishPayloadTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/SubscriptionTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/SubscriptionsTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/TagsValuePairTest.java

Moves the data expression evaluation to the impl
package for easier experimentation. Also implements
equals, hashCode, and toString for the various
helper objects to make debugging easier.

move expr eval to impl package, add tests

---

spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoGauge.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoGaugeTest.java

Updates the gauges using ServoRegistry to explicity specify
`DataSourceType.GAUGE`. The Counter, Timer, and
DistributionSummary types get it automatically from using
StepCounter and MaxGauge internally.
This fixes the reporting of gauges when local
normalization is on. By default the value would get
treated as a rate and use a weighted average which
doesn't make sense for gauges.

explicitly specifiy DataSourceType.GAUGE for servo

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Parser.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/DataExprTest.java

The same variable was being used for keeping track
of a list being created from the stack and popping
a list value off the stack to use for an operator.
The result is that operators like `:in` that take
a list would change the parse to list mode after
popping off the list argument and all subsequent
values on the stack would get added to the list until
another list terminator was found or the end of the
expression was reached.

fix #391, ClassCastException with :in

---

spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoRegistry.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoRegistryTest.java

Though not advised, this change will allow multiple
ServoRegistry instances to be created without clobbering
each other. If users are relying on this behavior their
code is broken and they should fix it to properly inject
the registry or use the global registry. However, with
this change it will prevent arbitrary broken behavior
from a library from breaking all spectator reporting
when it relies on the ServoRegistry.

fix #392, multiple ServoRegistry instances

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Subscription.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Subscriptions.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/SubscriptionTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/SubscriptionsTest.java

The set of expressions on each server instance can vary
over a small window of time. To avoid expressions coming
and going unnecessarily the client merges the results
with a small TTL (right now 15 times the refresh rate).

merge subscriptions from lwc response

---

build.gradle
spectator-api/src/jmh/java/com/netflix/spectator/perf/Counters.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeMeter.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/NoopCounter.java
spectator-api/src/main/java/com/netflix/spectator/api/NoopGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/NoopTimer.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapCounter.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapTimer.java
spectator-api/src/test/java/com/netflix/spectator/api/CompositeCounterTest.java
spectator-api/src/test/java/com/netflix/spectator/api/CompositeDistributionSummaryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/CompositeRegistryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/CompositeTimerTest.java
spectator-api/src/test/java/com/netflix/spectator/api/NoopCounterTest.java
spectator-api/src/test/java/com/netflix/spectator/api/NoopDistributionSummaryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/NoopTimerTest.java

Fixes #393. CompositeRegistry has been updated to use
a swappable counter and only update the copies when the
set of registries is changed (rare).
For cached meters, this means the only additional
overhead is the cost of the wrapper and access via a
volatile member variable. How much benefit this provides
depends a lot of the lookup cost which depends on the
overall number of meters, hashing cost of typical ids,
and concurrency. For the simple case benchmared it is
about a 3x improvement when using a composite with a
single DefaultRegistry added in:
```
Benchmark      Mode  Cnt         Score         Error  Units
before        thrpt   10  19433058.126 ± 4927554.937  ops/s
after         thrpt   10  61043422.331 ± 3085269.565  ops/s
```

avoid lookups for cached meters in global registry

---

spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java

The tag set is immutable and recomputing the hash
code each time is not necessary. This makes it much
faster to perform subsequent lookups of the same id
instance.

cache the hash code for the tag set

---

build.gradle
spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java

The binary search is typically more expensive for the
relatively short tag lists that are normally used. For
the sample append1 benchmark:
```
Ids.append1
Before      thrpt   10   19,083,890.827 ±    616,750.336  ops/s
After       thrpt   10   23,459,023.310 ±  3,610,133.557  ops/s
```

use a simple merge for adding a single tag

---

spectator-api/src/jmh/java/com/netflix/spectator/perf/Ids.java
spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/test/java/com/netflix/spectator/api/ArrayTagSetTest.java

Improves the performance of ArrayTagSet by sorting
the new tags rather than the whole array and then
doing a simple merge and dedup. Note, this change
has the most impact when the base id already has
a number of tags which in most apps we have looked
at is not the most common case. However, these changes
do not adversely impact the common case.
**Before**
```
Benchmark                         Mode  Cnt          Score         Error  Units
Ids.append1                      thrpt   10   24,956,568.448 ± 1881424.574  ops/s
Ids.append2                      thrpt   10    4,576,156.695 ±  171956.274  ops/s
Ids.append4                      thrpt   10    3,243,308.879 ±   38863.963  ops/s
Ids.append4sorted                thrpt   10    3,395,557.068 ±  137222.666  ops/s
Ids.baseline …
```

optimize addAll methods for ArrayTagSet

---

spectator-api/src/jmh/java/com/netflix/spectator/perf/Ids.java
spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/main/java/com/netflix/spectator/api/Id.java

Though there are typically better options, the variable
args `withTags(String... tags)` call is quite popular. This
change reduces the number of allocations for a number of
common calling patterns. In particular when using 4 or fewer
tags there are now overloads that will avoid the parameter
array from being created. Also if there are no existing
tags to merge with, it will dedup using the existing tags
array instead of allocating an new one can merging in.

reduce allocations for common withTags calls

---

build.gradle

Spotbugs is the successor to findbugs and should have better
support for newer jvms. Note right now it is still using the
older findbugs lib, will follow up with that later.

use spotbugs gradle plugin instead of findbugs

---

spectator-api/src/main/java/com/netflix/spectator/api/Registry.java

This has caused some confusion for both internal and
external users. See this mail thread for more context:
https://groups.google.com/forum/#!topic/netflix-atlas/hdMCAniOWOA

clarify usage of `Registry.register` method

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDistributionSummary.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMeter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimer.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasDistributionSummaryTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasGaugeTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasTimerTest.java

Updates the AtlasRegistry to expire meters that
have not seen activity within the `meterTTL` setting
of AtlasConfig.

expire inactive meters in AtlasRegistry

---

spectator-ext-placeholders/src/main/java/com/netflix/spectator/placeholders/DefaultPlaceholderFactory.java
spectator-ext-placeholders/src/main/java/com/netflix/spectator/placeholders/DefaultPlaceholderGauge.java
spectator-ext-placeholders/src/main/java/com/netflix/spectator/placeholders/PlaceholderFactory.java
spectator-ext-placeholders/src/test/java/com/netflix/spectator/placeholders/DefaultPlaceholderGaugeTest.java

Adds support for active gauges to the placeholder
extension. This makes gauges consistent with other
core types. Fixes #412.

add contextual gauge support

---

build.gradle

This version pulls in the latest spotbugs 3.1.0
release candidate instead of using the old findbugs
release.

update to spotbugs gradle plugin 1.2

---

build.gradle

The overrides to generate the html report were being
ignored because it was getting applied to the FindBugs
task instead.

fix class name for spotbugs task

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/main/java/com/netflix/spectator/api/Statistic.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasGauge.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasCounterTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasGaugeTest.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoDistributionSummary.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoRegistry.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoTimer.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoCounterTest.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoGaugeTest.java

This is for Netflix/atlas#597. Adds a statistic to
the counters and gauges to help with querying for
conceptual types when sent to Atlas.

add statistic to counters and gauges

---

settings.gradle
spectator-perf/build.gradle
spectator-perf/src/main/java/com/netflix/spectator/perf/Main.java
spectator-perf/src/main/java/com/netflix/spectator/perf/ManyTags.java
spectator-perf/src/main/java/com/netflix/spectator/perf/NameExplosion.java
spectator-perf/src/main/java/com/netflix/spectator/perf/TagKeyExplosion.java
spectator-perf/src/main/java/com/netflix/spectator/perf/TagValueExplosion.java
spectator-perf/src/test/java/com/netflix/spectator/perf/AtlasMemoryUseTest.java
spectator-perf/src/test/java/com/netflix/spectator/perf/DefaultMemoryUseTest.java
spectator-perf/src/test/java/com/netflix/spectator/perf/MemoryUseTest.java
spectator-perf/src/test/java/com/netflix/spectator/perf/NoopMemoryUseTest.java
spectator-perf/src/test/java/com/netflix/spectator/perf/ServoMemoryUseTest.java

Start for a project to add automated memory use tests
as part of the build. The main tests for registries
other than noop are ignored for now. Will follow up
after some improvements to the memory use.

initial work on memory tests for registries

---

spectator-api/src/main/java/com/netflix/spectator/impl/Config.java
spectator-nflx/src/test/java/com/netflix/spectator/nflx/AutoPluginTest.java

Checks the java version and uses a different mechanism
to invoke default methods when running under jdk9 or
higher. This fixes #425 and makes the project build and
tests run on jdk9.

fix invocation of default methods on jdk9

---

.travis.yml

Verify that the build and tests work when running
on jdk8 and jdk9.

enable jdk9 build on travis

---

.travis.yml
buildViaTravis.sh

Updates the build settings so that publication to
jcenter will only occur when using jdk8. Cross build
on jdk9 is to ensure compatibility for use on jdk9,
but jdk8 is still the primary target.

only publish from jdk8 build

---

build.gradle

This was an old helper task to get a copy of the
dependency jars in a local directory. It hasn't
been used in a long time and is causing some build
warnings.

remove copyDepsToBuild

---

README.md
docs/ext/jvm-gc.md
docs/ext/log4j1.md
docs/ext/log4j2.md
docs/ext/placeholders.md
docs/index.md
docs/intro/netflix.md
docs/registry/metrics3.md
docs/registry/servo.md

There is a bug with the publication of the log4j1
extension in 0.57.0. See #445 for details.

update docs version to 0.57.1

---

spectator-api/src/jmh/java/com/netflix/spectator/perf/Ids.java
spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java

Uses a string array internally to store the tags
so we no longer have the overhead of `BasicTag`
objects. For the sample test case it reduced the
memory use by 15.2%. The Ids benchmark shows a
reduction on some and improvement on other
benchmarks. It is currently deemed to be acceptable
for futher testing with real world data and we'll
revisit performance improvements as needed.
Before:
```
memory use exceeds limit: 26306048 > 8000000
com.netflix.spectator.api.DefaultRegistry@5b1d2887d footprint:
COUNT       AVG       SUM   DESCRIPTION
400002        24   9600088   [C
10000        96    960000   [Lcom.netflix.spectator.api.Tag;
1     65552     65552   [Ljava.util.concurrent.ConcurrentHashMap$Node;
10000        24    240000   com.netflix.spectator.api.ArrayTagSet
200000        24   4800000 …
```

reduce memory use of ArrayTagSet

---

gradle/wrapper/gradle-wrapper.properties
spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapCounter.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapTimer.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoRegistry.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoCounterTest.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoGaugeTest.java

The AbstractRegistry which is the basis for most of the
other implementations now returns swappable implementations
of the core types. This is a first step that will allow
us to perform some additional steps later.
Why is this needed? Spectator allows the user to keep a
reference to a meter so it can be quickly updated without
an additional lookup cost. The drawback is that we cannot
safely expire the meter in the registry if someone is holding
onto a reference. If the user is running with improper tag
values this can grow over time and result in a memory leak.
For apps that pull in many libraries expecting each dependency
to be responsible with metrics is a tall order. This change
will allow us to swap out the reference when expiring to
a simple implementation that will lookup again if …

AbstractRegistry now returns swappable impl

---

spectator-api/src/main/java/com/netflix/spectator/api/Gauge.java
spectator-api/src/main/java/com/netflix/spectator/api/NoopGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/ObjectGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/Registry.java

The default implementations that do nothing were added
to avoid breaking compatibility for external classes
that implementated those interfaces. However, that comes
at the cost of correctness if those methods are not
implemented. Current estimate is that it is low risk
to remove those defaults and it makes the api cleaner
and less error prone.

remove defaults for Registry.gauge

---

docs/intro/gauge.md
spectator-api/src/main/java/com/netflix/spectator/api/Registry.java
spectator-api/src/main/java/com/netflix/spectator/api/patterns/IntervalCounter.java
spectator-api/src/main/java/com/netflix/spectator/api/patterns/LongTaskTimer.java
spectator-api/src/main/java/com/netflix/spectator/impl/Scheduler.java
spectator-api/src/test/java/com/netflix/spectator/api/RegistryTest.java
spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java
spectator-reg-metrics3/src/test/java/com/netflix/spectator/metrics3/MetricsRegistryTest.java

Deprecates the passive overloads that used to be named
`gauge` and replaces them with `monitorNumber` and
`monitorValue` methods. The difference between passive
and active gauge has caused some confusion and the goal
is to make the distinction more clear while maintaining
consistent naming for the core active types.
The methods have been deprecated with a note that they
will be removed in 2.0. For now the desire is to avoid
significantly breaking backwards compatibility with
the api between now and marking as 1.0.

rename passive gauge overloads

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/Registry.java
spectator-api/src/main/java/com/netflix/spectator/api/patterns/MonotonicCounter.java
spectator-api/src/main/java/com/netflix/spectator/impl/GaugePoller.java
spectator-api/src/test/java/com/netflix/spectator/api/patterns/MonotonicCounterTest.java

Monotonic counters are fairly common, this change
adds a pattern that is used internally for regularly
polling them and updating an associated counter.

add helper for monotonic counters

---

spectator-api/src/main/java/com/netflix/spectator/api/patterns/ThreadPoolMonitor.java
spectator-api/src/test/java/com/netflix/spectator/api/patterns/ThreadPoolMonitorTest.java

Added polled monitoring of common thread pool properties.  Where
possible, Tomcat thread pool and executor metric names were used for
consistency.

Issue #419 Add thread pool monitor.

---

spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpRequestBuilder.java
spectator-ext-sandbox/src/test/java/com/netflix/spectator/sandbox/DefaultHttpClientTest.java

If an error response such as a 503 is returned, then
HttpURLConnection will return `null` for the input
stream of the body. This change now checks for that
and returns an empty array rather than failing with:
```
java.lang.NullPointerException
at com.netflix.spectator.sandbox.HttpRequestBuilder.readAll(HttpRequestBuilder.java:264)
at com.netflix.spectator.sandbox.HttpRequestBuilder.sendImpl(HttpRequestBuilder.java:242)
at com.netflix.spectator.sandbox.HttpRequestBuilder.send(HttpRequestBuilder.java:165)
at com.netflix.spectator.sandbox.DefaultHttpClientTest.unavailableEmpty(DefaultHttpClientTest.java:127)
```
The `DefaultHttpClientTest.unavailableEmpty()` test
case that was added verifies this particular change.
/cc @skandragon

fix NPE for error responses with empty body

---

dependencies.properties
spectator-ext-aws2/build.gradle

Update to jackson 2.9.1 to workaround bug in jdk9
with backticks in the manifest. For more information
see FasterXML/jackson-jr#55.

jackson 2.9.1

---

spectator-api/src/test/java/com/netflix/spectator/api/patterns/ThreadPoolMonitorTest.java

In jdk9 there is additional validation on `setCorePoolSize`
for the thread pool to verify that the new size is not greater
than the configured max.
/cc @zimmermatt

fix core pool size update test on jdk9

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/SpectatorModule.java
spectator-nflx-plugin/src/test/java/com/netflix/spectator/nflx/SpectatorModuleTest.java

This is mostly to help avoid issues with some internal
users that are using spring along with a bridge that
brings in guice bindings. If the bindings are lazy, then
apparently the bridge cannot tell the type for the binding
and use the concrete type of the class. For the registry
this means it cannot tell there is already a binding for
the Registry interface because it just sees the concrete
ServoRegistry type.

use eager singleton for Registry binding

---

spectator-api/src/main/java/com/netflix/spectator/api/Registry.java
spectator-api/src/main/java/com/netflix/spectator/api/patterns/PolledMeter.java

Fixes the method names used in two of the code samples.

fix code samples in PolledMeter javadoc

---

spectator-api/src/main/java/com/netflix/spectator/api/Registry.java

Updates the overloaded helper methods for active gauges
to be consistent with counters, timers, and distribution
summaries. The old passive `gauge` methods are now deprecated
and the user should use PolledMeter instead.

make active gauge overloads consistent with others

---

spectator-api/src/main/java/com/netflix/spectator/api/patterns/TagsBuilder.java

They were package private which means anyone outside
of that package was unable to use the builder methods.

fix visibility for methods on TagsBuilder

---

spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultIdTest.java

There was a bug in ArrayTagSet.dedup where if the source
list had multiple entries that are not duplicates, then
it would overwrite the value of the first entry with the
key of the second. This would lead to a shifted set of
tags and the last value is null. This causes a NPE when
attempting to compute the hashCode.

fix #483, ArrayTagSet.dedup overwrites first value

---

build.gradle

This pulls in the latest 3.1.0 release candidate. Help to
verify there are not problems before the 3.1.0 release.

update spotbugs plugin to 1.5

---

gradle/wrapper/gradle-wrapper.properties

Travis updated to java 9.0.1 which is causing build failures
with older versions of gradle:
```
Could not determine java version from '9.0.1'.
```

update to gradle 4.2.1

---

spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpRequestBuilder.java
spectator-ext-sandbox/src/test/java/com/netflix/spectator/sandbox/HttpRequestBuilderTest.java

Updates the simple client to allow configuring the
hostname verification and SSL socket factory that are
used.

allow ssl settings to be configured

---

spectator-api/src/main/java/com/netflix/spectator/impl/Config.java
spectator-api/src/test/java/com/netflix/spectator/impl/ConfigTest.java

Before if a configuration interface used a default method
that takes parameters, then it would fail because the paramter
type list was not being passed to the lookup.

fix #490, cannot invoke default methods with args

---

spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpLogEntry.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpRequestBuilder.java
spectator-ext-sandbox/src/test/java/com/netflix/spectator/sandbox/HttpLogEntryTest.java

Improves the error message on HttpLogEntry to indicate
the method was not set instead of failing later when
attempting to add a null tag value to the id.
Also updates the HttpRequestBuilder to fill in the default
value for the method so it will not be null if the user
does not call `withMethod` explicitly.
/cc @copperlight

improve error message if method is not set

---

spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoGauge.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoGaugeTest.java

Before it was incorrectly returning null instead of
a set of measurements.

fix NPE for ServoGauge.measure()

---

spectator-api/src/main/java/com/netflix/spectator/api/NoopRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/Utils.java
spectator-api/src/test/java/com/netflix/spectator/api/patterns/LongTaskTimerTest.java

Fixes #503. This change overrides the propagate methods
from Registry to always ensure that they are indeed noops.
Before they would follow the `spectator.api.propagateWarnings`
flag and could result in exceptions due to type errors since
there is only one Id for the noop registry.

override propagate in NoopRegistry

---

spectator-ext-spark/src/main/resources/reference.conf
spectator-ext-spark/src/test/java/com/netflix/spectator/spark/SparkNameFunctionTest.java

Updated the patterns to capture driver and executor emitted metrics.
Compatible with Spark 2.0 / Spark 2.1 
No longer compatible Spark 1.6 and older.

Updated regex patterns to capture Spark 2.0 / Spark 2.1 metrics

---

spectator-nflx/src/main/java/com/netflix/spectator/nflx/governator/AutoPlugin.java

The package name for the module annotated to be an
auto-bind singleton has been moved so it does not
conflict with `spectator-nflx-plugin`. This module
was changed for two reasons:
1. It is deprecated and if we have failures for users
we would prefer it be on this library so we can
move users off.
2. This class is only loaded via classpath scanning
so it shouldn't break anything.
Note, the test case has been left in the old package
because it needs package private access to the Plugin
class. Since this is internal to the code base we'll
revisit if it becomes a problem later. External users
will not be impacted.

fix #501, change package for spectator-nflx

---

spectator-api/src/main/java/com/netflix/spectator/impl/AsciiSet.java

The AsciiSet optimization to reuse the character array
will not only be used on jdk8. For jdk9 and later it
loses its benefit anyway because the string representation
changed to `byte[]` instead of `char[]`.

fix #507, illegal reflective access on jdk9

---

spectator-api/build.gradle
spectator-ext-aws/build.gradle
spectator-ext-aws2/build.gradle
spectator-ext-gc/build.gradle
spectator-ext-jvm/build.gradle
spectator-ext-log4j1/build.gradle
spectator-ext-log4j2/build.gradle
spectator-ext-placeholders/build.gradle
spectator-ext-sandbox/build.gradle
spectator-ext-spark/build.gradle
spectator-nflx-plugin/build.gradle
spectator-nflx/build.gradle
spectator-perf/build.gradle
spectator-reg-atlas/build.gradle
spectator-reg-metrics3/build.gradle
spectator-reg-servo/build.gradle
spectator-web-spring/build.gradle

Should help avoid compatibility problems in the future
if users try to pull these in before we support a proper
`module-info.java`. For more details see:
http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

add Automatic-Module-Name to manifest

---

docs/ext/jvm-gc.md

We'll have to wait for a fix in the jdk, so for now update
the docs to warn users.

update gc docs to indicate jdk9 regression

---

spectator-nflx-plugin/build.gradle
spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/SpectatorModule.java
spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/TestModule.java
spectator-nflx-plugin/src/test/java/com/netflix/spectator/nflx/SpectatorModuleTest.java
spectator-nflx-plugin/src/test/java/com/netflix/spectator/nflx/TestModuleTest.java

This is to work-around a problem where libraries explicitly
install `SpectatorModule` instead of deferring that to the
application. By making it an optional binding other users
can still install `TestModule` for the purposes of testing
without getting duplicate binding errors.

use optional binding for Registry in nflx-plugin

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/SpectatorModule.java
spectator-nflx-plugin/src/test/java/com/netflix/spectator/nflx/SpectatorModuleTest.java

If set as eager it will force the default to be created
even if it is overridden.
/cc @elandau

avoid eager singleton for optional binding

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDoubleCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMaxGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/DoubleCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/MaxGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/NoopDoubleCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/NoopMaxGauge.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasDoubleCounterTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasMaxGaugeTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java

This is an experimental addition to support creating a
prototype for #432. These types are used internally to
the implementations of Timer and DistributionSummary.
This should allow us to have a separate registry
implementation that forwards the base parts to a remote
AtlasRegistry implementation.

atlas: add DoubleCounter and MaxGauge types

---

spectator-ext-jvm/src/main/resources/tomcat.conf

These aren't documented particularly well in the Tomcat
docs, but are fairly easy to follow by looking at the
connection pool [source].
[source]: https://github.com/apache/tomcat/blob/trunk/modules/jdbc-pool/src/main/java/org/apache/tomcat/jdbc/pool/ConnectionPool.java

add JMX mappings for Tomcat JDBC connection pools

---

spectator-api/src/test/java/com/netflix/spectator/api/SpectatorTest.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoCounter.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoGauge.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoRegistry.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoRegistryTest.java

Before the servo registry would return instances of ServoId
for Counter and Gauge types that would have additional tagging
and fail to match the id for the meter in the base registry
map. This would lead to null values when using the iterator
with a composite registry.
Fixes #530.

ensure ids for servo meters are consistent

---

spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpRequestBuilder.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpUtils.java
spectator-ext-sandbox/src/test/java/com/netflix/spectator/sandbox/HttpUtilsTest.java

This should allow us to specify a faster compression level to
regain some CPU cycles, or a more aggressive one if reducing the size
of the payload is the goal.

Helper method to specify the gzip compression level

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/Counter.java
spectator-api/src/main/java/com/netflix/spectator/api/DistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapCounter.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapTimer.java
spectator-api/src/main/java/com/netflix/spectator/api/Timer.java
spectator-api/src/main/java/com/netflix/spectator/impl/SwapMeter.java
spectator-api/src/test/java/com/netflix/spectator/api/ExpiringRegistry.java
spectator-api/src/test/java/com/netflix/spectator/api/RegistryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/SwapMeterTest.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/SwapDoubleCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/SwapMaxGauge.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasSwapMeterTest.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoRegistry.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoRegistryTest.java

Originally the contract for the registry was that
the meters like counter would track the state since
the meter was created. This means that meters must
stick around for the life of the process.
With some registries, e.g., AtlasRegistry, we already
removed this retriction and limited it to the count
for the last completed interval. Given we have been
running in this mode a while with no issues, we are
changing the contract to officially give the registry
implementation the choice of reset frequency. Along
with this the AbstractRegistry now has a method that
can be used to fully remove any expired meters. This
avoids a memory leak over time if the user has a bug
and the distinct meter set grows over time.

add support for removing expired meters

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/MeasurementSerializer.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/MeasurementSerializerTest.java

For Atlas the name will be filled in by the name
on the id. If the user used this key, then ignore
it when sending to Atlas. Otherwise it could overwrite
the name on the id depending on how the json map
is consumed.
In a separate PR we'll add some validation logging
so the user can be aware if they are doing something
wrong.

ignore "name" when used as a tag key

---

spectator-api/src/main/java/com/netflix/spectator/api/Timer.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultTimerTest.java

Updates the Timer interface to support recording a
`java.time.Duration`. A lot of newer code uses the
java.time types and it is less error prone than
having to keep track of the unit.

add helper for recording java.time.Duration

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcMetric.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcMetricTest.java

Adds a helper function that can be used to perform basic
validation of the IPC metrics as part of a unit test. To
use it run the test with a registry and then call:
```java
IpcMetric.validate(registry);
```
/cc @kerumai

add helper to validate ipc metrics

---

spectator-api/src/main/java/com/netflix/spectator/api/SwapTimer.java
spectator-api/src/test/java/com/netflix/spectator/api/ExpiringRegistry.java
spectator-api/src/test/java/com/netflix/spectator/api/RegistryTest.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMeter.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoCounter.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoDistributionSummary.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoGauge.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoTimer.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoCounterTest.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoGaugeTest.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoTimerTest.java

The SwapTimer implementation allows us to swap or null out
the underlying timer implementation and recreate it if the
user still had a reference somewhere and there is new
activity.
There was a bug in the record calls that took a lambda where
it would cache the underlying timer before the lambda was
called and reuse it again after. For a lambda with a longer
duration, it was quite likely the underlying timer would be
removed before this completed and the update would get dropped.
This change also modifies the initial state of the meters when
first created to not be expired. Before they were initially
expired until the first activity occurred.

fix possible missed timer updates using lambda

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/NoopCounter.java
spectator-api/src/main/java/com/netflix/spectator/api/NoopDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/NoopGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/NoopTimer.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapMaxGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapTimer.java
spectator-api/src/main/java/com/netflix/spectator/impl/SwapMeter.java
spectator-api/src/test/java/com/netflix/spectator/api/CompositeRegistryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/ExpiringRegistry.java
spectator-api/src/test/java/com/netflix/spectator/api/NoopCounterTest.java
spectator-api/src/test/java/com/netflix/spectator/api/NoopDistributionSummaryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/NoopTimerTest.java
spectator-api/src/test/java/com/netflix/spectator/api/RegistryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/SpectatorTest.java
spectator-api/src/test/java/com/netflix/spectator/api/SwapMeterTest.java
spectator-reg-servo/src/test/java/com/netflix/spectator/servo/ServoRegistryTest.java

If there was a cached reference to a meter and it expired
more than once, then it would be updating a dangling meter
that is no longer connected to the registry.
The first expiration would work because the SwapMeter in
the registry and the SwapMeter referenced by the user are
the same. After that, the SwapMeter in the registry is
different and so it would not null out the value for the
cached copy and force a new lookup. This has been simplified
to just check for expiration of the underlying meter and
perform a lookup if expired.

fix secondary expiration of cached meter

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
spectator-ext-ipc/build.gradle
spectator-ext-ipc/src/jmh/java/com/netflix/spectator/ipc/ServerGroupParsing.java
spectator-ext-ipc/src/jmh/java/com/netflix/spectator/ipc/StringServerGroup.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/ServerGroup.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/ServerGroupTest.java

For some of the IPC fields we may need to fill them in
using data passed via headers. To reduce the number of
headers the plan is to just send the server group and
rely on the [naming conventions] to extract the app and
cluster. Frigga is not used for the parsing as this
could be used in a hot path and it is rather inefficient.
Comparing throughput of this approach (spectator) with
the Frigga library (frigga):
```
Benchmark      Mode  Cnt        Score       Error   Units
spectator     thrpt   10  3216353.588 ± 87966.348   ops/s
frigga        thrpt   10    11745.242 ±  2367.298   ops/s
```
Comparing allocations:
```
Benchmark      Mode  Cnt        Score       Error   Units
spectator     thrpt   10      784.171 ±     0.006    B/op
frigga        thrpt   10   124987.101 ±    11.368    B/op …
```

add utility for parsing server groups

---

spectator-agent/src/main/java/com/netflix/spectator/agent/Agent.java
spectator-agent/src/test/java/com/netflix/spectator/agent/AgentTest.java
spectator-agent/src/test/resources/a.conf
spectator-agent/src/test/resources/b.conf
spectator-agent/src/test/resources/c.conf

There was a typo in the regex so it was not properly
splitting by the comma. This fixes the regex and adds
a test case for the config loading.
/cc @ebukoski

fix loading of multiple configs for agent

---

spectator-agent/src/main/java/com/netflix/spectator/agent/Agent.java
spectator-agent/src/test/java/com/netflix/spectator/agent/AgentTest.java
spectator-agent/src/test/resources/a.conf
spectator-agent/src/test/resources/b.conf
spectator-agent/src/test/resources/c.conf
spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/JmxData.java

This delays the resolution of the user specfied agent
configs so that the mappings lists will merge properly
if multiple files are specified.
To aid in debugging the final loaded config is now logged
and the jmx query results and types can be enabled at the
TRACE level.
/cc @ebukoski

delay resolving agent configs

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcAttemptFinal.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcAttemptFinalTest.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcMetricTest.java

Internal users suggested this would be useful for
consistency. Since it was basically a boolean type
we left it out before.
/cc @kerumai

add attempt final enum

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcTagKey.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcMetricTest.java

This makes a commonly used pattern for some of the internal
integrations cleaner.

add helper to create tag for ipc key

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcProtocol.java

The values used for HTTP requests should always and are
fairly standard.

add enum for standard protocols

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcErrorGroup.java

Updates the IpcErrorGroup to have general categories for
client and server errors.

add client/server error categories to group

---

spectator-api/src/main/java/com/netflix/spectator/impl/AsciiSet.java
spectator-api/src/main/java/com/netflix/spectator/impl/Config.java

Fixes #544, now spectator-api only depends on the `java.base`
module. If the property is not set, then it will assume java8.

use system property to check the java version

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/NetflixHeader.java

These are used to pass context between the client and
the server and get consistent tagging for the IPC metrics.
/cc @kerumai @twicksell

add constants for Netflix headers

---

.travis.yml
build.gradle

JDK11 is expected to be the next long term stable release.
Switch the build to use that version to start verifying with
the early access versions.

update CI to build on jdk10

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

This was requested by a user in #537. The scope has been
limited as in most cases we do not want users interacting
with this method directly.
/cc @krutsko

make removeExpiredMeters public for AtlasRegistry

---

spectator-ext-ipc/src/jmh/java/com/netflix/spectator/ipc/SeqServerGroup.java
spectator-ext-ipc/src/jmh/java/com/netflix/spectator/ipc/ServerGroupParsing.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/ServerGroup.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/ServerGroupTest.java

Since the primary use is extracting values for tags and
that requires a String, the version that returns a
CharSequence is a bit cumbersome. Also the performance
benefit goes away since a new string instance will have
to get created for using as a tag value anyway.

use String variant for ServerGroup helper

---

spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/JmxData.java
spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/JmxMeasurementConfig.java

This adds support for composite values to JMX mappings. It creates keys
of the form: `name.sub-key` populated with the extracted values.
For example for type=MemoryPool, Usage is a composite:
` [java.lang:type=MemoryPool,name=Code Cache][Usage] =
javax.management.openmbean.CompositeDataSupport(compositeType=javax.management.openmbean.CompositeType(name=java.lang.management.MemoryUsage,items=((itemName=committed,itemType=javax.management.openmbean.SimpleType(name=java.lang.Long)),(itemName=init,itemType=javax.management.openmbean.SimpleType(name=java.lang.Long)),(itemName=max,itemType=javax.management.openmbean.SimpleType(name=java.lang.Long)),(itemName=used,itemType=javax.management.openmbean.SimpleType(name=java.lang.Long)))),contents={committed=29556736, init=2555904, max=251658240, …

Add support for CompositeData values to JMX

---

.travis.yml
gradle/wrapper/gradle-wrapper.properties

There is a release publishing issue with nebula, the
gradle bintray plugin, and gradle 4.8. Will update
these again once that is resolved.

move back to gradle 4.7 / jdk9

---

spectator-reg-metrics3/src/main/java/com/netflix/spectator/metrics3/MetricsTimer.java

The totalTime is always zero when the registry is backed by metrics3.

Fix: don't leave totalTime at zero when using a metrics3 registry

---

spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/MappingExpr.java
spectator-ext-jvm/src/test/java/com/netflix/spectator/jvm/MappingExprTest.java

The default is to decapitalize to match the normal
naming conventions for Atlas. In some cases it is
useful to have the raw value substituted, for example,
JVM memory pool names. This can now be done by using
a placeholder with a `raw:` prefix.

support raw substitution for jmx mappings

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcTagKey.java

Having insight into the servers' port is useful for services that listen on multiple ports, particularly if different functionality/configuration on different ports. And as it's low cardinality, it seems low overhead to include this.

Add optional ipc.server.port tag

---

build.gradle

This updates to gradle-bintray-plugin 1.8.4 which should
fix some of the release build issues that we were seeing
on gradle 4.8.

try nebula plugin 5.1.1-rc.2

---

codequality/findbugs-exclude.xml
spectator-ext-ipc/build.gradle
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogger.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/NetflixHeader.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpClient.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpRequestBuilder.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpResponse.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpUtils.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/HttpRequestBuilderTest.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/HttpResponseTest.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/HttpUtilsTest.java

Initial version of some basic helpers to aid in using the
common IPC metrics in a consistent manner. As an example
of using the a simple HTTP client based on the java
HttpURLConnection is instrumented. This will replace
the version from the sandbox lib.

IpcLogger to help with using IPC metrics

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogger.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java

Switch to using compute if absent and add test cases.

fix lookup of inflight metric count

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Parser.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/DataExprTest.java

Updates the Atlas expression parsing to match the behavior
of the backend. Before it would fail with nested lists and
throw a NullPointerException:
```
Caused by: java.lang.NullPointerException
at java.util.ArrayDeque.addFirst(ArrayDeque.java:228)
at java.util.ArrayDeque.push(ArrayDeque.java:503)
at com.netflix.spectator.atlas.impl.Parser.parse(Parser.java:83)
at com.netflix.spectator.atlas.impl.Parser.parseDataExpr(Parser.java:42)
at com.netflix.spectator.atlas.impl.Subscription.setExpression(Subscription.java:66)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndS …
```

fix interpretation of nested parens for Atlas expr

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcMetric.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java

The percentile approximations are counters, the validation
was rejecting these as having an invalid type.

fix ipc validation for percentile counters

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcMetric.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcMetricTest.java

Update validation to check that successful requests will
not get an error reason. The logger was setting to successful
http status codes.

 no error reason for successful requests

---

settings.gradle
spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/main/java/com/netflix/spectator/api/Utils.java
spectator-reg-stateless/build.gradle
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/JsonUtils.java
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessConfig.java
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessCounter.java
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessDistributionSummary.java
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessGauge.java
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessMaxGauge.java
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessMeter.java
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessRegistry.java
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessTimer.java
spectator-reg-stateless/src/main/resources/META-INF/services/com.netflix.spectator.api.Registry
spectator-reg-stateless/src/test/java/com/netflix/spectator/stateless/JsonUtilsTest.java
spectator-reg-stateless/src/test/java/com/netflix/spectator/stateless/StatelessConfigTest.java
spectator-reg-stateless/src/test/java/com/netflix/spectator/stateless/StatelessRegistryTest.java

Keeps track of basic delta and sends to an [aggregation service]
that can maintain the state for the step interval. This is the
similar to the implementation being used with the the thin
clients for various languages.
[aggregation service]: https://github.com/Netflix-Skunkworks/iep-apps/tree/master/atlas-aggregator
Fixes #432.

add stateless registry for FaaS use-cases

---

spectator-ext-ipcservlet/build.gradle
spectator-ext-ipcservlet/src/main/java/com/netflix/spectator/ipcservlet/IpcServletFilter.java

The `init` and `destroy` methods have default implementations
on 4.x, for older versions they do not.

fix AbstractMethodError on older servlet-api

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMaxGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java

Some use-cases expect to access the clock from the registry
and it is confusing to have it be step aligned. This is only
really needed for the measurements read from gauges.

limit use of step clock to gauges

---

spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/JmxData.java
spectator-ext-jvm/src/test/java/com/netflix/spectator/jvm/JmxBean.java
spectator-ext-jvm/src/test/java/com/netflix/spectator/jvm/JmxDataTest.java

There was a report that the `id` for Tomcat thread pool
metrics changed when moving to a newer client version
that used `spectator-ext-jvm` instead of `servo-tomcat`.
The reason is that the key `name` is both in the ObjectName
and the attributes. The attributes were overwriting the
ObjectName property. For now we are just giving precedence
to the ObjectName properties. Longer term we can look at a
better way to distinguish between them so the user can
specify.
/cc @zarfide

give ObjectName props priority over attributes

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/ServerGroup.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/ServerGroupTest.java

Turns out avoiding Frigga's `Names` class will still be useful, so thought I'd just expose the sequence here instead.

Expose sequence on ServerGroup

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

This was inadvertently changed in #600. The timestamp sent
to the eval payload of lwc should always be step aligned.

use step clock for lwc eval payload

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/ServerGroup.java

This comment about copies is no longer true since we
switched to using String instead of CharSequence in #569.

remove incorrect comment

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/SpectatorModule.java

Use the provider to ensure that the registry will be started
and stopped as expected.

connect registry lifecycle to injector

---

spectator-nflx-plugin/build.gradle

It only needs `servo-core`, the Servo registry is no longer
used internally at Netflix.

cleanup nflx plugin dependency for Servo

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpRequestBuilder.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/SubscriptionManager.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/SubscriptionManagerTest.java

Take advantage of the ETag header and only update
the expression list if they have changed.

use ETag for refreshing lwc subscriptions

---

buildViaTravis.sh

It isn't adding much value and makes it much harder to
find the useful information in the travis build logs.

remove --info from gradle release builds

---

.travis.yml

Now that there is an updated spotbugs release we should
be able to build on jdk11. Dropping jdk10 as it will no
longer be supported soon.

enable CI build for jdk11

---

spectator-api/src/main/java/com/netflix/spectator/api/Id.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultIdTest.java

Leveraging a canonical String representation of an enum. Enum's given their nature, are a fixed cardinality and typical low-cardinality, which makes it safe to use as a tag.

Utility function to accept Enum as tag value, using Enum::name()

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/NetflixConfig.java
spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/SpectatorModule.java

Replicate the behavior used internally at Netflix by attempting to load
account and environment specific properties, and populating common-tags
so subscriptions can be properly evaluated.

Ensure the AtlasRegistry uses a proper config

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/EvalPayload.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/EvalPayloadTest.java

Updates the eval payload to include passing diagnostic
messages back to the server (Netflix/atlas#925).

update eval payload to support messages

---

spectator-api/src/main/java/com/netflix/spectator/api/patterns/TagsBuilder.java
spectator-api/src/test/java/com/netflix/spectator/api/patterns/TagsBuilderTest.java

Keeps it consistent with the Id interface which received
a similar helper in #623. Also improves the test coverage
of TagsBuilder and fixes an issue found with the varags
string variant where only the first tag would get added.

add `withTag(String, Enum)` for TagsBuilder

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcErrorGroup.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcMetric.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcStatus.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcTagKey.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcMetricTest.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcStatusTest.java
spectator-ext-ipcservlet/src/test/java/com/netflix/spectator/ipcservlet/IpcServletFilterTest.java
spectator-ext-ipcservlet/src/test/java/com/netflix/spectator/ipcservlet/TestUtils.java

Updates the IPC metrics pattern based on recent internal
conversations. In particular, many found the errorGroup
and errorReason values to be confusing and these have been
replaced by status and statusDetail.

update IPC metrics to use status and detail

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java

Updates the Atlas registry to explicitly ignore the
measurements with a value of `NaN`. Before a gauge
that was explicitly set to `NaN` would get passed
through.

ignore NaN values when publishing

---

docs/intro/gauge.md

Fix the example of using a gauge with a `Number`

Minor fix for gauge documentation

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcTagKey.java

fix typo for `ipc.status.detail` tag key

---

docs/intro/timer.md

Make the example use the pattern, and not the deprecated `Registry`
method, plus a few minor clarifications.

Update LongTaskTimer docs

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcTagKey.java

Zuul team wants to be able to use this still so they can
have application specific details while retaining the actual
HTTP status code.

remove deprecation of `http.status`

---

build.gradle
codequality/checkstyle.xml
spectator-api/src/main/java/com/netflix/spectator/api/CompositeMeter.java
spectator-api/src/main/java/com/netflix/spectator/api/DefaultId.java
spectator-ext-aws/src/main/java/com/netflix/spectator/aws/SpectatorRequestMetricCollector.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoId.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoTag.java

Fixes incorrect flagging of javadoc on variables used inside
a lambda function (checkstyle/checkstyle#1254).

update to checkstyle 8.14

---

spectator-api/src/main/java/com/netflix/spectator/api/CompositeMeter.java
spectator-api/src/main/java/com/netflix/spectator/api/DefaultId.java
spectator-api/src/main/java/com/netflix/spectator/api/patterns/CardinalityLimiters.java
spectator-api/src/test/java/com/netflix/spectator/api/patterns/CardinalityLimitersTest.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogger.java

Updates the most frequent cardinality limiter to better
handle cases where there is a long tail with a lot of
churn. It should now detect a baseline frequency that
is higher than the frequncy of values with a lot of
churn over time. This may limit the number of values
emitted to be smaller than the limit specified by the
user.

improve churn resistance for mostFrequent limiter

---

settings.gradle
spectator-api/src/main/java/com/netflix/spectator/api/BasicTag.java
spectator-api/src/main/java/com/netflix/spectator/api/Id.java
spectator-api/src/main/java/com/netflix/spectator/api/Tag.java
spectator-reg-micrometer/build.gradle
spectator-reg-micrometer/src/main/java/com/netflix/spectator/micrometer/MicrometerClock.java
spectator-reg-micrometer/src/main/java/com/netflix/spectator/micrometer/MicrometerCounter.java
spectator-reg-micrometer/src/main/java/com/netflix/spectator/micrometer/MicrometerDistributionSummary.java
spectator-reg-micrometer/src/main/java/com/netflix/spectator/micrometer/MicrometerGauge.java
spectator-reg-micrometer/src/main/java/com/netflix/spectator/micrometer/MicrometerMeter.java
spectator-reg-micrometer/src/main/java/com/netflix/spectator/micrometer/MicrometerRegistry.java
spectator-reg-micrometer/src/main/java/com/netflix/spectator/micrometer/MicrometerTimer.java
spectator-reg-micrometer/src/main/resources/META-INF/services/com.netflix.spectator.api.Registry
spectator-reg-micrometer/src/test/java/com/netflix/spectator/micrometer/MicrometerRegistryTest.java

Wraps the Micrometer MeterRegistry interface so that code
instrumented using the Spectator API can use Micrometer
registry implementations. Micrometer API borrowed a lot
from Spectator so most of the concepts translate directly.
/cc @ewiseblatt @jkschneider

registry that delegates to Micrometer

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMaxGauge.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasMaxGaugeTest.java

Polls the step double before accessing the timestamp to ensure
that it has been rotated. Otherwise the timestamp used for the
measurement may not have been advanced and still reflect the
previous interval.

fix measured timestamp for Atlas max gauge

---

spectator-ext-aws/src/main/java/com/netflix/spectator/aws/SpectatorMetricCollector.java
spectator-ext-aws/src/main/java/com/netflix/spectator/aws/SpectatorServiceMetricCollector.java

Update the SpectatorMetricCollector to get the time it takes
to retrieve a connection from the underlying connection pool.
/cc @okigan

collect HttpClientGetConnectionTime for AWS SDK

---

docs/ext/jvm-memory-pools.md

This seems to be the only link to the old wiki.

Update link to live data size

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpRequestBuilder.java

For some use-cases it can be useful to perform some minor
adjustments to the log entry for the request.
/cc @rnz0

provide access to log entry from request builder

---

spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessRegistry.java

Helps reduce the amount of data going into the aggregator
and avoid saturating the NIC with many clients.

compress payload sent by StatelessRegistry

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessRegistry.java

It will now do a cleanup check after sending data for a
given iteration.

StatelessRegistry should remove expired meters

---

README.md

This will automatically get updated to point to latest
version of javadocs that are available in maven central.

update javadoc link to javadoc.io

---

build.gradle

IntelliJ provides code coverage inline as an option when
running tests that is more convenient.

remove jacoco from build

---

scripts/Makefile

The main use of this was for javadocs which can now be
accessed via javadoc.io (#664).

remove custom reports from mkdocs site

---

docs/reports.md
mkdocs.yml

These are no longer being generated, see #668.

remove build reports page

---

build.gradle

See if it fixes build error for publishing:
```
A problem occurred evaluating root project 'spectator'.
> Failed to apply plugin [class 'nebula.plugin.bintray.NebulaBintrayPublishingPlugin']
> Cannot get property 'release.stage' on extra properties extension as it does not exist
```

update to nebula 7.1

---

spectator-api/src/main/java/com/netflix/spectator/impl/AsciiSet.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/CharClassMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/CharSeqMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/IgnoreCaseMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/IndexOfMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/NegativeLookaheadMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/OrMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/PositiveLookaheadMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/RepeatMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/SeqMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/StartsWithMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/ZeroOrMoreMatcher.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/MatcherSerializationTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/PatternMatcherTest.java

This is needed for some Spark use-cases.

make PatternMatcher serializable

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/SubscriptionManager.java

For the main publish payload this will be JSON instead
of the binary format over the wire.
Also explicitly adds the URI to failure warning logs as
a number of the default network exceptions do not include
it. The URI and exception is available via the IPC access
logging, but that is debug level and not on by default for
most apps.

add trace logging of raw payload

---

spectator-api/src/test/java/com/netflix/spectator/api/histogram/PercentileBucketsTest.java

It was used for some debugging and shouldn't have been
committed.

remove bogus test case

---

spectator-api/src/main/java/com/netflix/spectator/api/patterns/CardinalityLimiters.java
spectator-api/src/test/java/com/netflix/spectator/api/patterns/CardinalityLimitersTest.java

This is a simple limiter that limits to a single pre-defined
value if the cardinality of the input exceeds a fixed size.
Useful for values with a fairly uniform frequency that do not
yield decent results with a most frequent limiter. Also used
as a building block for automatic-rollup policies to protect
the backends.

add rollup limiter

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogger.java

The frequencies get a bit messy for use-cases that have
many clusters / ASGs reporting at a fixed rate. There is
a larger number with roughly the same frequency. This should
be a lot easier to reason about.

use simple rollup limiter for ipc

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/DefaultRegistry.java
spectator-api/src/test/java/com/netflix/spectator/api/RegistryTest.java

The use-case is to allow for resetting the state between
test invocations when the registry instance needs to be
reused.
/cc @quidryan

add reset() method for DefaultRegistry

---

build.gradle

This will ensure the artifacts produced will still run
on JDK8 even if a newer JDK is used to build the project.

use `--release 8` when building on newer JDKs

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcStatus.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcStatusTest.java

For many historical uses at Netflix, the 503 status code
is used to indicate throttling to the client. The `IpcStatus`
helper now maps `503` to `throttled` by default. A new
method `withHttpStatusStandard` that follows the RFC more
closely.

ipc: support mapping 503 to throttled

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogger.java

This makes it easier to use for testing when the clock for
the registry is manually controlled.

IpcLogger should default to registry clock

---

build.gradle
spectator-api/src/jmh/java/com/netflix/spectator/perf/PercentileTimers.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileTimer.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/PercentileDistributionSummaryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/PercentileTimerTest.java

For percentile approximations that are dynamically looked
up based on the the id, a new instance of the composite
was being created each time. The array used for keeping
track of the counters is about 1-2K (depending on pointer
size) leading to a lot of allocations if this was done in
a hotspot in the code.
This change will cache the results as part of the registry
state. JMH benchmarks show no degradation in the overhead
to record a value and much lower allocation rate:
**Before**
```
defaultTimerGet             16.012 ±       0.001    B/op
defaultTimerReuse            0.005 ±       0.001    B/op
percentileTimerBuilder    1424.163 ±       0.021    B/op
percentileTimerGet        1376.149 ±       0.007    B/op
percentileTimerReuse         0.012 ±       0.001    B/op
```
**After**
``` …
```

reduce allocs for lookups of Percentile types

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/PercentileTimerTest.java

Ensures that patterns using the registry state to cache
wrappers implementing Meter will successfully get cleaned
up.

add test cases for percentile expirations

---

spectator-web-spring/src/main/java/com/netflix/spectator/controllers/MetricsController.java

Updates the MetricsController spring properties to be compatible with Spring Boot 2. Boot 2 enforces convergence on kebab-case configurations within code. User-land configuration will continue to resolve correctly if kept as camelCase.
This is to support Spinnaker's upgrade to Spring Boot 2.

Spring Boot 2 properties compatibility

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasConfigTest.java

Allow the tilde `~` character in the tags we send to atlas. This is
needed because internally some server groups include that character in
their names

Relax valid charset for atlas to allow tilde

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimer.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasTimerTest.java

In some rare cases we have seen enough activity within a
single interval to overflow the `long` value. Switches it
to a `double` to further reduce the probability of
overflowing the type.
The `totalTime` method is part of the public API and returns
a `long`. This cannot be changed at this time and is mostly
used for unit tests. For now it will just cast the `double`
to a `long`. We'll revisit in the future if it becomes a
problem.

use double for total on AtlasTimer

---

spectator-api/src/main/java/com/netflix/spectator/api/patterns/ThreadPoolMonitor.java
spectator-api/src/test/java/com/netflix/spectator/api/CompatibilityTest.java
spectator-api/src/test/java/com/netflix/spectator/api/patterns/ThreadPoolMonitorTest.java

Wraps the `RejectedTaskHandler` for a monitored pool to
track the number of times tasks are rejected. If the user
wants to use a custom handler, then they must set it on
the pool before calling `ThreadPoolMonitor.attach`.

add counter for number of rejected tasks

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/Plugin.java
spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/SpectatorModule.java
spectator-nflx-plugin/src/test/java/com/netflix/spectator/nflx/SpectatorModuleTest.java
spectator-reg-atlas/build.gradle
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

In some internal use-cases where this gets used with Spring
via a Guice bridge, the provider can cause problems and avoid
the detection used to prevent interference with the Spring
bindings. While the underlying problem is some bug with the
Guice bridge used in the Spring apps, this change should help
reduce the probability that our library is in the middle of it
when users hit problems.

avoid using provider for Registry binding

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/Plugin.java
spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/SpectatorModule.java
spectator-nflx-plugin/src/test/java/com/netflix/spectator/nflx/SpectatorModuleTest.java
spectator-reg-atlas/build.gradle
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

This reverts commit 90b78aea00d0837b9a9332a853dfdc62135fdfd9.
Due to a bug in governator that can cause a memory leak
(see Netflix/governator#392) we are going to revert this
change.
Note, if we do roll forward there is also an intialization
order issue because the SpectatorContext may not be set until
much later. That issue can be worked around by setting it to
the global registry when configured.

Revert "avoid using provider for Registry binding (#699)"

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/SpectatorModule.java

Before many things could get initialized prior to the
context for Servo being set. This would result in those
metrics being missing.

set spectator context for servo earlier

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java

This allows the metrics for the registry itself to be reported
separately with a different failure mode. This can be useful for
debugging or cases where the AtlasRegistry is being used as a
service and forwarding data on behalf of other apps.

configurable debug registry for AtlasRegistry

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

The string data for the tags tends to compress pretty
well and reduce the entity size quite a bit. With this
setting we can have larger batches without hitting server
side limits for the max entity size.

enable compression for Atlas publish

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/RollupPolicy.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/Rollups.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/RollupsTest.java

Adds a setting for a RollupPolicy that will get applied to
the set of measurements before sending to Atlas. This can
be used to perform automatic cardinality limiting or other
sanity checks prior to sending to the storage layer.
The policy is not applied for the streaming path so that
full data can be accessed on demand when needed.

add rollup policy for AtlasRegistry

---

spectator-agent/src/main/java/com/netflix/spectator/agent/Agent.java
spectator-agent/src/main/resources/agent.conf
spectator-agent/src/test/java/com/netflix/spectator/agent/AgentTest.java
spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/JmxMeasurementConfig.java
spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/JmxMeter.java
spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/JmxPoller.java
spectator-ext-jvm/src/test/java/com/netflix/spectator/jvm/CassandraTest.java

The agent will now check file based configs to see if they
have been modified and then reload the JMX mappings. This
allows the mappings to be updated without having to restart
the process.
Fixes #704.

agent: support reloading changed configs

---

docs/ext/ipc.md
docs/ext/jvm-gc.md

this brings the ipc metrics documentation in-line with the standard
metrics glossary format, by adding units descriptions, so that they
can be consumed reliably by an internal build process.
the jvm-gc metrics have been simplified from a list of units
depending on statistic, to base units.

update units for ipc and jvm-gc metrics

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Clears up some security warnings due to transitive dependencies
on dom4j.

update to gradle 5.4.1 and spotbugs 3.1.12

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Parser.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryTest.java

DNF is a useful simplification for indexing. It allows us to
ignore OR clauses and just have multiple simple queries combined
with AND mapped to the same value.

add helper function to convert Query to DNF

---

build.gradle
spectator-api/src/jmh/java/com/netflix/spectator/perf/IdTraversal.java
spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/main/java/com/netflix/spectator/api/DefaultId.java
spectator-api/src/main/java/com/netflix/spectator/api/Id.java
spectator-api/src/main/java/com/netflix/spectator/api/NoopId.java
spectator-api/src/main/java/com/netflix/spectator/api/TagList.java
spectator-api/src/test/java/com/netflix/spectator/api/ArrayTagSetTest.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultIdTest.java

Adds a base interface for Id that allows it to be treated
consistently as a collection of tags, i.e., name is not
special other than being the first entry. It also allows
the tag keys and values to be accessed without allocating
a Tag object.

support traversal of ids without allocations

---

build.gradle
spectator-api/build.gradle
spectator-api/src/jmh/java/com/netflix/spectator/perf/Caching.java
spectator-api/src/main/java/com/netflix/spectator/api/TagList.java
spectator-api/src/main/java/com/netflix/spectator/impl/Cache.java
spectator-api/src/main/java/com/netflix/spectator/impl/LfuCache.java
spectator-api/src/test/java/com/netflix/spectator/impl/LfuCacheTest.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

Adds a `QueryIndex` class that can be used to quickly check
and `Id` against a potentially large set of queries that are
known in advance.
This is similar to the structure in the Atlas backend, but
exploits the current structure of the Spectator `Id`. The tree
is setup to check the name first and then the tags in order.
To compensate for regex and other query types that would require
a linear scan of events a simple LFU cache is used. The scan
is only needed for the values that are not in the cache or after
the index is modified at that level.
Tests with real data shows it performs pretty well and allows us
to comfortably check ~450k distinct ids against ~50k alerting
queries in a fraction of a second.

add index for matching against a set of queries

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

Before this would cause a ClassCastException because they
were not a KeyQuery.

update QueryIndex to handle true/false

---

spectator-nflx-plugin/src/test/java/com/netflix/spectator/nflx/SpectatorModuleTest.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/SubscriptionManager.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Consolidator.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Evaluator.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Subscriptions.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/RollupsTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/ConsolidatorTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/EvaluatorTest.java

Updates the LWC integration to support subscribing to
expressions with various step sizes. The meters will
collect data with a base step size. LWC subscriptions
can use any even multiple of that. The data to publish
to Atlas storage will be generated by consolidating the
measurements collected with the base LWC step. The step
size used for publishing must be greater than or equal
and an even multiple of the base LWC step.

support multiple step sizes for LWC

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/SubscriptionManager.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/SubscriptionManagerTest.java

For cases where data going through the normal publish path
is already forwared to LWC on the backend, the client should
not send directly for those step sizes.

add setting to ignore the publish step

---

spectator-api/src/main/java/com/netflix/spectator/api/Registry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/RollupsTest.java

Adds a Registry method to get a flattened stream of
measurements rather than having to compute that from the
set of meters. This is the most common data access pattern
and the details of this get a bit more complex with the
support for variable frequencies in AtlasRegistry for LWC.
For now it uses a simple implementation, an override will
be added to AtlasRegistry in a later PR.

add Registry method to get stream of measurements

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/RollupsTest.java

The collector for the set of measurements will now get the
same step and values as publishing to Atlas storage.

update measurements() to use publish step

---

spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileDistributionSummary.java

It will now use the same caching behavior as timers. This was
overlooked when introduced in #690.
/cc @bondj

fix lookup for PercentileDistributionSummary

---

spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/main/java/com/netflix/spectator/api/Id.java
spectator-api/src/test/java/com/netflix/spectator/api/ArrayTagSetTest.java

This change special cases `ConcurrentMap` to ensure that the
code will not throw if there is a concurrent modification
while it is being added to the list. A concurrent modification
should be considered a bug in the caller, but it should not
propagate and cause a bigger problem for the app. Also it
is not possible to detect all cases, only ones that fail in
a noticeable way.
The docs for `Id` have also been updated to clarify the
expectation for the user.
Fixes #733.
/cc @elandau

avoid exceptions if map is modified concurrently

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

There are some internal use-cases that have not yet
been transitioned to directly publish via the registry
and run with Atlas publishing disabled. This is a
temporary workaround to avoid missing some updates
until those can be transitioned.

ensure meters are always polled

---

codequality/findbugs-exclude.xml
spectator-api/src/main/java/com/netflix/spectator/api/Clock.java
spectator-api/src/main/java/com/netflix/spectator/api/SystemClock.java
spectator-api/src/main/java/com/netflix/spectator/api/patterns/CardinalityLimiters.java
spectator-api/src/test/java/com/netflix/spectator/api/patterns/CardinalityLimitersTest.java

This can be useful when using in environments such as
Spark or Flink

make cardinality limiters serializable

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Consolidator.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/ConsolidatorTest.java

This makes the local behavior consistent with how
aggregation works if an automatic rollup is applied
to the data.

always use max consolidation for gauges

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

Check that the set of metrics is not empty before sending
the LWC payload.

lwc: do not send empty payloads

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

Logging for that specific metric name is not all that
useful for general cases.

remove temporary trace logging

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

For now share this setting with the existing num threads
for the scheduler. In the future this may get refactored
so need to be careful how it impacts the public api.

make size of sender pool configurable

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/RollupsTest.java

Add timers for some of the main methods used when sending
to Atlas or to LWC. Will be used for tracking if we are
unable to collect all of the data on time.

add timers for publish tasks

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/Id.java
spectator-api/src/main/java/com/netflix/spectator/api/Utils.java
spectator-api/src/test/java/com/netflix/spectator/api/RegistryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/UtilsTest.java

Though not recommended, in some cases users are implementing
the `Id` interface rather than using `registry.createId`. This
change adds some default implementations to avoid breaking
older code for changes introduced in #722. It also updates the
base registry implementation to normalize the ids to force them
to be a proper implementation created by the registry and avoid
confusing behavior.

add default implementations of new methods to Id

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/MeasurementSerializer.java

Avoids allocating the temporary Tag objects when serializing
the id for a measurement.

reduce allocations for serializing measurements

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/MeasurementSerializer.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/SubscriptionManagerTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/MeasurementSerializerTest.java

It is not used anymore at Netflix and generally having
different allowed character sets just creates confusion.

deprecate AtlasConfig.validTagValueCharacters

---

spectator-api/src/main/java/com/netflix/spectator/api/Utils.java
spectator-api/src/test/java/com/netflix/spectator/api/UtilsTest.java

Refactors Utils.getTagValue to avoid allocating the Tag
objects if the iterable is of type TagList.

avoid allocating Tag objects for getTagValue

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/OffsetClock.java

Updates the AtlasRegistry to attempt flushing the data
for the final interval when shutting down. This may still
not be successful if the backend guards against data coming
in with timestamps in the future.

flush data for final interval on shutdown

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java

Change it to be close to the start of the interval. With
smaller step sizes this gives more time to publish data
when there are a lot of metrics on an instance. It also
helps get the data to the server more quickly after an
it is complete.
The main down side we'll need to watch out for is that now
the metrics collection and publishing will be more aligned
across all instances of a cluster. From initial testing it
is not expected to cause problems.

adjust initial polling delay

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/NetflixConfig.java
spectator-nflx-plugin/src/test/java/com/netflix/spectator/nflx/NetflixConfigTest.java

These will be set when running in environments that are
supported. However, when running locally they may not be
set which can lead to some errors when used as substitutions
for other settings.

add defaults for context environment variables

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/NetflixConfig.java

These can sometimes be used as well for looking up context
specific to the app rather than the general environment.

add defaults for app and cluster

---

spectator-reg-micrometer/src/main/java/com/netflix/spectator/micrometer/MicrometerRegistry.java

I'm in the process of rolling out `spectator-reg-micrometer` as a bridge to Micrometer.  There are some Micrometer core types that do not jive with the Micrometer `Type` enum - for example `FunctionalTimer` is a distinct core meter type, even though the Type enum that it receives is that of `TIMER`. 
This resolves that issue and allows us to move forward in a backwards compatible (+/-) way.
@brharrington

Check if meter is instance of supported type prior to returning new meter type

---

spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
spectator-api/src/test/java/com/netflix/spectator/api/CompositeRegistryTest.java

This helps guard against double counting for the global
registry if an application has bugs in its initialization
that cause the same underlying registry to get added more
than once.

dedup registries added to composite

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapCounter.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapMaxGauge.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapTimer.java
spectator-api/src/main/java/com/netflix/spectator/impl/SwapMeter.java
spectator-api/src/test/java/com/netflix/spectator/api/CompositeRegistryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/SwapMeterTest.java

If instrumented properly, the number of distinct ids should
not grow unbounded for the life of the process. However, if
users are not disciplined enough with their tagging, this can
occur. With the previous implementation of CompositeRegistry
it would keep track of all of the ids it saw so it could
update the mapping if the registries ever changed. This would
lead to the set of ids growing and eventually using up all
of the heap.
With this change, the composite registry no longer stores the
ids, it just returns a new copy of the SwapMeter instance. A
version is used to indicate if a change has occured that would
require it to perform a new lookup.
This will result in additional allocations if the same id is
looked up repeatedly. Before it would have just returned the
meter instance from …

avoid storing ids for CompositeRegistry

---

spectator-api/src/main/java/com/netflix/spectator/api/patterns/GaugePoller.java
spectator-api/src/main/java/com/netflix/spectator/api/patterns/PolledMeter.java
spectator-api/src/test/java/com/netflix/spectator/api/patterns/PolledMeterTest.java

Before it would remove the meter from the state map and
then wait for the object to get garbage collected. In
some cases this could take a while and if a new meter
was registered with the same id, then the value could
get overwritten. Now the polling will get stopped as
part of the remove.

immediately stop polling in PolledMeter.remove

---

spectator-reg-atlas/build.gradle

Internally there are some apps that cannot move beyond
guava 19. When spectator updated to jackson 2.10.0 an
alignment rule forced all jackson subprojects to that
version include jackson-datatype-guava which as of
2.10.0 now dependes on guava 20.
To try and minimize the chances we will be in the middle
of such a mess in the future, this change shades the
jackson usage. The dependency has been relocated, inlined,
and POM file has those dependencies removed.

shade jackson for spectator-reg-atlas

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

Before if the id did not include a key it would not match
a query checking the key was not equal to a given value.

fix handling of not queries with missing keys

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java

If the application has a bug in its initialization, then
we sometimes see the stop method get called without the
registry having been started. This would result in an NPE
getting logged because the sender pool was not setup. With
this change the send will get ignored if the pool is not
setup. Should avoid support requests from users asking
about the exception.

avoid NPE if registry is shutdown without starting

---

spectator-reg-atlas/build.gradle

Verifies that we do not accidentally include stuff from
dependencies that has not been relocated.

add sanity check for contents of shadow jar

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

It seems to have much better performance for iterating
the map with little penalty for get/put with the real
workloads we tested. For most of the tests it was around
50% faster.

use LinkedHashMap for measurements

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDistributionSummary.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMaxGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMeter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimer.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasGaugeTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasMaxGaugeTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java

Removes the allocation of temporary lists from the
measure call. Also reduces some of the checks for
each meter:
- Expiration check can be avoided because the expired
meters will get removed in the context where the
data is collected.
- NaN checks inlined to the gauge type which is the
only type where it would be possible to have a NaN
value for the measurement.

optimize the collection of measurements

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java

This gives more control over how the data coming in will
be distributed across the step interval. By default it
will try to spread it out randomly to distribute the load.
Other policies can be chosen if needed for a given setup.
See also: #756.

make the initial polling delay configurable

---

.travis.yml
build.gradle

It was pending update to gradle 6, see #761. Support
for jdk12 has been dropped consistent with policy of
supporting 2 LTS plus latest.

update travis build to include jdk13

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

The wrong variable was used for the removal portion
of the condition leading to:
```
java.lang.NullPointerException: null
at com.netflix.spectator.atlas.impl.QueryIndex.removeFromMissingKeysIdx(QueryIndex.java:220)
at com.netflix.spectator.atlas.impl.QueryIndex.remove(QueryIndex.java:239)
at com.netflix.spectator.atlas.impl.QueryIndex.remove(QueryIndex.java:189)
at com.netflix.spectator.atlas.impl.QueryIndex.remove(QueryIndex.java:236)
at com.netflix.spectator.atlas.impl.Evaluator.sync(Evaluator.java:91)
at com.netflix.spectator.atlas.AtlasRegistry.fetchSubscriptions(AtlasRegistry.java:402)
```

fix NPE for removing not queries

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpRequestBuilder.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/RetryPolicy.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/HttpRequestBuilderTest.java

Updates the sample HTTP client that wraps HttpURLConnection
to support a RetryPolicy. By default it uses a safe policy
that will retry read requests for all exceptions, throttling,
and 5xx errors. Write requests will only get retried for
connect exceptions and throttling. Other failures could have
a partial write and are considered unsafe to retry.

customizable retry policy for http client

---

spectator-reg-atlas/build.gradle

Retain illegal package name to prevent accidental importing.
By having a valid package name as the prefix, one can configure their IDE to prevent auto-import of the shaded dependency.

Relocate shaded dependency under library's package root. 

---

spectator-ext-ipcservlet/src/main/java/com/netflix/spectator/ipcservlet/IpcServletFilter.java

This is no longer used and should get phased out.

remove usage of IpcErrorGroup

---

docs/ext/ipc.md
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcFailureInjection.java

This allows properly tagging IPC metrics where both a failure
and latency has been injected.

add delay_and_failure failure injection type

---

spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/JsonUtils.java
spectator-reg-stateless/src/test/java/com/netflix/spectator/stateless/JsonUtilsTest.java

Update the behavior of the `StatelessRegistry` to match the other thin
clients that assume a missing `statistic` tag, or an unknown value for
that tag encodes a gauge measurement.

Treat unknown or missing statistic as gauges

---

dependencies.properties

Pick up fix for DNS resolution with netty client. The
usage in Spectator is just for instrumentation so this
is mostly in case someone gets it transitively.
https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md#21056-2020-01-24

aws-sdk-java-v2 2.10.56

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Pull in fix to disable publishing the gradle module file
when using the shadow plugin. This incorrectly includes the
shaded dependencies which can cause issues for consumers.

nebula oss plugin 8.6.0

---

build.gradle
spectator-agent/build.gradle
spectator-api/build.gradle
spectator-ext-aws/build.gradle
spectator-ext-aws2/build.gradle
spectator-ext-gc/build.gradle
spectator-ext-ipc/build.gradle
spectator-ext-ipcservlet/build.gradle
spectator-ext-jvm/build.gradle
spectator-ext-log4j1/build.gradle
spectator-ext-log4j2/build.gradle
spectator-ext-placeholders/build.gradle
spectator-ext-sandbox/build.gradle
spectator-ext-spark/build.gradle
spectator-nflx-plugin/build.gradle
spectator-nflx/build.gradle
spectator-perf/build.gradle
spectator-reg-atlas/build.gradle
spectator-reg-metrics3/build.gradle
spectator-reg-micrometer/build.gradle
spectator-reg-servo/build.gradle
spectator-reg-stateless/build.gradle
spectator-web-spring/build.gradle

We are doing some work to remove compileApi configuration from nebula (https://github.com/nebula-plugins/nebula-publishing-plugin/pull/159)
`nebula.compile-api `plugin was created for:
* adds a compileApi configuration which will put dependencies in the compile scope of maven poms
* This configuration should only be used for dependencies that are actually present in the api and needed to compile.
This is now accomplished via java-library plugin (https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation)

Support java library plugin

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/RetryPolicy.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/RetryPolicyTest.java

If the `SocketTimeoutException` had a null message, then
it would result in an NPE.

fix NPE for IPC retry policy

---

build.gradle
spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/main/java/com/netflix/spectator/api/Id.java
spectator-api/src/test/java/com/netflix/spectator/api/ArrayTagSetTest.java

The main use-case was to sort the list. This change
switches to a simple insertion sort that can work on
the paired string array in-place. Since the set of
tags is small, internally limited to less than 20,
this works well for current use-cases.
JMH benchmark shows throughput increased and
allocations per operation were reduced.
**Throughput**
| Benchmark            |        Before |         After | % Delta |
|----------------------|---------------|---------------|---------|
| append1              |  33,912,834.4 |  35,650,910.7 |     5.1 |
| append2              |  23,578,876.9 |  24,495,289.0 |     3.9 |
| append4              |   6,793,235.3 |   8,047,446.0 |    18.5 |
| append4sorted        |   7,863,378.4 |   8,574,785.4 |     9.0 |
| baseline             |  28,814,809.1 | …

avoid allocating tag objects for ids

---

spectator-api/src/jmh/java/com/netflix/spectator/perf/BucketMeters.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketCounter.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketTimer.java

The meter for a bucket will get stored so it can get quickly
looked up for subsequent updates.
**Throughput**
| Benchmark            |        Before |         After | % Delta |
|----------------------|---------------|---------------|---------|
| counterRecord        |  30,046,637.8 |  77,787,334.6 |   158.9 |
| distRecord           |  26,777,122.7 |  63,082,754.3 |   135.6 |
| timerRecord          |  25,752,977.2 |  56,120,916.6 |   117.9 |
**Allocations**
| Benchmark            |        Before |         After | % Delta |
|----------------------|---------------|---------------|---------|
| counterRecord        |          88.0 |           0.0 |  -100.0 |
| distRecord           |          88.0 |           0.0 |  -100.0 |
| timerRecord          |          88.0 |           0.0 |  -100.0 |

avoid id alloction for bucket type updates

---

spectator-agent/build.gradle
spectator-ext-spark/build.gradle

Newer versions of nebula plugin does this automatically. Fixes
errors on builds:
```
Execution failed for task ':spectator-agent:publishNebulaPublicationToBintrayRepository'.
> Failed to publish publication 'nebula' to repository 'Bintray'
> Invalid publication 'nebula': multiple artifacts with the identical extension and classifier ('jar', 'shadow').
```

remove config to publish of shadowJar

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java

Updates the query index to avoid allocating the list and
caching an empty list for cases where there are no other
checks (key queries that are not exact equality). For most
cases it is a small overhead, but for some data sets it
can be significant.

reduce allocations for other key queries

---

build.gradle
spectator-reg-atlas/src/jmh/java/com/netflix/spectator/atlas/PollMetersBench.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDistributionSummary.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMaxGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMeter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimer.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/MeasurementConsumer.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Evaluator.java

Refactors the code to avoid creating temporary Measurement
lambda instances.
**Throughput**
| Benchmark            |        Before |         After | % Delta |
|----------------------|---------------|---------------|---------|
| pollMeters           |          11.2 |          14.5 |    30.0 |
**Allocations**
| Benchmark            |        Before |         After | % Delta |
|----------------------|---------------|---------------|---------|
| pollMeters           |   9,077,604.8 |     933,845.9 |   -89.7 |

reduce allocations for AtlasRegistry.pollMeters

---

dependencies.properties
spectator-ext-ipc/build.gradle
spectator-ext-ipc/src/jmh/java/com/netflix/spectator/ipc/ShardParsing.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/ServerGroup.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/ServerGroupTest.java

Updates the random ASG generator in the tests to include
the naming convention patterns and fixes gaps with recent
changes to frigga. In particular:
1. Sequence logic has been updated to match the same range
of numeric values allowed.
2. Support for parsing shards has been added for the shard1
and shard2 that are intended to be used as tags.

update ServerGroup helper for recent frigga changes

---

spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java

For now we use the same logic for extracting the region
as normal zones. This may get revisited in the future
to be the actual base AWS region.

add test case for AWS local zones

---

spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessConfig.java
spectator-reg-stateless/src/test/java/com/netflix/spectator/stateless/StatelessConfigTest.java

There was a copy/paste issue and it was looking at the
enabled setting before.

fix property name for frequency setting

---

spectator-ext-spark/src/test/java/com/netflix/spectator/spark/SpectatorConfigTest.java

Simple test case to ensure reference config loads as
expected.

spark: add test case for registry config

---

spectator-ext-log4j2/src/main/java/com/netflix/spectator/log4j/SpectatorAppender.java
spectator-ext-log4j2/src/test/java/com/netflix/spectator/log4j/SpectatorAppenderTest.java

Update the the new constructor for the AbstractAppender class.

fix deprecation warning for log4j2 AbstractAppender

---

spectator-api/src/jmh/java/com/netflix/spectator/perf/DefaultStat.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMaxGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasCounterTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasGaugeTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasMaxGaugeTest.java

The atlas counter and gauges cache the `Id` used for reporting
measurements. This change improves the performance of this operation by
creating a new `Id` from scratch instead of adding the statistic tag to
our base id, and then re-adding all the original tags. This avoid
iterating over all the tags in the original `Id` twice.
```
Benchmark                      Mode  Cnt        Score        Error  Units
DefaultStat.withIdWithTags    thrpt    9  2693269.613 ± 189599.585  ops/s
DefaultStat.withNameWithTags  thrpt    9  3485856.299 ± 116456.216  ops/s
```

Faster approach to set the default statistic tag

---

gradle/wrapper/gradle-wrapper.properties
spectator-agent/build.gradle
spectator-ext-spark/build.gradle
spectator-reg-atlas/build.gradle

Move back to older versions. Something with the combination
of gradle 6.5 and shadow 6.0.0 breaks the publishing due
to duplicate artifacts. Same error message as in #807.

gradle 6.4.1 and shadow 5.2.0

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/EvalPayload.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/EvalPayloadTest.java

Batch the data going to LWC API. This change reuses the
batch size parameter for payloads going to the publish
endpoint. Ensures that the max request size is bounded.

batch payloads to LWC API service

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/MeasurementSerializer.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/SubscriptionManagerTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/MeasurementSerializerTest.java

Allows the set of valid tag characters to be set to null
in order to disable the conversion during serialization.
This helps improve performance for cases where the values
have already been validated and there is nothing to fix.

allow disabling replacement during serialization

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/DsType.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/Rollups.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/RollupsTest.java

This allows inline aggregation of dimensions like node
that can cause duplicate ids across systems.

use sum dstype for Atlas rollups

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/ValidationHelper.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/ValidationResponse.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/ValidationHelperTest.java

Meant to be consistent with the same metrics that are already
provided by spectator-js (Netflix/spectator-js#39).

add metrics to track measurements sent and dropped

---

spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/main/java/com/netflix/spectator/api/DefaultId.java
spectator-api/src/main/java/com/netflix/spectator/api/Id.java
spectator-api/src/main/java/com/netflix/spectator/api/TagList.java
spectator-api/src/test/java/com/netflix/spectator/api/ArrayTagSetTest.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultIdTest.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/RollupPolicy.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/Rollups.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/RollupPolicyTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/RollupsTest.java

This is similar to the aggregate config used on the legacy
internal client. The rollup policy has been refactored so
that it can operate on the common tags as well as user tags.
This is a breaking change if anyone was already using the
RollupPolicy interface, but couldn't find any examples and
it was considered an experiment before. Unfortunately that
was not clearly marked.

atlas: add support for rule based rollup

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/NetflixConfig.java
spectator-nflx-plugin/src/test/java/com/netflix/spectator/nflx/NetflixConfigTest.java

Update the common tags for the NetflixConfig to ignore values
that are present, but empty.

empty common tag values should get ignored

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

This is an internal detail for publishing, but not something
that should come back to the user. Restores the behavior from
prior to #836.

atlas: don't merge common tags for measurements()

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/RetryPolicy.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/RetryPolicyTest.java

In some cases the message is "Connect timed out" and didn't
match because of the casing. The message is now converted
to lowercase to make the matching more likley. It is still
pretty hacky, but not sure of a better way.

ipc: more robust connect timeout detection

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcStatus.java

This is for some uses like GraphQL where the response code
at the HTTP level is typically 200 even if there are various
errors returned in the response payload.

ipc: add `application_error` status

---

spectator-api/src/main/java/com/netflix/spectator/impl/matcher/ZeroOrMoreMatcher.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/AbstractPatternMatcherTest.java

The zero or more matcher could result in an endless loop
when the repeated portion could match an empty string.

fix endless loop in matcher

---

spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java
spectator-ext-gc/src/main/java/com/netflix/spectator/gc/HelperFunctions.java

Update GC logger to better handle ZGC and Shenandoah
that will no longer be experimental in JDK15.

update for newer garbage collectors

---

.travis.yml

Drop jdk14 and add jdk15 to keep ensure latest version is
tested.

add jdk15 to travis build matrix

---

spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java

The `Concurrent GC` cause is used for both STW and
concurrent work. The name will be `Shenandoah Pauses`
for STW pauses and `Shenandoah Cycles` for concurrent.

fix concurrent phase check for Shenandoah

---

spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java
spectator-ext-gc/src/main/java/com/netflix/spectator/gc/HelperFunctions.java

ZGC and Shenandoah are not generational. They do not have
the normal allocation behavior seen with other GCs that
allow us to measure the allocation rate by comparing the
young gen pool size with a previous event. These new GCs
will only increment the promotion rate since there is
one memory pool.
Live data size also checks for entries with all zeroes
that sometimes get reported causing bogus values to show
up for the user.

fix promotion and live data size for new GCs

---

spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java

It seems like this only means some thread is blocked, but
from internal discussion the least confusing behavior seems
to be to count this as a pause rather than a concurrent
phase.

zgc: update pause timer for allocation stall

---

spectator-api/src/test/java/com/netflix/spectator/impl/matcher/CaseInsensitivePatternMatcherTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/JavaVersion.java

There was a bug in earlier Java versions. With jdk15 the
bug has been fixed and we can test with the full set of
expressions.

enable case-insensitive pattern tests in jdk15

---

spectator-api/build.gradle
spectator-api/src/main/java/com/netflix/spectator/impl/PatternMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/Matcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/PatternUtils.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/SqlPatternMatcherTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/ToSqlPatternTest.java

Adds a helper on the pattern matcher to get an equivalent
SQL LIKE pattern if possible. Can be used to more optimally
map a regex into a SQL where clause.

add helper to get SQL LIKE pattern

---

spectator-api/src/main/java/com/netflix/spectator/impl/matcher/CharClassMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/CharSeqMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/IgnoreCaseMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/IndexOfMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/NegativeLookaheadMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/OrMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/PositiveLookaheadMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/RepeatMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/SeqMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/StartsWithMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/ZeroOrMoreMatcher.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/MatcherEqualsTest.java

In some cases where we hash expressions these will get
called a lot and the allocations add up to be a considerable
overhead. The `Objects.hash` uses a varargs parameter so
it allocates an object array and boxes any primitives.

eliminate allocations for matcher hashcode

---

spectator-api/src/main/java/com/netflix/spectator/impl/matcher/OrMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/SeqMatcher.java

Avoids the creation of intermediate ArrayList objects
when rewriting SeqMatcher and OrMatcher. The SeqMatcher
in particular leads to a large number of allocations for
our expression set.

reduce allocations for matcher rewrite

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Subscription.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/SubscriptionTest.java

The `expr` field is computed from the string and the only
setter will update both. Using only the string for the
hash code computation is much faster in particular for
subsequent calls because string caches the hash code.

improve hash code performance for Subscription

---

build.gradle
spectator-api/src/jmh/java/com/netflix/spectator/perf/Ids.java
spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/main/java/com/netflix/spectator/api/Id.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultIdTest.java

For some use-cases where we already have the array this
method allows it to be reused. This method is named to
indicate it is unsafe since it depends on the caller
to have done all of the necessary sanity checks and
not modify the array after.

add helper to more efficiently create an Id

---

spectator-api/src/test/java/com/netflix/spectator/api/RegistryTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/AtomicDoubleTest.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMaxGauge.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasMaxGaugeTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessMaxGauge.java
spectator-reg-stateless/src/test/java/com/netflix/spectator/stateless/StatelessRegistryTest.java

This change makes the initial value for a max gauge `NaN`
rather than `0`. As a result negative values will be
treated as being larger and can be used with the max gauge
types.
The benefit is that when using an aggregator normal gauges
flow into a max guage on the remote service. So with this
change those gauges should behave more consistently with
expectations.
Note, this does mean that if someone was using a max gauge
directly via this library, it will now init to `NaN` on
each step interval rather than `0.0`. That is not a common
use-case so it is not a big concern. The local behavior
for the max on timers and distribution summaries has not
changed which is the common use-case.

support negative values for max gauge

---

spectator-api/src/test/java/com/netflix/spectator/impl/AsciiSetTest.java

Double check that null char would be replaced properly. We
saw some corrupt values come in and trying to isolate why
they were not rejected or replaced.

add test case for replacing null char

---

.github/workflows/release.yml
.github/workflows/snapshot.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Hi folks,
This upgrades to Nebula NetflixOSS which will publish to Nebula's OSS repos and Maven Central.
Repositories based on status:
* https://netflixoss.jfrog.io/artifactory/maven-oss-snapshots
* https://netflixoss.jfrog.io/artifactory/maven-oss-candidates
* https://netflixoss.jfrog.io/artifactory/maven-oss-releases

Replace bintray with publishing directly to maven central and NetflixOSS repositories

---

dependencies.properties
spectator-agent/build.gradle
spectator-agent/src/main/java/com/netflix/spectator/agent/Agent.java
spectator-nflx-plugin/build.gradle
spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/NetflixConfig.java

Updates the agent and nflx-plugin to use the common library
for creating the set of common tags to use. Helps keep
everything in sync as changes are made.

use iep-nflxenv to get common tags

---

spectator-api/src/main/java/com/netflix/spectator/api/BasicTag.java
spectator-api/src/test/java/com/netflix/spectator/api/BasicTagTest.java

Include the key name as part of the message. When used
as part of a tag list this helps narrow down the which
entry was causing problems.

improve exception message for null tag value

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/Registry.java
spectator-api/src/main/java/com/netflix/spectator/api/Utils.java
spectator-api/src/main/java/com/netflix/spectator/api/patterns/IdBuilder.java
spectator-api/src/main/java/com/netflix/spectator/api/patterns/LongTaskTimer.java
spectator-api/src/main/java/com/netflix/spectator/api/patterns/PolledMeter.java
spectator-api/src/test/java/com/netflix/spectator/api/RegistryExceptionsTest.java

Adds a test case that uses reflection to call all methods
or the registry with sample values including `null`. This
revealed a number of corner cases where the exception was
getting thrown to the user rather than just getting logged.

fix corner cases for error propagation check

---

spectator-api/src/main/java/com/netflix/spectator/impl/AtomicDouble.java

Before, if there was contention and the body of the loop
was accessed, then it could result in an infinite loop
because it accessed the raw value from the AtomicLong
rather than convert the bits to a double. If the long
bits for `v` treated as a long that is coerced to a double
is smaller than `v`, then the loop condition will never
be satisfied and it loops forever.
Not sure of a good test case to hit this, but the loop
behavior can be reproduced by initializing the max to
the raw long bits and running the `maxNegative` test.

fix inf loop in AtomicDouble.max

---

spectator-ext-log4j2/src/main/java/com/netflix/spectator/log4j/SpectatorAppender.java
spectator-ext-log4j2/src/test/java/com/netflix/spectator/log4j/SpectatorAppenderTest.java

There are some use-cases with dynamically generated
classes where the source is set, but the filename is
still null. Before this would result in an NPE due to
the precondition on the tag value.

fix NPE for log4j appender with null filename

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpResponse.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/HttpResponseTest.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/SubscriptionManager.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/SubscriptionManagerTest.java

Adds `entityInputStream` method for getting an InputStream
for consuming the entity. The main advantage is for use-cases
such as parsing JSON to internal model objects it avoids the
need to create an intermediate decompressed byte array.

add helper for getting entity stream

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

Fix NPE if the client passed into the constructor is not
already set.
```
java.lang.NullPointerException: Cannot invoke "com.netflix.spectator.ipc.http.HttpClient.get(java.net.URI)" because "this.client" is null
at com.netflix.spectator.atlas.SubscriptionManager.refresh(SubscriptionManager.java:81) ~[spectator-reg-atlas-0.128.0.jar:0.128.0]
at com.netflix.spectator.atlas.AtlasRegistry.fetchSubscriptions(AtlasRegistry.java:452) ~[spectator-reg-atlas-0.128.0.jar:0.128.0]
at com.netflix.spectator.impl.Scheduler$DelayedTask.runAndReschedule(Scheduler.java:401) ~[spectator-api-0.128.0.jar:0.128.0]
at com.netflix.spectator.impl.Scheduler$Worker.lambda$run$0(Scheduler.java:475) ~[spectator-api-0.128.0.jar:0.128.0]
at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:53) …
```

fix client used for subscription manager

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcTagKey.java

Consistency should be a high priority for the common IPC
metrics and we should discourage additions that are not
part of the [spec]. As a first step, the existing entries
for the IpcTagKey enum that are not in the spec have been
deprecated.
[spec]: https://netflix.github.io/spectator/en/latest/ext/ipc/

deprecate IpcTagKey entries that are not in spec

---

docs/ext/ipc.md
spectator-ext-aws2/src/test/java/com/netflix/spectator/aws2/SpectatorExecutionInterceptorTest.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcMetric.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcMetricTest.java
spectator-ext-ipcservlet/src/test/java/com/netflix/spectator/ipcservlet/IpcServletFilterTest.java

Adds a flag that can be used to enable strict validation
for IPC metrics. The goal is that this can be used in unit
tests for integrations to promote consistency.
For now the strict validation just ensures that the only
dimensions on an id are those that are allowed by the spec.
Additional checks can get added overtime which may break
tests for some integrations, but that should help catch
issues and drive compliance going forward.

ipc: add strict validation mode

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/DataGenerator.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryTest.java

Adds a remove method to the query index that works in the
same way as the add method. The query used when adding the
value must be specified which allows us to avoid searching
the entire index for the value to remove. Testing with a
randomly generated index with 100k queries, the new remove
variant averages 6us per call vs 25ms for the existing
remove variant.

add a faster QueryIndex.remove

---

build.gradle
spectator-ext-ipc/src/jmh/java/com/netflix/spectator/ipc/http/PathSanitizerBench.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/PathSanitizer.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/PathSanitizerTest.java

Adds a helper class to sanitize URL paths before using
as a tag value. This is best effort and tries to do a
reasonable job for common patterns that are seen. Users
would need to manually customize before calling if more
specific mappings are necessary.

ipc: add helper for sanitizing paths

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpRequestBuilder.java

Only log the last failed HTTP attempt at warn level, to reduce noise in the
logging platform.

reduce http logging

---

spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketDistributionSummary.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketFunction.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketFunctions.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketTimer.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpClient.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpLogEntry.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpRequestBuilder.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpResponse.java

The `spectator-ext-ipc` classes should be used instead.

deprecate sandbox http classes

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketCounter.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketTimer.java

Use a member variable to store capturing lambdas that
are often in a hot path in user code. This avoids the
allocation of a lambda on each call.

reduce allocations for lambda calls

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/Publisher.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/DefaultPublisher.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/GzipLevelOutputStream.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/JsonUtils.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/StreamHelper.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/ValidationHelper.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/ValidationResponse.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/StreamHelperTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/ValidationHelperTest.java

Moves the publishing logic to an interface that can be
overridden via the config. This allows some customization
such as trying alternate clients or sending to other
stores.

atlas: refactor publishing to allow customization

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Parser.java

Switch from TreeSet to HashSet for the in query. This
improves performance for the match check.

use HashSet for in query

---

build.gradle
spectator-api/src/main/java/com/netflix/spectator/impl/LfuCache.java

Switch to reusable priority queue rather than a on demand
set and separate sorting operation. This helps to reduce
allocations and improve throughput for the compaction.

reduce overhead of cache compaction

---

spectator-api/src/main/java/com/netflix/spectator/impl/matcher/RepeatMatcher.java

When the min and max repeat values are the same, use
the simpler form in the toString output for the matcher.
This tends to match actual usage of user written patterns
more closely.

simplify repeat matcher toString

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Parser.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryTest.java

If the regex pattern will match any possible value, then
rewrite to a has key query instead.

optimize case where regex always matches

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Evaluator.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Subscription.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/EvaluatorTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/SubscriptionTest.java

Before the expression string would get parsed whenever
it was set on the Subscription object. This can be slow
in particular for exprs with complex regex where the
pattern matching optimizer will need to make many passes.
In most cases, after the first fetch the set of expressions
is fairly consistent and only a few new expressions will
need to be parsed. This change makes the parsing lazy.
The other result of this change is that a bad expression
will not be noticed until it is accessed. The evaluator
has been updated with some additional error handling and
logging.

only parse exprs if needed

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/PathSanitizer.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/PathSanitizerTest.java

Improves handling of normal request parameters using
`?` rather than matrix arguments. In some cases these
may not get stripped off before calling the sanitizer.
Also explicitly checks the length of the sanitized
result.

additional checks for path sanitizer

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcMetric.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java

Updates the metric enum and logging helper to include
the inbound/outbound size metrics from the spec.

ipc: add inbound/outbound size metrics

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java
spectator-ext-ipcservlet/src/test/java/com/netflix/spectator/ipcservlet/IpcServletFilterTest.java

Update log entry helper to use the sanitized path for the
endpoint if not explicitly set.

ipc: use sanitized path as default endpoint

---

spectator-api/src/main/java/com/netflix/spectator/api/ExtendedRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/Registry.java
spectator-api/src/main/java/com/netflix/spectator/api/Spectator.java
spectator-api/src/main/java/com/netflix/spectator/api/patterns/PolledMeter.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcErrorGroup.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcTagKey.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketCounter.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketDistributionSummary.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketFunction.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketFunctions.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketTimer.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpClient.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpLogEntry.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpRequestBuilder.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/HttpResponse.java
spectator-reg-servo/src/main/java/com/netflix/spectator/servo/ServoRegistry.java

Cleanup deprecation notices and just note that they
will be removed in a future release. The exact timing
and release is not known at this time as we would have
to gauge the internal impact.

update deprecation messages

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java

There was a typo and it was using the client name instead.

ipc: fix metric name for server outbound size

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpRequestBuilder.java

Update the helper around the built in JDK client to set
the entity sizes on the ipc log entry.

ipc: set entity sizes for http client helper

---

spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java
spectator-ext-gc/src/main/java/com/netflix/spectator/gc/HelperFunctions.java

JDK17 has an update to the notification events for ZGC
to make it possible to accurately detect STW pauses
([JDK-8265136]).
[JDK-8265136]: https://bugs.openjdk.java.net/browse/JDK-8265136

update GC logger for ZGC changes in jdk17

---

spectator-reg-atlas/build.gradle
spectator-web-spring/build.gradle

This should help minimize issues with other uses that
might need to use older versions of jackson (e.g. #920).

shade jackson dependency for web-spring

---

spectator-ext-aws/README.md
spectator-ext-aws/src/main/java/com/netflix/spectator/aws/SpectatorRequestMetricCollector.java

The aws sdk places a value in HandlerContextKey.OPERATION_NAME (e.g. GetObject) at least
some of the time, so use a default that's not one of the predefined HandlerContextKey
objects to avoid that.
I noticed this with a test of spectator 1.0.5 against a localstack container.  Happy to add a test like that here is it's OK to add a test dependency on https://github.com/testcontainers/testcontainers-java.  Sorry I didn't catch this earlier.

fix(aws): change default handler context key

---

spectator-reg-atlas/src/jmh/java/com/netflix/spectator/atlas/ListIteration.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java

Iterate the matches list using size/get rather than the
foreach loop which allocates an iterator. This can often
be a hotspot for searching.

reduce allocations for searching query index

---

.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml

https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/

GitHub Actions setup-java v2

---

README.md

Point to the Spectator section of the atlas-docs site.

update link to docs

---

spectator-api/src/main/java/com/netflix/spectator/impl/StepDouble.java
spectator-api/src/main/java/com/netflix/spectator/impl/StepLong.java
spectator-api/src/main/java/com/netflix/spectator/impl/StepValue.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDistributionSummary.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimer.java

Update the Atlas distribution summary and timer so that
the record calls will only access the time value once for
a record call. Before it would happen internally to the
step value for each summary statistic. This can add up if
the meter is updated from a tight loop.

reduce calls to access time on record

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDistributionSummary.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMaxGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMeter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimer.java

Atlas meters get the current time to ensure they are
updating the correct entry for the step value. Now that
timestamp will be reused when updating the last mod time
for the meter.

reuse current time when updating last mod

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDistributionSummary.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMaxGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMeter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimer.java

Updates the AtlasRegistry to pass in the timestamp when
polling the meters to reduce the number of times the
`clock.wallTime()` call will need to be made.

reduce wallTime calls when sending

---

spectator-api/src/main/java/com/netflix/spectator/api/DistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/ManualClock.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/Timer.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileDistributionSummary.java
spectator-reg-atlas/src/jmh/java/com/netflix/spectator/atlas/BatchRecordBench.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDistributionSummary.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimer.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasDistributionSummaryTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasTimerTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/CountingManualClock.java

Supports record of many Timer and DistributionSummary metrics in a single call, and provides an optimised implementation for the Atlas implementation.

support batch record() of metrics in Timer and DistributionSummary

---

spectator-ext-log4j1/build.gradle

For more details see https://reload4j.qos.ch/. Builds using
nebula resolution rules will replace log4j with reload4j if
both are present ([5c087f]).
[5c087f]: https://github.com/nebula-plugins/gradle-resolution-rules/commit/5c087f742a9f0efe84855118e266c69a5fd4a58b

switch from log4j1 to reload4j

---

spectator-web-spring/build.gradle

Update spring dependencies for [security fix].
[security fix]: https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement

spring 5.3.18

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Parser.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryTest.java

Smaller in clauses will now get expanded to a disjunction
or equal clauses. This allows them to get indexed using
the faster exact match path and avoid being lumped into
the other checks. Looking at existing expressions ~95%
of in clauses are covered with the current size limit.

improve indexing for :in clauses

---

spectator-api/src/main/java/com/netflix/spectator/api/patterns/GaugePoller.java
spectator-api/src/main/java/com/netflix/spectator/api/patterns/PolledMeter.java
spectator-api/src/test/java/com/netflix/spectator/api/patterns/PolledMeterTest.java

Adds a `PolledMeter.poll` method that can be used to run
an arbitrary `Runnable` task using the default thread pool
for polled meters. The main use-case is for being able to
update multiple meters each time the task is run. In this
case, the user would just use the registry to make any
updates directly.
The advantage of this method over just having the user
scheduling it themselves is it avoids having additional
polling threads running for simple use-cases. It is not
connected to the lifetime of an object, so the caller must
keep track of and use the returned future to cancel if
the polling should be stopped.

helper to run task using PolledMeter pool

---

settings.gradle
spectator-api/src/main/java/com/netflix/spectator/api/TagList.java
spectator-reg-sidecar/README.md
spectator-reg-sidecar/build.gradle
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/CommonTags.java
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/NoopWriter.java
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/PrintStreamWriter.java
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/SidecarConfig.java
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/SidecarCounter.java
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/SidecarDistributionSummary.java
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/SidecarGauge.java
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/SidecarMaxGauge.java
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/SidecarMeter.java
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/SidecarRegistry.java
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/SidecarTimer.java
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/SidecarWriter.java
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/UdpWriter.java
spectator-reg-sidecar/src/main/resources/META-INF/services/com.netflix.spectator.api.Registry
spectator-reg-sidecar/src/test/java/com/netflix/spectator/sidecar/MemoryWriter.java
spectator-reg-sidecar/src/test/java/com/netflix/spectator/sidecar/PrintStreamWriterTest.java
spectator-reg-sidecar/src/test/java/com/netflix/spectator/sidecar/SidecarConfigTest.java
spectator-reg-sidecar/src/test/java/com/netflix/spectator/sidecar/SidecarRegistryTest.java
spectator-reg-sidecar/src/test/java/com/netflix/spectator/sidecar/UdpServer.java
spectator-reg-sidecar/src/test/java/com/netflix/spectator/sidecar/UdpWriterTest.java

With this implementation Java would be consistent
with other languages based on thin clients.

add registry that reports to SpectatorD

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Evaluator.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/PrefixTree.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/PrefixTreeTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

Two improvements to make it more efficient to check
incoming ids:
1. The :has queries are no longer lumped into the other
checks as all that needs to be verified is that the
key is present.
2. Uses a prefix tree for the other checks. The pattern
matcher for :re queries can be used to extract an
exact match prefix if possible for a regex. This makes
it much faster to perform the matching if there are a
lot of prefix regex queries. Looking at the current
set of expressions internally, this is quite common.
Running a test with an index of ~341k actual expressions
and a real set of ids for incoming datapoints, the indexing
improvements significantly increase the throughput in terms
of datapoints per second checked via the index.
| Test                         | Throughput | …

improve indexing for :has and :re

---

spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/Jmx.java

I was looking through our current JVM metrics and identified some areas where we have gaps:
- ClassLoading - Classloading is the most significant contributor to startup time and we've seen apps affected by runtime class generation issues more than once
- Thread - Characterize JVMs by thread count, detect issues with excessive thread allocations
- Compilation - Understand compilation times particularly when evaluating alternative JVMs
I'll start a thread internally to discuss.

Additional JVM metrics

---

spectator-api/src/main/java/com/netflix/spectator/impl/matcher/RepeatMatcher.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/AbstractPatternMatcherTest.java

Before it wouldn't explicitly group causing some patterns
like simple character sequences to get changed to only
repeat the last character. Now the repeated pattern will
get emitted as part of a non-capturing group.

fix toString for repeated pattern

---

spectator-api/src/main/java/com/netflix/spectator/impl/matcher/Optimizer.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/Parser.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/ZeroOrOneMatcher.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/MatcherEqualsTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/OptimizerTest.java

Before it would use an OR matcher to handle the zero or
one case. This is mostly to make it easier to experiment
with rewriting to simpler pattern formats used by some
data stores. It can be convenient to expand OR clauses,
but that can be expensive if there are many different
combinations. The zero or one, `?`, operator is commonly
used and often supported with simpler patterns so having
the explicit matcher reduces the number of combinations
from expanding OR clauses.

add zero or one matcher

---

spectator-api/src/main/java/com/netflix/spectator/impl/PatternMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/IndexOfMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/Matcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/NegativeLookaheadMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/Optimizer.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/OrMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/PatternUtils.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/PositiveLookaheadMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/RepeatMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/SeqMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/ZeroOrMoreMatcher.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/AbstractPatternMatcherTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/ExpandOrPatternMatcherTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/ExpandOrTest.java

Add helper to PatternMatcher for expanding OR clauses
to a set where the original pattern should match if
at least one of the expanded patterns match. This can
be a useful first step for other processing such as
indexing the query or rewriting for data stores that
support a more limited pattern matching.

support expanding OR clauses in regex

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

Before it would always remove from the prefix tree even
if there were other similar expressions with the same
prefix. After that those other expressions would never
match because the sub-index would no longer be in the
tree. Now it will only remove from the prefix tree if
the sub-index is empty.

fix removal for exprs with regex prefix

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/PathSanitizer.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/PathSanitizerTest.java

The path sanitizer uses runs of consonants to detect
values that are likely to be random. GraphQL is a
common path that hits that check. Special case it to
avoid removing.

ensure graphql is not removed by sanitizer

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/DefaultPublisher.java

When using the default publisher, the debug registry was
always null rather than falling back to using the registry
it is publishing for. This means that some of the validation
metrics would be missing.

fix validation metrics for default publisher

---

spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/main/java/com/netflix/spectator/api/Id.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultIdTest.java

Since this method is already sorting and that is needed
for finding duplicates, have it do the deduplication as
well. This will add a bit of overhead for existing usage
where it is already known that there are no duplicates.

dedup keys in Id.unsafeCreate

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java

Update the comment for the commonTags with AtlasRegistry
to indicate that the user is responsible for ensuring that
they conform to the valid tag character restrictions.

clarify expectations for common tags

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogger.java

When logging to some systems the MDC values are used for
tagging. Having the common IPC tags available as part of
the MDC can make it easier to query them independently
where the JSON for the message is just treated as a string.

add common IPC tags to MDC

---

spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/test/java/com/netflix/spectator/api/ArrayTagSetTest.java

Special case merging an ArrayTagSet with another to avoid the overhead of sorting, deduping, and copying. Since an ArrayTagSet is immutable is already sorted and deduped, we can skip directly to merging.
Additionally, add handling for merging of an ArrayTagSet with a TagList, where we can avoid some extra copying and allocating of Tags.

Special case merging ArrayTagSets and TagLists

---

spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java

The backing array was being allocated with double the required size when merging tags in ArrayTagSet::addAll.

Fix calculation of array size in ArrayTagSet::addAll

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/test/java/com/netflix/spectator/api/RegistryTest.java

Override AbstractRegistry::spliterator to return the ConcurrentHashMap's values Spliterator, which has estimated size and other characteristics set.

Delegate to ConcurrentHashMap values Spliterator in AbstractRegistry

---

spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java
spectator-ext-gc/src/main/java/com/netflix/spectator/gc/HelperFunctions.java

I was troubleshooting an GC pause outlier issue caused by survivor space growth and the associated copying, while overall allocation/tenuring rates remained stable. Issue was obvious from GC logs, but it occured to me this was a gap in our existing pool rates.

Add rate metrics for survivor pool growth

---

spectator-api/src/main/java/com/netflix/spectator/api/BasicTag.java

Use the [racy single-check idiom](http://javaagile.blogspot.com/2013/05/the-racy-single-check-idiom.html) to lazily compute and cache the hash code in BasicTag. The hashCode method of Tag / BasicTag is not called anywhere within Spectator itself, so precomputing the hash code in the constructor is now an unnecessary overhead.

Lazily compute hash code in BasicTag

---

spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/test/java/com/netflix/spectator/api/ArrayTagSetTest.java

- Only read cached hash code field once to avoid running afoul of edge case involving re-ordering of operations permitted by the Java memory model. (see [this blog post](http://jeremymanson.blogspot.com/2008/12/benign-data-races-in-java.html) for details).
- Make computed hash code consistent with Arrays.hashCode (e.g., ArrayTagSet.EMPTY hashes to 1).

Fix issues with ArrayTagSet's hashCode

---

codequality/checkstyle.xml
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Parser.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryTest.java

Update to be consistent with recent changes to Atlas backend to support `:contains`, `:starts`, and `:ends` query operations. These get mapped to regex so it only impacts the query parsing.
See: Netflix/atlas#1470 and Netflix/atlas#1471.

add support for contains, starts, and ends

---

spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/test/java/com/netflix/spectator/api/ArrayTagSetTest.java

When tags are supplied in a SortedMap, skip the sorting step. Additionally, skip deduping when tags are supplied in a Map in general.

Skip sorting in ArrayTagSet for SortedMaps

---

spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/test/java/com/netflix/spectator/api/ArrayTagSetTest.java

Change ArrayTagSet::add to avoid allocating extra space when an existing tag is being overridden, and to avoid creating a new ArrayTagSet at all if the supplied key/value pair already exists in the target ArrayTagSet.
Additionally, switch to System.arraycopy instead of manually copying to the newly created array.

Avoid allocating extra space when overriding tag

---

spectator-api/src/main/java/com/netflix/spectator/api/Counter.java
spectator-api/src/main/java/com/netflix/spectator/api/CounterBatchUpdater.java
spectator-api/src/main/java/com/netflix/spectator/api/DefaultTimer.java
spectator-api/src/main/java/com/netflix/spectator/api/DistSummaryBatchUpdater.java
spectator-api/src/main/java/com/netflix/spectator/api/DistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapCounter.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapTimer.java
spectator-api/src/main/java/com/netflix/spectator/api/Timer.java
spectator-api/src/main/java/com/netflix/spectator/api/TimerBatchUpdater.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultCounterTest.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultDistributionSummaryTest.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultTimerTest.java
spectator-api/src/test/java/com/netflix/spectator/api/ExpiringRegistry.java
spectator-api/src/test/java/com/netflix/spectator/api/SwapMeterTest.java
spectator-reg-atlas/src/jmh/java/com/netflix/spectator/atlas/BatchUpdates.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDistSummaryBatchUpdater.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDistributionSummary.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMeter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimer.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimerBatchUpdater.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasDistributionSummaryTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasTimerTest.java

Adds a helper that can be used to batch updates to the delegate meter. The main use-case for this is timers or distributions summaries that need to be updated from a single thread with a high throughput.
For counters, this can easily be achieved by the user with a local variable to track the count and then calling increment with the amount when complete or at the desired batch interval. However, for timers and distribution summaries that doesn't work because the implementation needs the raw samples. In #941 a method was added so the samples could be accumulated in an array and posted in a batch. This helps a bit, but it is cumbersome to use, incurs memory overhead, and the full set of samples have to be traversed and processed when recorded.
This change introduces batch updaters that can …

batch updater for counter, timer, and dist summary

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasCounterTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasDistributionSummaryTest.java

Adds a test case for AtlasCounter to ensure that it will preserve the custom statistic if one is used.

add test for preserving custom statistic

---

spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java

Non-generational Shenandoah and ZGC have two memory managers, one concurrent, one stop-the-world, named `<gc> Cycles` and `<gc> Pauses`:
- https://github.com/openjdk/jdk/blob/master/src/hotspot/share/gc/z/zServiceability.cpp#L123-L124
- https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/hotspot/share/gc/shenandoah/shenandoahHeap.cpp#L477-L478
However generational ZGC splits these into major/minor cycles/pauses:
- https://github.com/openjdk/zgc/blob/zgc_generational/src/hotspot/share/gc/z/zServiceability.cpp#L174-L187
Looks like there's no change required for genshen so far, they're using the same memory managers:
- https://github.com/corretto/corretto-17/blob/generational-shenandoah/src/hotspot/share/gc/shenandoah/shenandoahHeap.cpp#L2895-L2909
`Allocation …

Compatibility with generational ZGC

---

spectator-ext-gc/src/main/java/com/netflix/spectator/gc/HelperFunctions.java

Add ZGC generational memory manager labels.
genshen uses the same memory managers, but different pools and will go into a hybrid collection when necessary, so other than checking pool size changes, I'm not sure we can do anything there:
https://github.com/openjdk/shenandoah/blob/998f68b26b8d2a5178a30a6c5b596194961e3821/src/hotspot/share/gc/shenandoah/shenandoahHeap.cpp#L2928-L2935

Add ZGC generational memory managers

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

Before it was looking for a specific query type, but this wouldn't work in some cases such as a conjunction of NOT clauses. Now it just verifies if the sub-query will match an empty tag map.

fix check for matching with missing key

---

spectator-ext-jvm/src/jmh/java/com/netflix/spectator/jvm/MappingExprSubstitute.java
spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/MappingExpr.java
spectator-ext-jvm/src/test/java/com/netflix/spectator/jvm/MappingExprTest.java

The variable substitution when processing JMX data used the `String.replace` function. On java 8 this internally uses regex which is costly to compile. This change switches it to a custom function for replacing the values. On newer java versions the default is more efficient and doesn't use regex, but the custom version still seems to be a little better for the sample data tested.

use custom replace for substitutions

---

spectator-ext-jvm/src/jmh/java/com/netflix/spectator/jvm/MappingExprSubstitute.java

Fix variable name to something that is in the sample map.

update benchmark for substitutions

---

spectator-ext-spark/README.md
spectator-ext-spark/build.gradle
spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SparkSink.java
spectator-ext-spark/src/main/java/com/netflix/spectator/spark/SpectatorConfig.java
spectator-ext-spark/src/main/resources/reference.conf
spectator-ext-spark/src/test/java/com/netflix/spectator/spark/SpectatorConfigTest.java

Spark ext uses stateless registry that is deprecated according to its README.
Switch spark ext to sidecar registry in order to send metrics to the local spectatord.

switch spark ext to sidecar registry

---

spectator-ext-spark/build.gradle

If spectator is being used by a job running on Spark, then it can create conflicts with the extension used to monitor spark itself. This changes updates the shadow plugin settings to relocate the spectator sub-projects that are pulled in.

relocate spectator classes for spark ext

---

spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/SidecarWriter.java

Some writers such as the UDP writer can be quite noisy if the sidecar is not present. To avoid spamming the user with warnings, they will be suppressed after a warning is logged. Warnings will be re-enabled if there is a successful write so that if there are problems with the sidecar being intermittently accessible it will still get detected.

reduce warning volume for sidecar registry

---

spectator-ext-spark/build.gradle

We are relocating to avoid conflicts, but the jar wasn't added to the dependency list so it results in a class not found error.

include slf4j in spark shadow jar

---

spectator-ext-spark/build.gradle

The api jar is needed by other spark distribution jars so we cannot change the package.

do not relocate spectator-api for spark jar

---

spectator-ext-spark/build.gradle

This makes it easier to have consistent logging and slf4j typically isn't an issue with conflicting versions in the spark distribution.

do not shade slf4j in spark jar

---

spectator-ext-spark/build.gradle

This should avoid changing the spark version used if someone is pulling this in with maven or gradle.

make spark deps compileOnly

---

spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/SidecarWriter.java

Before we would reenable after successful calls so we could detect if the sidecar was having periodic problems. However, for UDP some calls can appear to be successful even if they have failed so it still leads to spammy logs. For now limit to the first failure.
Fixes #1025.

sidecar: only log the first failure

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Evaluator.java

Cache the query tags on the subscription entry so it only needs to happen once instead once per eval.

avoid recomputing query tags

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMeter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

Tune the `removeExpiredMeters` method to make it a bit more efficient. Uses the values iterator rather than entries so Entry objects are not needed. For the Atlas registry, the timestamp for the expiration check will now be computed once rather than once per meter.

reduce overhead for expiration pass

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

Avoid the list needing to grow if there are a lot
of batches.

pre-size batches list

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java

The name is used as the root of the query index and can have a big impact on the performance of matching against the index. Always expand the name when used with an in clause so it will increase the probability of a quick first match.

always expand in clauses for name key

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Consolidator.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Evaluator.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/EvaluatorConfig.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/IdMapper.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/EvaluatorTest.java

For some internal uses under heavy load, such as aggregators, it is desirable to have more control over some of the settings used with the LWC evaluator. In particular, this allows for tuning the cache behavior used with the index. Later it can be extended to support parallelism for matching against the index.

support more customization for evaluator

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Evaluator.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/EvaluatorConfig.java

Add option to poll measurements concurrently. This can be useful for apps that mostly just report metrics and are not doing other work. It is disabled by default to ensure there isn't heavy load for other apps.

support parallel polling of measurements

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

The private clock skew method was moved to the publisher implementation.

remove unused method

---

spectator-api/src/main/java/com/netflix/spectator/impl/StreamHelper.java
spectator-api/src/test/java/com/netflix/spectator/impl/StreamHelperTest.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpRequestBuilder.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/SubscriptionManager.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/DefaultPublisher.java

If there are a large number of subscriptions, then there can be a significant number of allocations from growing the ByteArrayOutputStream when consuming the response. Adds an option to the request builder to enable reusing the buffers.

reduce allocations for refreshing subscriptions

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

Updates the matches set to be a CopyOnWriteArraySet. For the hot path of finding matches, the set needs to have fast traversal. The key set from the ConcurrentHashMap is more efficient for updates, but allocates a Traverser and is slower to traverse.

use more efficient set type for QueryIndex

---

spectator-reg-atlas/src/jmh/java/com/netflix/spectator/atlas/EnsureIdTags.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMaxGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMeter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasGaugeTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasMaxGaugeTest.java

Updates how the cached stat id used for measurements is computed on simple meter types. Before it would always create a new id and then add back the original tags to overwrite. Now it will check to see if they are present and only add if missing. This ensures that at most a new id will be created once and in some cases not at all.

reduce overhead for cached stat id

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractRegistry.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeRegistry.java

The default implementation for some of the createId overloads in Registry don't create an ArrayTagSet directly and do some extra copying of tags.

Override createId methods in AbstractRegistry and CompositeRegistry

---

spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java

In JDK20 a new mbean has been added for tracking the concurrent phases of G1. Update the check to correctly attribute this as a concurrent phase.

support concurrent GC events for G1

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

Add `forEachMatch` overloads to the `QueryIndex` that takes a function to supply the value for a tag key. For use-cases where the tags are not already structured as an id, this avoids the overhead of converting. Since it is just a simple function, there is a lot of flexibility for the actual data structure used.

support matching without structuring as an id

---

build.gradle

Update to latest gradle jmh plugin for better compatibility with 8.0. Needed to move repository block to avoid errors when loading in intellij.

gradle jmh 0.7.1

---

build.gradle
codequality/checkstyle-suppressions.xml
codequality/checkstyle.xml
codequality/findbugs-exclude.xml
dependencies.properties
spectator-api/build.gradle
spectator-api/src/jmh/java/com/netflix/spectator/perf/IdHash.java
spectator-api/src/main/java/com/netflix/spectator/impl/Hash64.java
spectator-api/src/main/java/com/netflix/spectator/impl/UnsafeUtils.java
spectator-api/src/test/java/com/netflix/spectator/impl/Hash64Test.java

Currently based on XXH64. Allows for data to be incrementally fed to the hash accumulator to make it more convenient to use and avoid allocations creating the structure needed to pass into the hash. Though in some cases the incremental processing is slower than just passing in something like a precomputed string.

add utility for computing 64-bit hash

---

spectator-api/src/main/java/com/netflix/spectator/impl/AsciiSet.java

Adjust containsAll check to an indexOf operation so when doing the replacement the prefix of matching characters do not need to be re-checked.

minor optimization for AsciiSet

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Consolidator.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/DataExpr.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Evaluator.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/EvaluatorConfig.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/ConsolidatorTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/DataExprTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/EvaluatorTest.java

Add support for delaying gauge aggregation when pushing data to LWC. In some cases, the registry will be used on an intermediate cluster that aggregates results and can receive updates more frequently than the consumption step size. This can lead to the same gauge value coming from multiple aggregators leading to skewed values for accumulating aggregation types like sum and count.
To avoid this problem, the gauge aggregation can be delayed until the evaluator consuming the data so that the corresponding values can be deduped before computing the final aggregation. The deduping is based on the `atlas.aggr` dimension which is a hash of the id.

atlas: support delayed gauge aggregation

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Evaluator.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/EvaluatorTest.java

When performing a group by, if there is a datapoint that does not have all of the keys used in the grouping there would be an NPE. They will now get ignored similar to the behavior for counters or when not delaying the gauge aggregation.

atlas: fix npe for grouped lwc gauges

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/PathSanitizer.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/PathSanitizerTest.java

This allows an explicit set of allowed segment strings for some use-cases where there is a small set of known strings that are desirable to include, but do not match with the normal rules.

support allow set for PathSanitizer

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java

This can lead to a large set of endpoints for things like security scans. Logs should be used to track down those paths.

do not extract endpoint from path for 404s

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

If it was in the process of sending data when the registry is shutdown, then it could result in the same time interval getting sent multiple times. Synchronizing the methods is a simple solution for now as only a single thread should be performing a send at a given time.

atlas: fix duplicate flush on shutdown

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

Before it was using synchronized and the locks were overly broad. Now the locks are for a specific publish task. This allows sending to LWC to happen concurrently with sending to Atlas.

make locks specific to tasks

---

spectator-api/src/main/java/com/netflix/spectator/impl/PatternMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/CharSeqMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/IndexOfMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/PatternUtils.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/RepeatMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/SeqMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/StartsWithMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/ZeroOrMoreMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/ZeroOrOneMatcher.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/PatternUtilsTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/TrigramsTest.java

Add method to PatternMatcher that can be used to extract a set of trigrams based on the pattern. For the pattern to match, a string must contain all of the trigrams. This only indicates a string might match, the full pattern will still need to be evaluated on the candidates that contain all of the trigrams.

extract trigrams for patterns

---

spectator-api/src/main/java/com/netflix/spectator/api/ArrayTagSet.java
spectator-api/src/test/java/com/netflix/spectator/api/ArrayTagSetTest.java

It was possible to provide a list of `Tag`s to an `ArrayTagSet` with duplicate values. The duplicates would not be de-duped at merge time if the duplicate keys in the list were lexically less than that of existing tags. Merge now checks the last written tag value to make sure we don't write a duplicate key.

api: Fix duplicate tag bug.

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/SubscriptionManager.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/SubscriptionManagerTest.java

Update the JSON parsing for the LWC subscription manager so that it will ignore unknown fields. This avoids breaking if the server adds some additional metadata to the response. There is the expectation, that new fields can be added as long as it doesn't otherwise break the expected behavior for old clients.

atlas: ignore unknown properties for lwc subs

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/DataExpr.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java

Update links in javadoc comments to point to the new docs site instead of the old GitHub wiki.

atlas: remove links to old wiki

---

spectator-api/src/main/java/com/netflix/spectator/impl/matcher/CharSeqMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/RepeatMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/SeqMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/ZeroOrMoreMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/ZeroOrOneMatcher.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/AbstractPatternMatcherTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/ContainsPatternMatcherTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/ContainsTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/TrigramsPatternMatcherTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/TrigramsTest.java

Put in some additional test cases for extracting contained strings and trigrams from patterns. Fixes some cases with trigram extraction for repeats that can be absent from the string and still match.

additional tests for contains and trigrams

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/NetflixHeader.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java

Internally most IPC metrics will start coming from proxyd. To avoid confusion the backend behind it should not publish them if they are already provided for a request by the proxy.

ipc: disable metrics if proxyd header is present

---

spectator-api/src/main/java/com/netflix/spectator/api/AbstractTimer.java
spectator-api/src/main/java/com/netflix/spectator/api/CompositeTimer.java
spectator-api/src/main/java/com/netflix/spectator/api/NoopTimer.java
spectator-api/src/main/java/com/netflix/spectator/api/SwapTimer.java
spectator-api/src/main/java/com/netflix/spectator/api/Timer.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketTimer.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileTimer.java
spectator-api/src/main/java/com/netflix/spectator/impl/Scheduler.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultTimerTest.java
spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketTimer.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimer.java
spectator-reg-micrometer/src/main/java/com/netflix/spectator/micrometer/MicrometerRegistry.java
spectator-reg-micrometer/src/main/java/com/netflix/spectator/micrometer/MicrometerTimer.java
spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/SidecarTimer.java

Adds methods to the Timer interface to make it easier to work with the Supplier types in the JDK. There is already a method that works with Callable, but since that throws Exception it can be cumbersome to use in code. Methods have also been added for the suppliers with primitive types to avoid boxing.
Overload resolution can be messy with lambdas. To avoid those issues record methods have been added with a different name for each interface. The existing record methods for Callable and Runnable have been deprecated in favor of the more specifically named method.
Fixes #566.

api: add helper methods for Suppliers

---

spectator-api/src/main/java/com/netflix/spectator/api/Timer.java
spectator-api/src/test/java/com/netflix/spectator/api/DefaultTimerTest.java

Adds helpers to the Timer interface to wrap the common lambda types in `java.util.function`. This can be useful to wrap a lambda that is passed to another class in order to measure each invocation. For example:
```java
Timer t = registry.timer(id);
int sum = Arrays
.stream(new String[] {"foo", "bar", "baz"})
.mapToInt(t.wrapToIntFunction(String::length))
.sum();
```
Caller should ensure that the lambda does sufficient work that timing an invocatino will not be more costly than executing the lambda body.

api: add helpers to wrap lambdas with a timer

---

spectator-api/src/jmh/java/com/netflix/spectator/perf/ArrayTagSetSort.java

Verify performance behavior of #1079. Case with two tags is quite a bit slower with the simplification.

add benchmark for simplifying sort

---

spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java

GcLogger was using a ConcurrentHashMap that was only written to in its constructor; switch to an unmodifiable HashMap.

Remove unnecessary use of ConcurrentHashMap in GcLogger

---

spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcEvent.java

Simplify TIME_ORDER and REVERSE_TIME_ORDER comparators by leveraging Comparator.comparing and .reversed.

Simplify comparators in GcEvent

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/PathSanitizer.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/PathSanitizerTest.java

Fix StringIndexOutOfBoundsException if sanitize is called with an empty path string. Also updates the logic for `/` to be consistent with an empty path string. Both will now get sanitized to `none` as tag values cannot be empty.

ipc: avoid exception for empty paths

---

spectator-ext-aws2/src/main/java/com/netflix/spectator/aws2/SpectatorExecutionInterceptor.java
spectator-ext-aws2/src/test/java/com/netflix/spectator/aws2/SpectatorExecutionInterceptorTest.java

The retry header was changed in [2.15.41]. Update the parsing logic to work with the newer version.
[2.15.41]: https://github.com/aws/aws-sdk-java-v2/blob/8aaeeb0a001106db4f6add5bf9517dc130188b4b/.changes/2.15.41.json#L39

aws2: fix retry header parsing

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java

Before if there was a disabled request that was successful, then all subsequent requests that reuse the entry would also be disabled. Also moves the finalization of some of the fields to a helper that is always called to avoid different values going to the access log if metrics are disabled.

ipc: reset disable flag when reusing entries

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/DataExpr.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/DataExprTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/EvaluatorTest.java

Uses a placeholder name of `unknown` if the query for an aggregate function has no exact tags. This matches the behavior of the backend.

atlas: aggr function with empty tags

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

Add helper method to QueryIndex to help find hot spots in the index.

atlas: add method to find hotspots in index

---

spectator-api/src/main/java/com/netflix/spectator/impl/PatternMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/SeqMatcher.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/StartsWithMatcher.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/AbstractPatternMatcherTest.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java

For patterns where the prefix is extracted and verified before values are checked against the full matcher, we do not need to recheck the prefix. This change adds a method to the pattern matcher to allow bypassing the prefix and just matching against the remaining part of the pattern.

support checking for match after the prefix

---

spectator-api/src/main/java/com/netflix/spectator/api/patterns/CardinalityLimiters.java
spectator-api/src/test/java/com/netflix/spectator/api/patterns/CardinalityLimitersConcurrencyTest.java

Under contention the `CardinalityLimiters.FirstLimiter` will stop accepting values *before* its limit has been reached. 
This behavior happens when more than one thread add the same value to the limiter value registry and the `remaining` property is decremented even though no new entry has been added. 
I added a test in `CardinalityLimitersConcurrencyTest` that reproduces the issue fairly consistently. It simulates threads submitting the same series of numbers and expect all numbers to be registered. A failing test example output is below, note the `--others--` entries that should not be present.
```
at least one number was not registered in the limiter, 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49 …
```

FirstLimiter race

---

spectator-reg-atlas/build.gradle
spectator-web-spring/build.gradle

Indicate that the shadow jar is an artifact that should be published.

fix publishing of shadow jars

---

codequality/checkstyle-suppressions.xml
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/PrefixTree.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/PrefixTreeTest.java

Updates the prefix tree implementation to improve the performance. Instead of going character by character the nodes will now keep a prefix string for faster matching and less thread contention. Testing on real sample data it reduced the time for matching against the query index by ~6%.

tune prefix tree implementation

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryTest.java

In some cases it can be a big set of values and recomputing in the query index to do map looks has a high overhead.

cache hash code for Query.In

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/PrefixTree.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/PrefixTreeTest.java

Updates the query index to leverage the prefix tree for `:in` queries. The `:in` query will only be returned in the result set if it is an exact match, so no further checks are needed.

use PrefixTree for :in queries

---

spectator-ext-aws/README.md

I've found a small typo in the readme. Causes importing the wrong class when the correct would be `com.netflix.spectator.aws.SpectatorMetricCollector`.

Fix typo in README.md

---

spectator-reg-stateless/README.md
spectator-reg-stateless/build.gradle
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/StatelessRegistry.java
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/ValidationHelper.java
spectator-reg-stateless/src/main/java/com/netflix/spectator/stateless/ValidationResponse.java
spectator-reg-stateless/src/test/java/com/netflix/spectator/stateless/StatelessRegistryTest.java
spectator-reg-stateless/src/test/java/com/netflix/spectator/stateless/ValidationHelperTest.java
spectator-reg-stateless/src/test/java/com/netflix/spectator/stateless/ValidationResponseTest.java

When reporting data to aggregator check the response and report validation metrics/logs. This makes it easier to debug if data is getting rejected due to validation errors.

stateless: add validation metrics

---

build.gradle
spectator-agent/build.gradle
spectator-ext-spark/build.gradle
spectator-reg-atlas/build.gradle
spectator-web-spring/build.gradle

This should restore the old behavior and upgrading ASM to 9.6 adds support for JDK 21 
Sample POM:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<modelVersion>4.0.0</modelVersion>
<groupId>com.netflix.spectator</groupId>
<artifactId>spectator-reg-atlas</artifactId>
<version>1.8.0-SNAPSHOT</version>
<name>spectator-reg-atlas</name>
<description>spectator-reg-atlas</description>
<url>https://github.com/netflix/spectator</url>
<licenses>
<license>
<name>The Apache Software License, Version 2.0</name>
<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
<distribution>repo</distribution> …
```

Go back to com.github.johnrengelman.shadow and upgrade ASM to 9.6

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/DataExpr.java

When computing the final aggregation results for a group by it was getting each of the simple aggregates and flat mapping over the set. Adds a SimpleAggregator type to just get the aggregate, avoid the list allocation, and avoid flat mapping over the lists.

reduce overhead for group by result

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Evaluator.java

For simple aggregate functions the full set of tags are determined based on the expression. This means we can avoid mapping the id to a tag map.

avoid id mapping for aggregate functions

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/DataExpr.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Evaluator.java

Avoid copying to new map for the group by.

reduce allocations for group by result tags

---

spectator-api/src/main/java/com/netflix/spectator/impl/Hash64.java

Improve performance of the updateBytes method by reducing the number of calls to checkSpace.

hash64: reduce number of checkSpace calls

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Evaluator.java

Update evaluator for streaming expressions to allow them to be evaluated in parallel. This can be useful when run as a centralized service with thousands of expressions.

atlas: support parallel evaluation

---

spectator-api/src/main/java/com/netflix/spectator/impl/PatternExpr.java
spectator-api/src/main/java/com/netflix/spectator/impl/matcher/IgnoreCaseMatcher.java
spectator-api/src/test/java/com/netflix/spectator/impl/matcher/Re2CaseInsensitivePatternMatcherTest.java

Allows mapping case insensitive regex to systems that only support simpler regex like RE2. Fixes #1126.

support case insenstive patterns for toPatternExpr

---

build.gradle
spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileDistributionSummary.java
spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileTimer.java

PercentileTimer.computeIfAbsent would delegate to Utils.computeIfAbsent, which actually eagerly calls get and then putIfAbsent if the timer is not in the underlying map. Just directly do that to avoid needing to allocate a lambda in the case the timer is present.

Avoid allocating lambda in PercentileTimer.computeIfAbsent

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/SubscriptionManager.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Subscription.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/SubscriptionTest.java

This registry only supports forwarding data for time series. Ignore other expression types if present.

atlas: limit LWC subs to time series exprs

---

spectator-ext-spark/build.gradle

Update the spark integration to use the main version of spark and scala in use at Netflix. Metrics version bumped to match what is used in spark 3.3 ([link](https://github.com/apache/spark/blob/27fdf96842ea5a98ea5835bbf78b33b26db1fd3b/pom.xml#L157)).

spark: update to versions used internally

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/RollupPolicy.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/Rollups.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/RollupsTest.java

Add an operation to the rule that can be used to indicate data should be dropped entirely.

atlas: support dropping data in rollup policy

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HostSanitizer.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/HostSanitizerTest.java

Adds a utility that can be used for sanitizing host names before adding them as a tag values. Tries to remove things like random aspects, IPs, UUIDs, ports, etc.

ipc: add host sanitizer utility

---

README.md

Switch to recordRunnable for the timer example.

Fix deprecated method in readme

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

The `step` variable is a duration and the toString indicates the units. Remove the `ms` in the log message which are confusing and lead to message like `PT1Mms`.

atlas: cleanup stop log message

---

spectator-api/src/main/java/com/netflix/spectator/impl/Scheduler.java
spectator-api/src/test/java/com/netflix/spectator/impl/SchedulerTest.java

Updated the scheduler helper to have the shutdown method block until the threads stop. This makes it easier for callers to ensure they are not competing with in-progress tasks while performing other shutdown work.

scheduler will now wait for threads on shutdown

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/PrefixTree.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/PrefixTreeTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

Add couldMatch check which can be used as a quick pre-filter on a partial tag set. This can be useful for cases where there is an expensive transform needed to get the final set of tags.

atlas: add couldMatch to QueryIndex

---

spectator-ext-aws/README.md
spectator-ext-log4j1/README.md
spectator-nflx-plugin/README.md
spectator-reg-metrics3/README.md
spectator-reg-metrics5/README.md

Update readmes for some sub-projects to indicate they are deprecated and usage should be phased out.

add deprecation notices to readmes

---

spectator-ext-aws/src/main/java/com/netflix/spectator/aws/SpectatorMetricCollector.java
spectator-ext-aws/src/main/java/com/netflix/spectator/aws/SpectatorRequestMetricCollector.java
spectator-ext-aws/src/main/java/com/netflix/spectator/aws/SpectatorServiceMetricCollector.java

Deprecate these classe to encourage users to transition to V2 before [AWS support for V1] ends.
[AWS support for V1]: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/

aws: deprecate classes

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java

Before the check for name against k1 could happen multiple times.

atlas: simplify compare method for name

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

Updates can happen concurrently with reads. This can result in some of the volatile variables being set to `null` after the `null` check occurs. Now they will get copied to a local reference before being used for reads.

atlas: fix race condition for QueryIndex

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java

Update QueryIndex.forEachMatch to use the proper position when calling sub-trees. This reduces the need to reprocess earlier positions in the tags list that will not match.

atlas: reduce amount of tag traversal

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogger.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLoggerConfig.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java

The inflight metrics are poorly modeled and can often be confusing. They do not aggregate as expected so aren't really meaningful unless you understand the full set of dimensions used. Add option to disable them. Cannot remove for now due to backwards compatibility.

ipc: add option to disable inflight

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogger.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/Defaults.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpClient.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/DefaultsTest.java

Update the visibility to allow the config to be customized. The default http client wrapper now sets up the config to delegate to system properties.

ipc: make constructor with logger config public

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Parser.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/ParserTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryTest.java

Update query parsing to support unicode escapes for special characters like comma.

atlas: support unicode escapes in expressions

---

spectator-ext-jvm/build.gradle
spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/JavaFlightRecorder.java
spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/Jmx.java
spectator-ext-jvm/src/main/java17/com/netflix/spectator/jvm/JavaFlightRecorder.java
spectator-ext-jvm/src/test/java/com/netflix/spectator/jvm/JavaFlightRecorderUnsupportedTest.java
spectator-ext-jvm/src/test/java17/com/netflix/spectator/jvm/JavaFlightRecorderTest.java

This adds Java Flight Recorder support using [JFR Event Streaming](https://openjdk.org/jeps/349) to begin adding measures that are not available via other means. For starters this includes per-process CPU load, Virtual Threads and ZGC.
Event Streaming was added in JDK 14, so I've anchored this to the nearest LTS using a Multi-Release jar so the classes are only visible on supported releases.
I need to dig deeper, but at a glance all of the current `registerStandardMXBeans` and `GcLogger` measures could be handled by JFR events instead. Unless there are any concerns, I'll follow this up with replacements for all of these standard measures with an `jfr` prefix so we can confirm parity with the `jvm` metrics in the real world.

Add Java Flight Recorder support

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java

Results in a
`java.lang.NullPointerException: Cannot invoke "com.netflix.spectator.ipc.IpcLogger.inflightEnabled()" because "this.logger" is null`

ipc: Fix NPE from #1150 if IPC logger is not configured.

---

spectator-api/src/main/java/com/netflix/spectator/api/NoopDistributionSummary.java
spectator-api/src/test/java/com/netflix/spectator/api/NoopDistributionSummaryTest.java

Implement overrides for batchUpdater and record in NoopDistributionSummary that do nothing and avoid allocating.

Implement missing overrides in NoopDistributionSummary

---

spectator-ext-jvm/src/main/java/com/netflix/spectator/jvm/Jmx.java

When I added the condition for ensuring we were still registering memory pools, I missed dropping the short-circuit return, so we accidentally dropped these.

Remove unintentional return

---

spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileBuckets.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/PercentileBucketsTest.java

Update the buckets helper to allow for computing the approximations using floating point counts. Avoids the need for conversion to integer which can be tricky to do correctly in some cases.

api: percentile approximations from doubles

---

.github/workflows/release.yml
.github/workflows/snapshot.yml

The builds were failing because that version was not available.

update snapshot/release builds for jdk23

---

spectator-api/src/main/java/com/netflix/spectator/impl/AtomicDouble.java
spectator-api/src/main/java/com/netflix/spectator/impl/StepDouble.java
spectator-api/src/main/java/com/netflix/spectator/impl/StepLong.java
spectator-api/src/test/java/com/netflix/spectator/impl/AtomicDoubleTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/StepDoubleTest.java
spectator-api/src/test/java/com/netflix/spectator/impl/StepLongTest.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasDistributionSummary.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasMaxGauge.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasTimer.java
spectator-reg-micrometer/src/main/java/com/netflix/spectator/micrometer/MicrometerRegistry.java

Use AtomicLongFieldUpdater to shrink the footprint of StepLong, StepDouble, and AtomicDouble.
From a heapdump for a typical app, we see tens of thousands of instances of these classes:
StepLong: 21,751 instances
StepDouble: 29,233 instances
AtomicDouble 31,822 instances
Getting rid of the object reference to an AtomicLong shrinks the allocation footprint and avoids the extra pointer chasing. Note that StepLong and StepDouble still have a field `current` that is an AtomicLong / AtomicDouble; it can't be inlined into a volatile field without breaking backwards compatibility since it is exposed via the `getCurrent` method.

Use AtomicLongFieldUpdater in StepLong, StepDouble, and AtomicDouble

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/PrefixTree.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/PrefixTreeTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

If a node only had a single child after a removal, it would get compressed by merging the prefix. However the children of the merged child node were getting dropped.

atlas: fix bug in PrefixTree

---

spectator-ext-gc/src/main/java/com/netflix/spectator/gc/GcLogger.java

We noticed `:dist-avg` under 1ms for ZGC and `getDuration` is in milliseconds, so we must be regularly seeing events that start and end in the same millisecond:
https://github.com/openjdk/jdk/blob/3b283543c33df8c225e10b9186b7bc3cefd1a347/src/jdk.management/share/classes/com/sun/management/GcInfo.java#L140-L147
There are few other problems with these metrics and the concurrent garbage collectors, but I'm intentionally avoiding looking at those because we expect to have better ways of measuring GC overhead/pressure in upcoming releases.

Avoid 0 duration GC event times

---

spectator-ext-aws/src/main/java/com/netflix/spectator/aws/SpectatorRequestMetricCollector.java
spectator-ext-aws/src/test/java/com/netflix/spectator/aws/SpectatorRequestMetricCollectorTest.java

Avoid null values in any custom tags that are passed into the collector.

aws: check for null values in custom tags

---

spectator-nflx-plugin/src/main/java/com/netflix/spectator/nflx/SpectatorModule.java
spectator-reg-atlas/build.gradle
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasRegistry.java

Most things have now moved to the jakarta annotations. If using the module it will still work as expected via a provider.

atlas: remove inject dependency

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounterBatchUpdater.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasCounterTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/AtlasRegistryTest.java

Ensure that if a counter is expired, any existing batch updaters will re-lookup the counter when flushing updates. Otherwise all updates from the batch updater will get ignored.

atlas: fix expiration for counter batch updates

---

spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/UdpWriter.java
spectator-reg-sidecar/src/test/java/com/netflix/spectator/sidecar/UdpWriterTest.java

Since the write is inline in user threads the write can get interruped leading to the channel being closed. Before all subsequent writes would fail, now it will detect a closed channel and attempt to reconnect.

sidecar: try to reconnect if channel closed

---

spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileBuckets.java
spectator-api/src/test/java/com/netflix/spectator/api/histogram/PercentileBucketsTest.java

In some cases the floating point math would result in it going to the end of the buckets and treating the max value as `Long.MAX_VALUE` rather than the end boundary for the last bucket with a non-zero count.

fix bug for p100 percentile approximation

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/IpcLogEntry.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/IpcLogEntryTest.java

If a `Content-Length` header is present and the payload length hasn't already been explicitly set, then try to extract from the header.

ipc: extract content length from header

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

Update query index to automatically dedup results to handle the case of OR clauses where both sides match the same data point. Before, the same match would be returned for each OR clause that matched a given data point. If the consumer did not handle that case, then they could aggregate the same value multiple times leading to incorrect results.
This will add some overhead as the set needs to be maintained, but should improve correctness for general usage.

atlas: handle OR with multiple matches

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/Query.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryTest.java

Disable expansion of `:in` queries when used with the query index. Since the prefix tree matches exactly now the overhead of multiple branches is higher than savings.

atlas: disable in clause expansion

---

spectator-api/src/main/java/com/netflix/spectator/api/patterns/PolledMeter.java

Primitive double values were being passed to the logger in various places, causing them to get boxed; only execute those lines if the logger is enabled at the trace level.

Avoid autoboxing of doubles in PolledMeter

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpRequestBuilder.java

Switch to a static holder class for lazily initializing the default executor to avoid needing to use an explicit lock. Also technically fixes a race condition where multiple executors could get initialized.

Remove ReentrantLock usage in HttpRequestBuilder

---

spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HeaderSanitizer.java
spectator-ext-ipc/src/main/java/com/netflix/spectator/ipc/http/HttpRequestBuilder.java
spectator-ext-ipc/src/test/java/com/netflix/spectator/ipc/http/HeaderSanitizerTest.java
spectator-ext-ipcservlet/src/main/java/com/netflix/spectator/ipcservlet/IpcServletFilter.java

Remove CR or LF in header values to avoid possible header injection.

ipc: sanitize header values

---

spectator-reg-sidecar/src/main/java/com/netflix/spectator/sidecar/SidecarWriter.java

Updates writer config to support the shorthand default `udp` destination similar to clients for other languages.

sidecar: add support for udp destination

---

spectator-api/src/main/java/com/netflix/spectator/api/patterns/LongTaskTimer.java

Avoid looking up the task twice in the map.

api: minor optimization for LongTaskTimer.stop

---

spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/PrefixTree.java
spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/impl/QueryIndex.java
spectator-reg-atlas/src/test/java/com/netflix/spectator/atlas/impl/QueryIndexTest.java

When updating the query index, it was invalidating the cache if there was a query clause that uses the others sub-index. Now it will only invalidate if the particular query clause is different.

atlas: only invalidate cache for changes

---

build.gradle
spectator-api/src/main/java/com/netflix/spectator/impl/Hash64.java
spectator-api/src/main/java/com/netflix/spectator/impl/UnsafeUtils.java
spectator-api/src/test/java/com/netflix/spectator/impl/Hash64Test.java

Update the hash64 helper to stop using Unsafe for accessing the internal array of the String. This will reduce performance, but helps avoid issues on newer JDKs that are locking down internals.

api: reduce usage of unsafe

---

spectator-api/src/main/java/com/netflix/spectator/api/Measurement.java

Use Long.hashCode / Double.hashCode to avoid boxing in Measurment.hashCode.

Avoid boxing in Measurment.hashCode
